#!/usr/bin/env bash
# ================================================================
# validate-iac.sh — IaC Governance Validator (Tool-Agnostic)
# ================================================================
# Validates IaC files against governance rules defined in .claude/rules/iac.instructions.md
# Uses the IaC Tool Descriptor from constitution.md for tool-specific operations
#
# Usage:
#   ./scripts/validate-iac.sh [--strict] [--path <dir>]
#
# Exit codes:
#   0 = All checks passed
#   1 = Secrets detected in IaC files (CRITICAL)
#   2 = Naming convention violations
#   3 = Missing required tags/labels
#   4 = State file committed to VCS
#   5 = Configuration error (missing governance files)
#
# Generated by Agent: SETUP | Feature: SETUP
# ================================================================

set -euo pipefail

# ── Configuration ────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
STRICT_MODE=false
TARGET_PATH="${PROJECT_ROOT}/infra"
EXIT_CODE=0

# ── Argument Parsing ─────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --strict)   STRICT_MODE=true; shift ;;
    --path)     TARGET_PATH="$2"; shift 2 ;;
    --help|-h)
      echo "Usage: $0 [--strict] [--path <dir>]"
      echo ""
      echo "Options:"
      echo "  --strict    Treat warnings as errors (exit non-zero)"
      echo "  --path      Target directory to scan (default: infra/)"
      echo ""
      echo "Exit codes:"
      echo "  0 = All checks passed"
      echo "  1 = Secrets detected (CRITICAL)"
      echo "  2 = Naming convention violations"
      echo "  3 = Missing required tags"
      echo "  4 = State file in VCS"
      echo "  5 = Configuration error"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 5 ;;
  esac
done

# ── Helpers ──────────────────────────────────────────────────────
RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'

pass()  { echo -e "${GREEN}✅ PASS${NC}: $1"; }
warn()  { echo -e "${YELLOW}⚠️  WARN${NC}: $1"; }
fail()  { echo -e "${RED}❌ FAIL${NC}: $1"; }

# ── Pre-Flight ───────────────────────────────────────────────────
if [[ ! -d "$TARGET_PATH" ]]; then
  warn "IaC directory not found: $TARGET_PATH (skipping IaC validation)"
  exit 0
fi

if [[ ! -f "${PROJECT_ROOT}/docs/constitution.md" ]]; then
  fail "Governance file missing: docs/constitution.md"
  exit 5
fi

echo "═══════════════════════════════════════════════════════════════"
echo "  IaC Governance Validator"
echo "  Target: ${TARGET_PATH}"
echo "  Mode: $(if $STRICT_MODE; then echo 'STRICT'; else echo 'STANDARD'; fi)"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# ── Check 1: Secrets Detection (CRITICAL — always blocking) ─────
echo "── Check 1: Secrets Detection ──────────────────────────────"
SECRETS_FOUND=0
FORBIDDEN_PATTERNS=(
  'password\s*=\s*"[^${"]*[a-zA-Z0-9]'
  'api[._-]key\s*=\s*"[^${"]*[a-zA-Z0-9]'
  'secret\s*=\s*"[^${"]*[a-zA-Z0-9]'
  'AWS_ACCESS_KEY_ID\s*=\s*"'
  'AWS_SECRET_ACCESS_KEY\s*=\s*"'
  '-----BEGIN.*PRIVATE KEY-----'
  'token\s*=\s*"[^${"]*[a-zA-Z0-9]'
)

for pattern in "${FORBIDDEN_PATTERNS[@]}"; do
  if grep -rn -E "$pattern" "$TARGET_PATH" --include="*.tf" --include="*.tfvars" \
     --include="*.yaml" --include="*.yml" --include="*.ts" --include="*.py" \
     --include="*.json" 2>/dev/null; then
    SECRETS_FOUND=1
  fi
done

if [[ $SECRETS_FOUND -eq 1 ]]; then
  fail "CRITICAL: Hardcoded secrets detected in IaC files!"
  fail "Policy: Zero secrets in IaC. Use secrets_manager per environment."
  EXIT_CODE=1
else
  pass "No hardcoded secrets detected"
fi
echo ""

# ── Check 2: State Files in VCS ─────────────────────────────────
echo "── Check 2: State Files in VCS ─────────────────────────────"
STATE_PATTERNS=("*.tfstate" "*.tfstate.backup" "Pulumi.*.yaml.bak")
STATE_FOUND=0

for pattern in "${STATE_PATTERNS[@]}"; do
  if find "$TARGET_PATH" -name "$pattern" -type f 2>/dev/null | grep -q .; then
    STATE_FOUND=1
    fail "State file found in repository: $(find "$TARGET_PATH" -name "$pattern" -type f)"
  fi
done

if [[ $STATE_FOUND -eq 1 ]]; then
  fail "State files MUST NOT be committed. Add to .gitignore."
  if [[ $EXIT_CODE -eq 0 ]]; then EXIT_CODE=4; fi
else
  pass "No state files in VCS"
fi
echo ""

# ── Check 3: Naming Conventions ─────────────────────────────────
echo "── Check 3: Directory Naming ───────────────────────────────"
NAMING_VIOLATIONS=0

# Check that module dirs follow kebab-case
if [[ -d "${TARGET_PATH}/modules" ]]; then
  while IFS= read -r dir; do
    dirname=$(basename "$dir")
    if [[ ! "$dirname" =~ ^[a-z][a-z0-9-]*$ ]]; then
      warn "Module directory not kebab-case: $dir"
      NAMING_VIOLATIONS=1
    fi
  done < <(find "${TARGET_PATH}/modules" -mindepth 1 -maxdepth 1 -type d 2>/dev/null)
fi

if [[ $NAMING_VIOLATIONS -eq 1 ]]; then
  if $STRICT_MODE && [[ $EXIT_CODE -eq 0 ]]; then EXIT_CODE=2; fi
else
  pass "Directory naming conventions OK"
fi
echo ""

# ── Check 4: Required Tags (Terraform-specific, extensible) ─────
echo "── Check 4: Required Tags (heuristic) ──────────────────────"
TAG_ISSUES=0

# For Terraform: check that resource blocks contain tags
if find "$TARGET_PATH" -name "*.tf" -type f 2>/dev/null | grep -q .; then
  while IFS= read -r tf_file; do
    # Check if file has resource blocks without tags
    if grep -q 'resource "' "$tf_file" && ! grep -q 'tags' "$tf_file"; then
      warn "Terraform file missing tags block: $tf_file"
      TAG_ISSUES=1
    fi
  done < <(find "$TARGET_PATH" -name "*.tf" -type f ! -name "variables.tf" ! -name "outputs.tf" ! -name "backend.tf" 2>/dev/null)
fi

if [[ $TAG_ISSUES -eq 1 ]]; then
  warn "Some resources may be missing required tags (project, environment, managed_by)"
  if $STRICT_MODE && [[ $EXIT_CODE -eq 0 ]]; then EXIT_CODE=3; fi
else
  pass "Tag checks OK (or no Terraform files found)"
fi
echo ""

# ── Check 5: Module Documentation ───────────────────────────────
echo "── Check 5: Module Documentation ───────────────────────────"
DOC_ISSUES=0

if [[ -d "${TARGET_PATH}/modules" ]]; then
  while IFS= read -r module_dir; do
    if [[ ! -f "${module_dir}/README.md" ]]; then
      warn "Module missing README.md: $module_dir"
      DOC_ISSUES=1
    fi
  done < <(find "${TARGET_PATH}/modules" -mindepth 1 -maxdepth 1 -type d 2>/dev/null)
fi

if [[ $DOC_ISSUES -eq 1 ]]; then
  warn "Some IaC modules lack documentation"
  if $STRICT_MODE && [[ $EXIT_CODE -eq 0 ]]; then EXIT_CODE=2; fi
else
  pass "Module documentation OK"
fi
echo ""

# ── Summary ──────────────────────────────────────────────────────
echo "═══════════════════════════════════════════════════════════════"
if [[ $EXIT_CODE -eq 0 ]]; then
  echo -e "  ${GREEN}All IaC governance checks passed.${NC}"
else
  echo -e "  ${RED}IaC governance violations detected (exit code: $EXIT_CODE).${NC}"
fi
echo "═══════════════════════════════════════════════════════════════"

exit $EXIT_CODE
