#!/usr/bin/env bash
# Generated by Agent: IMPLEMENT | Feature: EVOL-011
# ============================================================================
# check-branch-protection.sh — PreToolUse hook: block Edit/Write on protected branches
# ============================================================================
# Reads stdin JSON from Claude Code hook protocol.
# Exits 1 (blocking) if current git branch is protected.
# ============================================================================

branch=$(git branch --show-current 2>/dev/null || echo '')
if [ -z "$branch" ]; then
  exit 0
fi

if echo "$branch" | grep -qE '^(main|master|develop|release(/.+)?|hotfix)$'; then
  echo "BLOCKED: on protected branch '$branch'. Create a working branch first. Allowed patterns:"
  echo "  feature/ID-slug   fix/slug   bugfix/slug   hotfix/slug   docs/slug   chore/slug"
  echo "Example: git checkout -b hotfix/my-fix origin/main"
  exit 1
fi

exit 0
