#!/usr/bin/env bash
# Generated by Phase: IMPLEMENT | Feature: EVOL-043
# ============================================================================
# deliver-governance.sh — PreToolUse hook (Edit|Write): law at the point of edit
# ============================================================================
# Delivers the families, defect classes and rule pointers that govern THE FILE
# BEING WRITTEN, narrowed by the one applicability resolver (scripts/gate.py
# deliver), within the `budgets.pre_edit` key. The payload travels through the
# only channel a pre-tool hook has to the model: stdout JSON
# {"hookSpecificOutput":{"hookEventName":"PreToolUse","additionalContext":…}}.
# A set already delivered in this session is replaced by a one-line pointer.
# Never blocks (exit 0). Missing reader or config → silent pass.
# ============================================================================
set -u
INPUT="$(cat)"
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo '')"
[ -n "$REPO_ROOT" ] || exit 0
GATE="$REPO_ROOT/scripts/gate.py"
[ -f "$GATE" ] || exit 0
command -v python3 >/dev/null 2>&1 || exit 0
FIELDS=$(printf '%s' "$INPUT" | python3 -c '
import json, sys
try:
    d = json.load(sys.stdin)
    print((d.get("tool_input") or {}).get("file_path", ""))
    print(d.get("session_id", "") or "none")
except Exception:
    print(""); print("none")
' 2>/dev/null) || exit 0
FILE_PATH=$(printf '%s\n' "$FIELDS" | sed -n '1p')
SESSION_ID=$(printf '%s\n' "$FIELDS" | sed -n '2p')
[ -n "$FILE_PATH" ] || exit 0
python3 "$GATE" --repo "$REPO_ROOT" deliver --path "$FILE_PATH" --session "$SESSION_ID" 2>/dev/null || exit 0
exit 0
