#!/usr/bin/env bash
# Generated by Phase: IMPLEMENT | Feature: EVOL-048
# ============================================================================
# record-plan-approval.sh — PostToolUse hook (ExitPlanMode): the ONLY writer of the plan-approval marker.
# ExitPlanMode completes only when the user approved the plan; the reader refuses any other payload (it checks
# the event, the tool, the permission mode and the session transcript). Never blocks (PostToolUse); every failure
# is said through the envelope. Marker: .claude/state/plan-approved-<branch>.json
# ============================================================================
cd "${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}" || exit 0
say() { printf '{"hookSpecificOutput":{"hookEventName":"PostToolUse","additionalContext":"%s"}}\n' "$(printf '%s' "$1" | tr -d '"\\' | tr '\n' ' ' | head -c 400)"; }
if ! command -v python3 >/dev/null 2>&1 || [ ! -f scripts/gate.py ]; then
  say "plan approval NOT recorded: the governance reader (scripts/gate.py) or python3 is not available — run scripts/factory-sync.sh, then approve the plan again"; exit 0
fi
OUT=$(python3 scripts/gate.py plan --record --hook-json 2>&1); RC=$?
[ "$RC" -eq 0 ] || say "plan approval NOT recorded (gate.py plan --record exit $RC): $OUT"
exit 0
