#!/usr/bin/env python3
r"""code_review_hash.py — canonical RDR-1 content hash for the Block 20 marker.

Generated by Phase: [EVOL] | Feature: [EVOL-039]

Reads detect_change_type.py JSON on stdin, filters the `files` dict to
`is_code OR is_test` paths (tests included: pr-test-analyzer reviews them),
drops paths deleted at HEAD, and prints
    sha256("\n".join(sorted(f"{path}\0{git blob sha at HEAD}")))
as 64-hex. Empty reviewable set -> prints "EMPTY", exit 0.

Both the factory-code-review branch pass (marker writer) and preflight.sh
Step 0-bis (marker verifier) run the SAME pipeline:
    detect_change_type.py --git-range BASE..HEAD [--check-secrets] | code_review_hash.py
so the hash is identical by construction. Extra JSON keys are ignored.

Presence of this file doubles as the RDR-2 executor-presence probe consumed
by preflight.sh Step 0-bis (absent -> noisy warning, push passes).

Exit codes: 0 ok (hash or EMPTY on stdout), 2 tooling failure (bad stdin,
missing `files` key, git unavailable) — NEVER 1; findings are not this
script's concern. Git infra failure is exit 2, never disguised as EMPTY.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys


def blob_shas(paths: list[str]) -> dict[str, str] | None:
    """path -> blob sha at HEAD, one git call. None == git itself failed
    (caller exits 2). Paths absent from the dict == deleted at HEAD."""
    try:
        out = subprocess.run(
            ["git", "ls-tree", "-z", "--full-name", "HEAD", "--", *paths],
            capture_output=True, text=True, timeout=30,
        )
    except Exception:
        return None
    if out.returncode != 0:
        return None
    result: dict[str, str] = {}
    for rec in out.stdout.split("\0"):
        if not rec:
            continue
        meta, _, path = rec.partition("\t")
        parts = meta.split()
        if len(parts) >= 3 and parts[1] == "blob":
            result[path] = parts[2]
    return result


def main() -> int:
    try:
        classification = json.load(sys.stdin)
    except Exception:
        print("code_review_hash: cannot parse detect_change_type.py JSON on stdin", file=sys.stderr)
        return 2

    if "files" not in classification or not isinstance(classification["files"], dict):
        print("code_review_hash: 'files' key missing or malformed", file=sys.stderr)
        return 2
    files = classification["files"]

    reviewable = sorted(
        p for p, c in files.items()
        if isinstance(c, dict) and (c.get("is_code") or c.get("is_test"))
    )

    if not reviewable:
        print("EMPTY")
        return 0

    shas = blob_shas(reviewable)
    if shas is None:
        print("code_review_hash: git unavailable or HEAD unreadable", file=sys.stderr)
        return 2

    entries = [f"{path}\0{shas[path]}" for path in reviewable if path in shas]

    if not entries:
        print("EMPTY")  # every reviewable path deleted at HEAD
        return 0

    digest = hashlib.sha256("\n".join(entries).encode("utf-8")).hexdigest()
    print(digest)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:  # keep the never-exit-1 contract
        print(f"code_review_hash: unexpected failure: {exc}", file=sys.stderr)
        sys.exit(2)
