// ============================================================================
// Governance Check on PR — Jenkins Pipeline
// ============================================================================
// Generated by Agent: SETUP | Framework: mi-AI-Factory
// Platform: Jenkins (Declarative Pipeline)
//
// Runs the governance gates that must pass before a PR can merge to main:
//
//   - scripts/check-adr-constitution-sync.sh — EVOL-026 single-source-of-truth
//     gate. Bypass via [adr-backfill] commit message marker.
//
// Wire as a Multibranch Pipeline configured to build PRs (Branch Sources →
// Discover pull requests from origin). The CHANGE_TARGET env var carries the
// target branch name for PR builds.
// ============================================================================

pipeline {
  agent any

  options {
    skipDefaultCheckout(false)
  }

  stages {
    stage('Governance Check') {
      when {
        changeRequest target: 'main'
      }
      steps {
        sh '''
          set -e
          BASE="${CHANGE_TARGET:-main}"
          git fetch origin "$BASE"
          chmod +x scripts/check-adr-constitution-sync.sh
          bash scripts/check-adr-constitution-sync.sh "origin/$BASE"
        '''
      }
    }
  }
}
