# Generated by Phase: IMPLEMENT | Feature: EVOL-043
"""Injection budgets: one home (`config/quality.json` → `budgets`), one reader that runs the REAL producer
against its worst-case input and measures what it emits. Not the file size — the bytes a session receives.

  session_start  scripts/validate-governance.sh --banner
  prompt_submit  scripts/governance-onprompt.sh under GOVERNANCE_ONPROMPT_WORST_CASE=1 (reload + stale warning forced)
  pre_edit       .claude/hooks/deliver-governance.sh on the path that matches the most families and classes
  snapshot       .context/governance_snapshot.md (bytes on disk; n/a where no snapshot exists)
  law_sentence_max_chars / dc_invariant_max_chars  shape budgets, checked over the corpus

A producer that is absent, exits non-zero, or emits nothing (banner, prompt, pre-edit delivery) is a RED row:
a dead producer is exactly the failure the gate exists to catch. A missing budget key is a red row too.
The caller (gate.py budget) exits 1 on any red row; only an unreadable config/quality.json is exit 2.
"""
from __future__ import annotations

import json
import os
import subprocess
import uuid
from pathlib import Path

from .common import GateFault, any_glob, key
from .corpus import catalog, laws

REQUIRED = ("session_start", "prompt_submit", "pre_edit", "snapshot", "law_sentence_max_chars", "dc_invariant_max_chars")
MUST_EMIT = ("session_start", "prompt_submit", "pre_edit")   # an empty emission from these is a dead producer, never "within budget"


class ProducerFault(GateFault):
    """A producer exited non-zero or is absent: a RED row (verdict), not an infrastructure fault."""


def _run(repo: Path, cmd: list[str], stdin: str = "", env: dict | None = None) -> str:
    """Stdout of a producer; a non-zero exit is a GateFault naming the producer and its first stderr line."""
    try:
        r = subprocess.run(cmd, cwd=str(repo), input=stdin, capture_output=True, text=True, timeout=120,
                           env={**os.environ, **(env or {})})
    except (OSError, subprocess.TimeoutExpired) as e:
        raise ProducerFault(f"producer {' '.join(cmd)} could not run: {e}") from None
    if r.returncode != 0:
        first = (r.stderr.strip().splitlines() or ["(no stderr)"])[0]
        raise ProducerFault(f"producer {' '.join(cmd)} exited {r.returncode}: {first}")
    return r.stdout


def _sample(glob: str) -> str:
    """A concrete path under a glob: `src/**` → `src/x/x.py`, `**/*.sql` → `x/x.sql`, `infra/` → `infra/x`."""
    g = glob.strip().strip("`")
    if g.endswith("/"):
        return g + "x"
    out = []
    for p in g.split("/"):
        if p == "**":
            out.append("x")
        elif "*" in p:
            out.append(p.replace("**", "x").replace("*", "x") if "." in p else "x")
        else:
            out.append(p)
    path = "/".join(out)
    return path if "." in Path(path).name else path + "/x.py"


def worst_case_path(cat: dict) -> str:
    """The path that the most defect classes and families govern (sample paths derived from their globs).
    Deterministic: candidates are sorted before the max."""
    globs = [g for f in cat["families"] for g in f["surface"]] + [g for d in cat["dcs"] for g in d["paths"]]
    candidates = {_sample(g) for g in globs if g != "*"}
    # a path can sit under several globs at once (src/** AND **/migrations/**): prepend literal directory
    # prefixes only — a wildcard prefix such as `**/migrations/` is not a directory to prepend
    prefixes = sorted({g[:-3] + "/" for g in globs if g.endswith("/**") and "*" not in g[:-3]})
    for pre in prefixes:
        candidates |= {pre + c for c in sorted(candidates) if not c.startswith(pre)}
    if not candidates:
        return "src/example.py"

    def score(p: str) -> int:
        return sum(1 for d in cat["dcs"] if d["paths"] == ["*"] or any_glob(p, d["paths"])) \
            + sum(1 for f in cat["families"] if any_glob(p, f["surface"]))
    return max(sorted(candidates), key=score)


def measure(repo: Path) -> dict:
    """Bytes emitted by each producer against its key. Every failure is a RED ROW (missing key, absent or
    dead producer, empty emission, overflow) — the caller exits 1. Only an unreadable config is a GateFault."""
    budgets = key(repo, "budgets", default={}) or {}
    cat = catalog(repo)
    rows: dict[str, dict] = {}

    def row(name: str, nbytes: int | None, producer: str, fault: str | None = None):
        cap = budgets.get(name)
        if type(cap) is not int:
            rows[name] = {"budget": None, "bytes": nbytes, "producer": producer, "ok": False, "fault": f"key budgets.{name} missing from config/quality.json"}
            return
        ok = fault is None and (nbytes is None or (nbytes <= cap and (nbytes > 0 or name not in MUST_EMIT)))
        rows[name] = {"budget": cap, "bytes": nbytes, "producer": producer, "ok": ok, "fault": fault}

    def produce(name: str, path: Path, cmd: list[str], producer: str, stdin: str = "", env: dict | None = None):
        if not path.is_file():
            row(name, None, producer, fault=f"producer absent: {path.relative_to(repo)}")
            return
        try:
            row(name, len(_run(repo, cmd, stdin, env).encode()), producer)
        except ProducerFault as e:
            row(name, None, producer, fault=str(e))

    produce("session_start", repo / "scripts/validate-governance.sh", ["bash", "scripts/validate-governance.sh", "--banner"],
            "scripts/validate-governance.sh --banner")
    produce("prompt_submit", repo / "scripts/governance-onprompt.sh", ["bash", "scripts/governance-onprompt.sh"],
            "scripts/governance-onprompt.sh (worst case: snapshot reload + stale warning forced)",
            '{"session_id":"budget","prompt":"x"}', {"GOVERNANCE_ONPROMPT_WORST_CASE": "1"})
    wpath = worst_case_path(cat)
    session = f"budget-{uuid.uuid4().hex}"   # a fresh session per run: the dedupe pointer must never be what is measured
    try:
        produce("pre_edit", repo / ".claude/hooks/deliver-governance.sh", ["bash", ".claude/hooks/deliver-governance.sh"],
                f".claude/hooks/deliver-governance.sh on {wpath}", json.dumps({"tool_input": {"file_path": wpath}, "session_id": session}))
    finally:
        marker = repo / ".claude/state" / f"governance-delivered-{session}.txt"
        if marker.is_file():
            marker.unlink()
    snap = repo / ".context/governance_snapshot.md"
    row("snapshot", snap.stat().st_size if snap.is_file() else None,
        ".context/governance_snapshot.md" + ("" if snap.is_file() else " (absent — n/a here)"))
    allv = laws(repo)
    row("law_sentence_max_chars", max((len(l["sentence"]) for l in allv["universal"] + allv["project"]), default=0),
        "longest law sentence in the index")
    row("dc_invariant_max_chars", max((len(d["invariant"]) for d in cat["dcs"]), default=0), "longest defect-class invariant")
    return rows


def render(rows: dict) -> str:
    out = ["| injection point | budget | measured | producer | |", "|---|---|---|---|---|"]
    for k, r in rows.items():
        state = "ok" if r["ok"] else (f"RED — {r['fault']}" if r.get("fault") else ("EMPTY — dead producer" if r["bytes"] == 0 else "OVERFLOW"))
        out.append(f"| {k} | {r['budget'] if r['budget'] is not None else '—'} | {'n/a' if r['bytes'] is None else r['bytes']} | {r['producer']} | {state} |")
    return "\n".join(out)
