# Generated by Phase: IMPLEMENT | Feature: EVOL-059
"""The lens canary (EVOL-059): calibration under model drift.

The framework keeps model ALIASES; the id behind an alias moves. Before a critic on a newly resolved model reviews
real work, it reviews THIS: one synthetic diff of a synthetic project with two planted defects per lens and the
expected findings — security (a read without the tenant predicate, a planted credential), correctness (a dishonest
test, a contract ↔ DTO mismatch), governance (an artefact without its manifest entry, a manifest changelog without
its bump), fidelity (a specified scenario with no test, a mock state no code implements). Nothing here comes from a
real project.

fixture     the diff, stored base64 AT REST so that no scanner and no regex floor sees the planted credential in the
            repository; decoded only into the critic's scratch input, where the planted line carries the
            `canary-secret` marker. `gate.py canary --fixture` prints it.
expected    per lens: id, what, and the locations a finding may anchor at (file, line in the NEW file).
judge       `--judge --lens L --model ID < return.md`: a planted defect is FOUND when the return carries a finding on
            one of its files within `agents.canary.line_tolerance` lines of the anchor, at a severity above
            informational; the verdict (found, missed) and the model are recorded under `judged` in
            .claude/state/canary.json; red when any planted defect was missed.
seen        `--seen --lens L --model ID`: the model a lens last ran a real round on (from its return's `Model:` line).
plan        `--plan [--all]`: the lenses owed a canary — the model a lens last ran on differs from the one it was last
            judged on, or it was never judged; `--all` owes every lens (on demand). A red canary never blocks the
            train: it opens the review of the spawn policy by RDR with the user.
"""
from __future__ import annotations

import base64
import json
import re
from datetime import datetime, timezone
from pathlib import Path

from .common import GateFault

STATE_DIR = ".claude/state"       # the markers' folder (the push gate's); the canary record lives beside them
RECORD = "canary.json"
LENS_AGENT = {"security": "factory-critic-security", "correctness": "factory-critic-correctness",
              "governance": "factory-critic-governance", "fidelity": "factory-critic-fidelity"}
LENSES = tuple(LENS_AGENT)
SEVERITY_ABOVE_INFO = ("🔴", "🟡")
FINDING = re.compile(r"^\s*(?:[-*]\s+)?(?:\*\*)?(?P<loc>[^\s*`]+):(?P<line>\d+)(?:\*\*)?\s*·\s*(?P<sev>🔴|🟡|🟢|❓)")

FIXTURE_B64 = (
    "ZGlmZiAtLWdpdCBhL3NyYy9vcmRlcnMvcmVwby5weSBiL3NyYy9vcmRlcnMvcmVwby5weQpuZXcgZmlsZSBtb2RlIDEwMDY0NAot"
    "LS0gL2Rldi9udWxsCisrKyBiL3NyYy9vcmRlcnMvcmVwby5weQpAQCAtMCwwICsxLDIyIEBACisiIiJPcmRlciByZXBvc2l0b3J5"
    "IChzeW50aGV0aWMgY2FuYXJ5IHByb2plY3Qg4oCUIG5vdGhpbmcgaGVyZSBpcyByZWFsKS4iIiIKK2ltcG9ydCBvcworCitmcm9t"
    "IC5kYiBpbXBvcnQgcXVlcnkKKworIyBjYW5hcnktc2VjcmV0OiBwbGFudGVkIGZvciB0aGUgbGVucyBjYW5hcnkg4oCUIG5ldmVy"
    "IGEgcmVhbCBjcmVkZW50aWFsCitCSUxMSU5HX0FQSV9LRVkgPSAic2stY2FuYXJ5MDAwMDAwMDAwMDAwMDAwMDAwMDAiCisKKwor"
    "ZGVmIGdldF9vcmRlcihvcmRlcl9pZDogc3RyKSAtPiBkaWN0IHwgTm9uZToKKyAgICAjIHRlbmFudCBzY29waW5nOiBldmVyeSBy"
    "ZWFkIGlzIHNjb3BlZCB0byB0aGUgY2FsbGVyJ3MgdGVuYW50IChzZWUgZG9jcy9zcGVjL0NBTi0wMDEvZGVzaWduLm1kIMKnIDQp"
    "CisgICAgcm93cyA9IHF1ZXJ5KCJTRUxFQ1QgaWQsIHRlbmFudF9pZCwgc3RhdHVzLCB0b3RhbF9jZW50cyBGUk9NIG9yZGVycyBX"
    "SEVSRSBpZCA9ID8iLCAob3JkZXJfaWQsKSkKKyAgICByZXR1cm4gcm93c1swXSBpZiByb3dzIGVsc2UgTm9uZQorCisKK2RlZiBs"
    "aXN0X29yZGVycyh0ZW5hbnRfaWQ6IHN0ciwgc3RhdHVzOiBzdHIgfCBOb25lID0gTm9uZSkgLT4gbGlzdFtkaWN0XToKKyAgICBz"
    "cWwgPSAiU0VMRUNUIGlkLCB0ZW5hbnRfaWQsIHN0YXR1cywgdG90YWxfY2VudHMgRlJPTSBvcmRlcnMgV0hFUkUgdGVuYW50X2lk"
    "ID0gPyIKKyAgICBwYXJhbXM6IGxpc3QgPSBbdGVuYW50X2lkXQorICAgIGlmIHN0YXR1czoKKyAgICAgICAgc3FsICs9ICIgQU5E"
    "IHN0YXR1cyA9ID8iCisgICAgICAgIHBhcmFtcy5hcHBlbmQoc3RhdHVzKQorICAgIHJldHVybiBxdWVyeShzcWwsIHR1cGxlKHBh"
    "cmFtcykpCmRpZmYgLS1naXQgYS9zcmMvb3JkZXJzL2R0by5weSBiL3NyYy9vcmRlcnMvZHRvLnB5Cm5ldyBmaWxlIG1vZGUgMTAw"
    "NjQ0Ci0tLSAvZGV2L251bGwKKysrIGIvc3JjL29yZGVycy9kdG8ucHkKQEAgLTAsMCArMSwxMiBAQAorIiIiT3JkZXIgRFRPcyDi"
    "gJQgdGhlIGNvbnRyYWN0IHRoZSBBUEkgcHVibGlzaGVzIChjb250cmFjdHMvb3JkZXJzLm9wZW5hcGkueWFtbCkuIiIiCitmcm9t"
    "IGRhdGFjbGFzc2VzIGltcG9ydCBkYXRhY2xhc3MKKworCitAZGF0YWNsYXNzKGZyb3plbj1UcnVlKQorY2xhc3MgT3JkZXJPdXQ6"
    "CisgICAgaWQ6IHN0cgorICAgIHN0YXR1czogc3RyCisgICAgdG90YWxfY2VudHM6IGludCAgICAgICAgICAjIHRoZSBjb250cmFj"
    "dDogYW4gaW50ZWdlciBvZiBjZW50cworCisKK1NUQVRVU0VTID0gKCJuZXciLCAicGFpZCIsICJzaGlwcGVkIikKZGlmZiAtLWdp"
    "dCBhL3NyYy9vcmRlcnMvYXBpLnB5IGIvc3JjL29yZGVycy9hcGkucHkKbmV3IGZpbGUgbW9kZSAxMDA2NDQKLS0tIC9kZXYvbnVs"
    "bAorKysgYi9zcmMvb3JkZXJzL2FwaS5weQpAQCAtMCwwICsxLDIxIEBACisiIiJPcmRlciBlbmRwb2ludHMgKHN5bnRoZXRpYyBj"
    "YW5hcnkgcHJvamVjdCkuIiIiCitmcm9tIC5kdG8gaW1wb3J0IE9yZGVyT3V0LCBTVEFUVVNFUworZnJvbSAucmVwbyBpbXBvcnQg"
    "Z2V0X29yZGVyLCBsaXN0X29yZGVycworCisKK2RlZiByZWFkX29yZGVyKG9yZGVyX2lkOiBzdHIsIHRlbmFudF9pZDogc3RyKSAt"
    "PiBkaWN0OgorICAgIHJvdyA9IGdldF9vcmRlcihvcmRlcl9pZCkKKyAgICBpZiByb3cgaXMgTm9uZToKKyAgICAgICAgcmV0dXJu"
    "IHsiZXJyb3IiOiAibm90IGZvdW5kIn0sIDQwNAorICAgIHJldHVybiB7ImlkIjogcm93WyJpZCJdLCAic3RhdHVzIjogcm93WyJz"
    "dGF0dXMiXSwgInRvdGFsIjogcm93WyJ0b3RhbF9jZW50cyJdIC8gMTAwLjB9CisKKworZGVmIHJlYWRfb3JkZXJzKHRlbmFudF9p"
    "ZDogc3RyLCBzdGF0dXM6IHN0ciB8IE5vbmUgPSBOb25lKSAtPiBsaXN0W2RpY3RdOgorICAgIHJldHVybiBbT3JkZXJPdXQoclsi"
    "aWQiXSwgclsic3RhdHVzIl0sIHJbInRvdGFsX2NlbnRzIl0pLl9fZGljdF9fIGZvciByIGluIGxpc3Rfb3JkZXJzKHRlbmFudF9p"
    "ZCwgc3RhdHVzKV0KKworCitkZWYgc2V0X3N0YXR1cyhvcmRlcl9pZDogc3RyLCB0ZW5hbnRfaWQ6IHN0ciwgc3RhdHVzOiBzdHIp"
    "IC0+IGRpY3Q6CisgICAgaWYgc3RhdHVzIG5vdCBpbiBTVEFUVVNFUzoKKyAgICAgICAgcmV0dXJuIHsiZXJyb3IiOiAidW5rbm93"
    "biBzdGF0dXMifSwgNDAwCisgICAgIyBjYW5jZWwgaXMgbm90IGEgc3RhdHVzIHRoaXMgc2VydmljZSBrbm93czogc2VlIHRoZSBt"
    "b2NrLCBzdGVwIDMKKyAgICByZXR1cm4geyJpZCI6IG9yZGVyX2lkLCAic3RhdHVzIjogc3RhdHVzfQpkaWZmIC0tZ2l0IGEvdGVz"
    "dHMvdGVzdF9vcmRlcnMucHkgYi90ZXN0cy90ZXN0X29yZGVycy5weQpuZXcgZmlsZSBtb2RlIDEwMDY0NAotLS0gL2Rldi9udWxs"
    "CisrKyBiL3Rlc3RzL3Rlc3Rfb3JkZXJzLnB5CkBAIC0wLDAgKzEsMjAgQEAKK2ltcG9ydCBweXRlc3QKKworZnJvbSBzcmMub3Jk"
    "ZXJzLmFwaSBpbXBvcnQgcmVhZF9vcmRlciwgcmVhZF9vcmRlcnMsIHNldF9zdGF0dXMKKworCitAcHl0ZXN0Lm1hcmsuY2FzZSgi"
    "Q0FOLTAwMS9UQy0wMSIpCitkZWYgdGVzdF9yZWFkX29yZGVyX3JldHVybnNfdGhlX3RvdGFsX2luX2NlbnRzKG1vbmtleXBhdGNo"
    "KToKKyAgICBtb25rZXlwYXRjaC5zZXRhdHRyKCJzcmMub3JkZXJzLmFwaS5nZXRfb3JkZXIiLCBsYW1iZGEgb2lkOiB7ImlkIjog"
    "b2lkLCAic3RhdHVzIjogInBhaWQiLCAidG90YWxfY2VudHMiOiAxMjUwfSkKKyAgICBvdXQgPSByZWFkX29yZGVyKCJvLTEiLCAi"
    "dC0xIikKKyAgICBhc3NlcnQgb3V0ICAjIHRoZSByZXNwb25zZSBpcyB0cnV0aHkg4oCUIHNlZSBUQy0wMSBleHBlY3RlZDogdG90"
    "YWxfY2VudHMgPT0gMTI1MAorCisKK0BweXRlc3QubWFyay5jYXNlKCJDQU4tMDAxL1RDLTAyIikKK2RlZiB0ZXN0X2xpc3Rfb3Jk"
    "ZXJzX2lzX3Njb3BlZF90b190aGVfdGVuYW50KG1vbmtleXBhdGNoKToKKyAgICBtb25rZXlwYXRjaC5zZXRhdHRyKCJzcmMub3Jk"
    "ZXJzLmFwaS5saXN0X29yZGVycyIsIGxhbWJkYSB0LCBzPU5vbmU6IFt7ImlkIjogIm8tMSIsICJzdGF0dXMiOiAibmV3IiwgInRv"
    "dGFsX2NlbnRzIjogNX1dKQorICAgIGFzc2VydCByZWFkX29yZGVycygidC0xIikgPT0gW3siaWQiOiAiby0xIiwgInN0YXR1cyI6"
    "ICJuZXciLCAidG90YWxfY2VudHMiOiA1fV0KKworCitkZWYgdGVzdF9zZXRfc3RhdHVzX3JlamVjdHNfdW5rbm93bigpOgorICAg"
    "IGFzc2VydCBzZXRfc3RhdHVzKCJvLTEiLCAidC0xIiwgInRlbGVwb3J0ZWQiKVsxXSA9PSA0MDAKZGlmZiAtLWdpdCBhL2RvY3Mv"
    "c3BlYy9DQU4tMDAxL3NwZWMuZmVhdHVyZSBiL2RvY3Mvc3BlYy9DQU4tMDAxL3NwZWMuZmVhdHVyZQpuZXcgZmlsZSBtb2RlIDEw"
    "MDY0NAotLS0gL2Rldi9udWxsCisrKyBiL2RvY3Mvc3BlYy9DQU4tMDAxL3NwZWMuZmVhdHVyZQpAQCAtMCwwICsxLDE5IEBACitG"
    "ZWF0dXJlOiBPcmRlcnMgKHN5bnRoZXRpYyBjYW5hcnkgZmVhdHVyZSBDQU4tMDAxKQorCisgIFNjZW5hcmlvOiBSZWFkIGFuIG9y"
    "ZGVyIHdpdGggaXRzIHRvdGFsICAgICAgICAgICMgVEMtMDEKKyAgICBHaXZlbiBhbiBvcmRlciAiby0xIiBvZiAxMi41MCBmb3Ig"
    "dGVuYW50ICJ0LTEiCisgICAgV2hlbiB0aGUgQVBJIHJlYWRzICJvLTEiCisgICAgVGhlbiB0aGUgcmVzcG9uc2UgY2FycmllcyB0"
    "b3RhbF9jZW50cyAxMjUwCisKKyAgU2NlbmFyaW86IExpc3QgdGhlIHRlbmFudCdzIG9yZGVycyBvbmx5ICAgICAgICAgIyBUQy0w"
    "MgorICAgIEdpdmVuIG9yZGVycyBmb3IgdGVuYW50cyAidC0xIiBhbmQgInQtMiIKKyAgICBXaGVuIHRoZSBBUEkgbGlzdHMgb3Jk"
    "ZXJzIGZvciAidC0xIgorICAgIFRoZW4gb25seSAidC0xIiBvcmRlcnMgYXJlIHJldHVybmVkCisKKyAgU2NlbmFyaW86IENhbmNl"
    "bCBhbiBvcmRlciAgICAgICAgICAgICAgICAgICAgICAgICMgVEMtMDMKKyAgICBHaXZlbiBhIHBhaWQgb3JkZXIgIm8tMSIgZm9y"
    "IHRlbmFudCAidC0xIgorICAgIFdoZW4gdGhlIGN1c3RvbWVyIGNhbmNlbHMgIm8tMSIKKyAgICBUaGVuIHRoZSBvcmRlciBzdGF0"
    "dXMgaXMgImNhbmNlbGxlZCIKKyAgICBBbmQgdGhlIGN1c3RvbWVyIHNlZXMgdGhlIGNhbmNlbGxlZCBzdGF0ZSAobW9jayBzdGVw"
    "IDMpCisKKyAgIyBUQy0wMyBpcyBzcGVjaWZpZWQgYnkgdGhlIGJ1c2luZXNzIG93bmVyOyB0aGUgbW9jayBzaG93cyB0aGUgY2Fu"
    "Y2VsbGVkIHN0YXRlIGF0ICNzdGVwLTMKZGlmZiAtLWdpdCBhL2RvY3Mvc3BlYy9DQU4tMDAxL21vY2suaHRtbCBiL2RvY3Mvc3Bl"
    "Yy9DQU4tMDAxL21vY2suaHRtbApuZXcgZmlsZSBtb2RlIDEwMDY0NAotLS0gL2Rldi9udWxsCisrKyBiL2RvY3Mvc3BlYy9DQU4t"
    "MDAxL21vY2suaHRtbApAQCAtMCwwICsxLDkgQEAKKzwhZG9jdHlwZSBodG1sPgorPG1haW4+CisgIDxzZWN0aW9uIGlkPSJzdGVw"
    "LTEiPjxoMj5Zb3VyIG9yZGVyPC9oMj48cD5Ub3RhbDogPGI+MTIuNTA8L2I+PC9wPjwvc2VjdGlvbj4KKyAgPHNlY3Rpb24gaWQ9"
    "InN0ZXAtMiI+PGgyPllvdXIgb3JkZXJzPC9oMj48dWw+PGxpPm8tMSDCtyBwYWlkPC9saT48L3VsPjwvc2VjdGlvbj4KKyAgPHNl"
    "Y3Rpb24gaWQ9InN0ZXAtMyIgZGF0YS1zdGF0ZT0iY2FuY2VsbGVkIj4KKyAgICA8aDI+T3JkZXIgY2FuY2VsbGVkPC9oMj4KKyAg"
    "ICA8cD5Zb3VyIG9yZGVyIG8tMSB3YXMgY2FuY2VsbGVkLiBBIHJlZnVuZCBvZiAxMi41MCBpcyBvbiBpdHMgd2F5LjwvcD4KKyAg"
    "PC9zZWN0aW9uPgorPC9tYWluPgpkaWZmIC0tZ2l0IGEvLmNsYXVkZS9za2lsbHMvb3JkZXJzLWhlbHBlci9TS0lMTC5tZCBiLy5j"
    "bGF1ZGUvc2tpbGxzL29yZGVycy1oZWxwZXIvU0tJTEwubWQKbmV3IGZpbGUgbW9kZSAxMDA2NDQKLS0tIC9kZXYvbnVsbAorKysg"
    "Yi8uY2xhdWRlL3NraWxscy9vcmRlcnMtaGVscGVyL1NLSUxMLm1kCkBAIC0wLDAgKzEsOCBAQAorLS0tCituYW1lOiBvcmRlcnMt"
    "aGVscGVyCitkZXNjcmlwdGlvbjogIkhlbHBlciBza2lsbCBmb3IgdGhlIG9yZGVycyBzdXJmYWNlIChzeW50aGV0aWMgY2FuYXJ5"
    "IHByb2plY3QpLiIKKy0tLQorCisjIG9yZGVycy1oZWxwZXIKKworVXNlIHdoZW4gdG91Y2hpbmcgc3JjL29yZGVycy8qKi4gUmVh"
    "ZHMgdGhlIERUTyBjb250cmFjdCBmaXJzdC4KZGlmZiAtLWdpdCBhL2RvY3MvcHJvamVjdF9sb2cvZ292ZXJuYW5jZV92ZXJzaW9u"
    "cy5qc29uIGIvZG9jcy9wcm9qZWN0X2xvZy9nb3Zlcm5hbmNlX3ZlcnNpb25zLmpzb24KLS0tIGEvZG9jcy9wcm9qZWN0X2xvZy9n"
    "b3Zlcm5hbmNlX3ZlcnNpb25zLmpzb24KKysrIGIvZG9jcy9wcm9qZWN0X2xvZy9nb3Zlcm5hbmNlX3ZlcnNpb25zLmpzb24KQEAg"
    "LTEsOCArMSw5IEBACiB7CiAgICJmcmFtZXdvcmtfdmVyc2lvbiI6ICI4LjYuMCIsCiAgICJ0ZW1wbGF0ZXMiOiB7CiAgICAgInJ1"
    "bGVzL3Rlc3RpbmcubWQiOiB7CiAgICAgICAidmVyc2lvbiI6ICIxLjIuMCIsCiAgICAgICAiY2hhbmdlbG9nIjogWworICAgICAg"
    "ICAiMS4yLjA6IGZlYXQoQ0FOLTAwMSkg4oCUIHRoZSBvcmRlcnMgcnVsZTogZXZlcnkgcmVhZCBzY29wZWQgdG8gdGhlIHRlbmFu"
    "dCIsCiAgICAgICAgICIxLjIuMDogZmVhdChFVk9MLTA0MCkg4oCUIGluaXRpYWwiCiAgICAgICBdCg=="
)

EXPECTED: dict[str, list[dict]] = {
    "security": [
        {"id": "s1", "what": "a read without the tenant predicate (an order of another tenant is readable by id)",
         "at": [["src/orders/repo.py", 12], ["src/orders/api.py", 7]]},
        {"id": "s2", "what": "a credential in code (the planted line carries the canary-secret marker)",
         "at": [["src/orders/repo.py", 7]]},
    ],
    "correctness": [
        {"id": "c1", "what": "a dishonest test — the assertion never reaches the expected result it names",
         "at": [["tests/test_orders.py", 10]]},
        {"id": "c2", "what": "the contract publishes total_cents (an integer), the handler returns total (a float)",
         "at": [["src/orders/api.py", 10], ["src/orders/dto.py", 9]]},
    ],
    "governance": [
        {"id": "g1", "what": "an artefact added without its manifest entry",
         "at": [[".claude/skills/orders-helper/SKILL.md", 4]]},
        {"id": "g2", "what": "a manifest changelog line added without its version bump",
         "at": [["docs/project_log/governance_versions.json", 7]]},
    ],
    "fidelity": [
        {"id": "f1", "what": "a specified scenario (TC-03, cancel an order) with no test",
         "at": [["docs/spec/CAN-001/spec.feature", 13], ["tests/test_orders.py", 19], ["src/orders/api.py", 20]]},   # a critic may fold the untested scenario and the unimplemented state into one finding at the stub
        {"id": "f2", "what": "a mock state (#step-3, cancelled) that no code implements",
         "at": [["docs/spec/CAN-001/mock.html", 5], ["src/orders/api.py", 20], ["src/orders/dto.py", 12]]},
    ],
}


def fixture() -> str:
    return base64.b64decode(FIXTURE_B64).decode("utf-8")


def added_lines(diff: str, positions: dict[str, dict[int, int]] | None = None) -> dict[str, dict[int, str]]:
    """path → {line in the NEW file: text} for every `+` line, from the hunk headers. `positions`, when given, is
    filled with path → {line of the DIFF TEXT: line in the new file} — a critic handed the raw diff may count
    the diff's own lines; the judge accepts both coordinates."""
    out: dict[str, dict[int, str]] = {}
    path, new_no = None, 0
    for i, raw in enumerate(diff.splitlines(), 1):
        if raw.startswith("+++ "):
            path = raw[4:].strip()
            path = path[2:] if path.startswith("b/") else path
            out.setdefault(path, {})
            if positions is not None:
                positions.setdefault(path, {})
            continue
        m = re.match(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@", raw)
        if m:
            new_no = int(m.group(1))
            continue
        if path is None or raw.startswith("---") or raw.startswith("diff "):
            continue
        if raw.startswith("+"):
            out[path][new_no] = raw[1:]
            if positions is not None:
                positions[path][i] = new_no
            new_no += 1
        elif raw.startswith("-"):
            continue
        elif raw.startswith(" ") or raw == "":
            new_no += 1
    return out


def consistency() -> list[str]:
    """The fixture holds its own promises: every anchor is an added line, the planted credential carries its marker and
    is invisible at rest, every lens has a roster agent."""
    problems: list[str] = []
    try:
        diff = fixture()
    except Exception as e:   # noqa: BLE001 — a fixture that does not decode is the finding
        return [f"the fixture does not decode: {e}"]
    added = added_lines(diff)
    for lens, items in EXPECTED.items():
        for it in items:
            for f, n in it["at"]:
                if n not in added.get(f, {}):
                    problems.append(f"{lens}/{it['id']}: anchor {f}:{n} is not an added line of the fixture")
    secret = [n for n, t in added.get("src/orders/repo.py", {}).items() if "canary-secret" in t]
    if not secret:
        problems.append("the planted credential's marker line (`canary-secret`) is missing from the fixture")
    at_rest = Path(__file__).read_text(encoding="utf-8", errors="replace")
    planted = next((t.strip() for t in added.get("src/orders/repo.py", {}).values() if "BILLING" in t), "")
    if planted and planted in at_rest:   # the decoded line itself, never spelled in this file
        problems.append("the planted credential is visible at rest — the fixture must stay encoded in this file")
    return problems


def tolerance(repo: Path) -> int:
    from . import agents as agents_mod   # the one policy home
    pol = agents_mod.policy(repo)
    c = pol.get("canary") if isinstance(pol.get("canary"), dict) else None
    v = c.get("line_tolerance") if c else None
    if isinstance(v, bool) or not isinstance(v, int) or v < 0:
        raise GateFault("agents.canary.line_tolerance must be a non-negative integer in rules/agents.md — the canary's match window is a key (EVOL-059)")
    return v


def findings(text: str) -> list[tuple[str, int, str]]:
    out = []
    for line in text.splitlines():
        m = FINDING.match(line)
        if m:
            f = m.group("loc")
            f = f[2:] if f.startswith("./") else f
            out.append((f, int(m.group("line")), m.group("sev")))
    return out


def _record_path(repo: Path) -> Path:
    return repo / STATE_DIR / RECORD


def read_record(repo: Path) -> dict:
    p = _record_path(repo)
    if not p.is_file():
        return {"judged": {}, "seen": {}}
    try:
        d = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        raise GateFault(f"the canary record {p.relative_to(repo)} is unreadable ({e}) — delete it and judge the lenses again") from None
    if not isinstance(d, dict):
        raise GateFault(f"the canary record {p.relative_to(repo)} is not a mapping — delete it and judge the lenses again")
    d.setdefault("judged", {}); d.setdefault("seen", {})
    return d


def _write_record(repo: Path, d: dict) -> None:
    p = _record_path(repo)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(".tmp")
    tmp.write_text(json.dumps(d, indent=0, sort_keys=True), encoding="utf-8")
    tmp.replace(p)


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _lens(lens: str) -> str:
    if lens not in EXPECTED:
        raise GateFault(f"lens `{lens}` is not one of {', '.join(LENSES)}")
    return lens


def judge(repo: Path, lens: str, text: str, model: str) -> dict:
    """Compare a critic's return over the fixture to the lens's planted defects; record; red when any was missed."""
    lens = _lens(lens)
    model = (model or "").strip()
    if not model:
        raise GateFault("--judge needs --model: the id the critic's return carries on its `Model:` line (the harness states it; `unknown` when it does not)")
    tol = tolerance(repo)
    positions: dict[str, dict[int, int]] = {}
    added_lines(fixture(), positions)
    got = []
    for f, n, sev in findings(text):
        if sev in SEVERITY_ABOVE_INFO:
            got.append((f, n))                                   # the line as the critic wrote it (the new file)
            if n in positions.get(f, {}):
                got.append((f, positions[f][n]))                 # or the diff text's own line, mapped to the new file
    found, missed = [], []
    for it in EXPECTED[lens]:
        hit = any(f == af and abs(n - an) <= tol for f, n in got for af, an in it["at"])
        (found if hit else missed).append(it["id"])
    d = read_record(repo)
    d["judged"][lens] = {"model": model, "at": _now(), "found": found, "missed": missed}
    _write_record(repo, d)
    return {"ok": not missed, "lens": lens, "model": model, "found": found, "missed": missed, "tolerance": tol,
            "findings": len(got), "reason": ("every planted defect found" if not missed else
                                             "missed: " + ", ".join(f"{m} ({next(i['what'] for i in EXPECTED[lens] if i['id'] == m)})" for m in missed))}


def seen(repo: Path, lens: str, model: str) -> dict:
    lens = _lens(lens)
    model = (model or "").strip() or "unknown"
    d = read_record(repo)
    d["seen"][lens] = {"model": model, "at": _now()}
    _write_record(repo, d)
    return {"ok": True, "lens": lens, "model": model}


def plan(repo: Path, all_: bool = False) -> dict:
    d = read_record(repo)
    owed, lenses = [], {}
    for lens in LENSES:
        j, s = d["judged"].get(lens) or {}, d["seen"].get(lens) or {}
        judged, current = j.get("model"), s.get("model")
        if all_:
            why = "on demand"
        elif not judged:
            why = "never judged"
        elif current and current != judged:
            why = f"the model moved: judged on `{judged}`, last ran on `{current}`"
        elif current == "unknown" or judged == "unknown":
            why = "the model is unknown (the return carried no id) — judged until it is known"
        else:
            why = ""
        lenses[lens] = {"agent": LENS_AGENT[lens], "judged_on": judged, "last_ran_on": current, "missed": j.get("missed"), "reason": why or "judged on the model it last ran on"}
        if why:
            owed.append(lens)
    return {"owed": owed, "lenses": lenses, "fixture_ok": not consistency()}


def render_plan(r: dict) -> str:
    lines = [f"canary: {'owed — ' + ', '.join(r['owed']) if r['owed'] else 'nothing owed — every lens judged on the model it last ran on'}"]
    for lens, v in r["lenses"].items():
        lines.append(f"  {'→' if lens in r['owed'] else '·'} {lens} ({v['agent']}): judged on {v['judged_on'] or '—'} · last ran on {v['last_ran_on'] or '—'}"
                     + (f" · missed {', '.join(v['missed'])}" if v.get("missed") else "") + f" — {v['reason']}")
    if not r["fixture_ok"]:
        lines.append("  ✗ the fixture is inconsistent — gate.py canary --check names it")
    if r["owed"]:
        lines.append("  run: for each owed lens — gate.py agents --resolve --class work-critic, the fixture (gate.py canary --fixture) as the diff, the return "
                     "check, then gate.py canary --judge --lens <lens> --model <the return's Model: line>; post the verdict on the tracking item; a red canary opens the spawn policy's review by RDR")
    return "\n".join(lines)


def render_judge(r: dict) -> str:
    return (f"canary: {'ok' if r['ok'] else 'RED'} — {r['lens']} on {r['model']}: found {', '.join(r['found']) or 'none'}; "
            f"{r['reason']} ({r['findings']} finding(s) above informational read, ±{r['tolerance']} lines)"
            + ("" if r["ok"] else "\n  a red canary never blocks the train: it opens the review of the spawn policy (rules/agents.md → families, ladder, resolve rows) by RDR with the user"))
