# Generated by Phase: IMPLEMENT | Feature: EVOL-059
"""The lens canary (EVOL-059): calibration under model drift.

The framework keeps model ALIASES; the id behind an alias moves. As soon as a lens is known to have run on a moved
model (its first real round on it tells the id), it reviews THIS before its next real work: one synthetic diff of a synthetic project with two planted defects per lens and the
expected findings — security (a read without the tenant predicate, a planted credential), correctness (a dishonest
test, a contract ↔ DTO mismatch), governance (an artefact without its manifest entry, a manifest changelog without
its bump), fidelity (a specified scenario with no test, a mock state no code implements). Nothing here comes from a
real project.

fixture     the diff, stored base64 AT REST so that no scanner and no regex floor sees the planted credential in the
            repository (a literal scanner; one that decodes base64 is not fooled, and need not be — the credential is
            invented); decoded only into the critic's scratch input OUTSIDE the tree, where the planted line itself
            carries the `canary-secret` marker. `gate.py canary --fixture` prints it, writes nothing.
expected    per lens: id, what, and the locations a finding may anchor at (file, line in the NEW file).
judge       `--judge --lens L --model ID < return.md`: a planted defect is FOUND when the return carries a finding on
            one of its files (the path's tail), within `agents.canary.line_tolerance` lines of the anchor in the NEW
            file's numbering or in the diff text's own (a critic counts either way; the filler leading the diff keeps
            the two spaces apart), at a severity above informational; the verdict (found, missed) and the model are
            recorded under `judged` in .claude/state/canary.json; red when any planted defect was missed; a return
            with no finding in the contract shape and no `no findings` line is a fault, not a verdict.
seen        `--seen --lens L --model ID`: the model a lens last ran a real round on (from its return's `Model:` line).
plan        `--plan [--all]`: the lenses owed a canary — the model a lens last ran on differs from the one it was last
            judged on, it was never judged, or the id is `unknown`; `--all` owes every lens (on demand). The id is known from a return, so
            a lens's first real round on a moved model runs before the canary owes it — the canary follows that round.
            A red canary never blocks the train: it opens the review of the spawn policy by RDR with the user.
"""
from __future__ import annotations

import base64
import json
import re
from datetime import datetime, timezone
from pathlib import Path

from .common import GateFault

STATE_DIR = ".claude/state"       # the markers' folder (the push gate's); the canary record lives beside them
RECORD = "canary.json"
LENS_AGENT = {"security": "factory-critic-security", "correctness": "factory-critic-correctness",
              "governance": "factory-critic-governance", "fidelity": "factory-critic-fidelity"}
LENSES = tuple(LENS_AGENT)
SEVERITY_ABOVE_INFO = ("🔴", "🟡")
DEFAULT_TOLERANCE = 3   # the template's `agents.canary.line_tolerance`; the fixture is checked against it when no repo is at hand

FIXTURE_B64 = (
    "ZGlmZiAtLWdpdCBhL1JFQURNRS5tZCBiL1JFQURNRS5tZApuZXcgZmlsZSBtb2RlIDEwMDY0NAotLS0gL2Rldi9udWxsCisrKyBi"
    "L1JFQURNRS5tZApAQCAtMCwwICsxLDQwIEBACisjIE9yZGVycyAoc3ludGhldGljIGNhbmFyeSBwcm9qZWN0KQorCitOb3RoaW5n"
    "IGluIHRoaXMgcHJvamVjdCBpcyByZWFsLiBJdCBleGlzdHMgc28gdGhhdCBhIHJlYWQtb25seSBjcml0aWMgY2FuIGJlIGNhbGli"
    "cmF0ZWQ6CitldmVyeSBmaWxlIGJlbG93IGlzIGludmVudGVkLCBldmVyeSBpZCBpcyBhIHBsYWNlaG9sZGVyLCBldmVyeSBkZWZl"
    "Y3QgaXMgcGxhbnRlZCBvbiBwdXJwb3NlLgorCisjIyBMYXlvdXQKKworLSBgc3JjL29yZGVycy9yZXBvLnB5YCDigJQgdGhlIHJl"
    "cG9zaXRvcnkgKHJlYWRzIGFuZCBsaXN0cyBvcmRlcnMpCistIGBzcmMvb3JkZXJzL2R0by5weWAg4oCUIHRoZSBwdWJsaXNoZWQg"
    "Y29udHJhY3QKKy0gYHNyYy9vcmRlcnMvYXBpLnB5YCDigJQgdGhlIGVuZHBvaW50cworLSBgdGVzdHMvdGVzdF9vcmRlcnMucHlg"
    "IOKAlCB0aGUgdGVzdHMgdGhlIHBsYW4gZGVjbGFyZXMKKy0gYGRvY3Mvc3BlYy9DQU4tMDAxL3NwZWMuZmVhdHVyZWAg4oCUIHRo"
    "ZSBidXNpbmVzcyBzY2VuYXJpb3MKKy0gYGRvY3Mvc3BlYy9DQU4tMDAxL21vY2suaHRtbGAg4oCUIHRoZSBtb2NrIHRoZSBidXNp"
    "bmVzcyBvd25lciB2YWxpZGF0ZWQKKy0gYC5jbGF1ZGUvc2tpbGxzL29yZGVycy1oZWxwZXIvU0tJTEwubWRgIOKAlCBhIGhlbHBl"
    "ciBza2lsbAorLSBgZG9jcy9wcm9qZWN0X2xvZy9nb3Zlcm5hbmNlX3ZlcnNpb25zLmpzb25gIOKAlCB0aGUgZ292ZXJuYW5jZSBt"
    "YW5pZmVzdAorCisjIyBSdWxlcyB0aGlzIHByb2plY3QgZm9sbG93cworCisxLiBFdmVyeSByZWFkIGFuZCB3cml0ZSBpcyBzY29w"
    "ZWQgdG8gdGhlIGNhbGxlcidzIHRlbmFudC4KKzIuIE5vIGNyZWRlbnRpYWwgbGl2ZXMgaW4gY29kZTogY29uZmlndXJhdGlvbiBh"
    "bmQgdGhlIHZhdWx0IHN1cHBseSB0aGVtLgorMy4gVGhlIERUTyBpcyB0aGUgY29udHJhY3QgdGhlIEFQSSBwdWJsaXNoZXM7IGEg"
    "aGFuZGxlciBuZXZlciBkZXBhcnRzIGZyb20gaXQuCis0LiBFdmVyeSBzY2VuYXJpbyB0aGUgYnVzaW5lc3Mgb3duZXIgc3BlY2lm"
    "aWVkIGhhcyBhIHRlc3QgcmVhY2hpbmcgaXRzIGV4cGVjdGVkIHJlc3VsdC4KKzUuIEV2ZXJ5IHN0YXRlIHRoZSB2YWxpZGF0ZWQg"
    "bW9jayBzaG93cyBpcyBpbXBsZW1lbnRlZC4KKzYuIEV2ZXJ5IGZyYW1ld29yayBhcnRlZmFjdCB1bmRlciBgLmNsYXVkZS8qKmAg"
    "aXMgcmVnaXN0ZXJlZCBpbiB0aGUgZ292ZXJuYW5jZSBtYW5pZmVzdC4KKzcuIEEgbWFuaWZlc3QgZW50cnkgd2hvc2UgY2hhbmdl"
    "bG9nIGdhaW5zIGEgbGluZSBtb3ZlcyBpdHMgdmVyc2lvbiBpbiB0aGUgc2FtZSBjaGFuZ2UuCisKKyMjIEhvdyB0byBydW4KKwor"
    "YGBgCitweXRlc3QgLXEKK2BgYAorCisjIyBOb3RlcworCitUaGlzIFJFQURNRSBsZWFkcyB0aGUgZGlmZiBvbiBwdXJwb3NlOiB0"
    "aGUgbGluZXMgb2YgdGhlIGRpZmYgdGV4dCBhbmQgdGhlIGxpbmVzIG9mIHRoZSBmaWxlcworYmVsb3cgbmV2ZXIgc2hhcmUgYSBu"
    "dW1iZXIgcmFuZ2UsIHNvIGEgY3JpdGljIHRoYXQgY291bnRzIGVpdGhlciB3YXkgaXMgcmVhZCB0aGUgc2FtZS4KKworTm90aGlu"
    "ZyB0byBkZXBsb3kuIE5vdGhpbmcgdG8gY29uZmlndXJlLiBOb3RoaW5nIGhlcmUgaXMgYSByZWFsIHN5c3RlbS4KKwor4oCUIGVu"
    "ZCBvZiBSRUFETUUg4oCUCmRpZmYgLS1naXQgYS9zcmMvb3JkZXJzL3JlcG8ucHkgYi9zcmMvb3JkZXJzL3JlcG8ucHkKbmV3IGZp"
    "bGUgbW9kZSAxMDA2NDQKLS0tIC9kZXYvbnVsbAorKysgYi9zcmMvb3JkZXJzL3JlcG8ucHkKQEAgLTAsMCArMSwyMyBAQAorIiIi"
    "T3JkZXIgcmVwb3NpdG9yeSAoc3ludGhldGljIGNhbmFyeSBwcm9qZWN0IOKAlCBub3RoaW5nIGhlcmUgaXMgcmVhbCkuIiIiCitp"
    "bXBvcnQgb3MKKworZnJvbSAuZGIgaW1wb3J0IHF1ZXJ5CisKKworZGVmIGdldF9vcmRlcihvcmRlcl9pZDogc3RyKSAtPiBkaWN0"
    "IHwgTm9uZToKKyAgICAjIHRlbmFudCBzY29waW5nOiBldmVyeSByZWFkIGlzIHNjb3BlZCB0byB0aGUgY2FsbGVyJ3MgdGVuYW50"
    "IChzZWUgZG9jcy9zcGVjL0NBTi0wMDEvZGVzaWduLm1kIMKnIDQpCisgICAgcm93cyA9IHF1ZXJ5KCJTRUxFQ1QgaWQsIHRlbmFu"
    "dF9pZCwgc3RhdHVzLCB0b3RhbF9jZW50cyBGUk9NIG9yZGVycyBXSEVSRSBpZCA9ID8iLCAob3JkZXJfaWQsKSkKKyAgICByZXR1"
    "cm4gcm93c1swXSBpZiByb3dzIGVsc2UgTm9uZQorCisKK2RlZiBsaXN0X29yZGVycyh0ZW5hbnRfaWQ6IHN0ciwgc3RhdHVzOiBz"
    "dHIgfCBOb25lID0gTm9uZSkgLT4gbGlzdFtkaWN0XToKKyAgICBzcWwgPSAiU0VMRUNUIGlkLCB0ZW5hbnRfaWQsIHN0YXR1cywg"
    "dG90YWxfY2VudHMgRlJPTSBvcmRlcnMgV0hFUkUgdGVuYW50X2lkID0gPyIKKyAgICBwYXJhbXM6IGxpc3QgPSBbdGVuYW50X2lk"
    "XQorICAgIGlmIHN0YXR1czoKKyAgICAgICAgc3FsICs9ICIgQU5EIHN0YXR1cyA9ID8iCisgICAgICAgIHBhcmFtcy5hcHBlbmQo"
    "c3RhdHVzKQorICAgIHJldHVybiBxdWVyeShzcWwsIHR1cGxlKHBhcmFtcykpCisKKworIyB0aGUga2V5IGJlbG93IGlzIHBsYW50"
    "ZWQgZm9yIHRoZSBsZW5zIGNhbmFyeSDigJQgbmV2ZXIgYSByZWFsIGNyZWRlbnRpYWwKK0JJTExJTkdfQVBJX0tFWSA9ICJzay1j"
    "YW5hcnkwMDAwMDAwMDAwMDAwMDAwMDAwMCIgICAjIGNhbmFyeS1zZWNyZXQKZGlmZiAtLWdpdCBhL3NyYy9vcmRlcnMvZHRvLnB5"
    "IGIvc3JjL29yZGVycy9kdG8ucHkKbmV3IGZpbGUgbW9kZSAxMDA2NDQKLS0tIC9kZXYvbnVsbAorKysgYi9zcmMvb3JkZXJzL2R0"
    "by5weQpAQCAtMCwwICsxLDEyIEBACisiIiJPcmRlciBEVE9zIOKAlCB0aGUgY29udHJhY3QgdGhlIEFQSSBwdWJsaXNoZXMgKGNv"
    "bnRyYWN0cy9vcmRlcnMub3BlbmFwaS55YW1sKS4iIiIKK2Zyb20gZGF0YWNsYXNzZXMgaW1wb3J0IGRhdGFjbGFzcworCisKK0Bk"
    "YXRhY2xhc3MoZnJvemVuPVRydWUpCitjbGFzcyBPcmRlck91dDoKKyAgICBpZDogc3RyCisgICAgc3RhdHVzOiBzdHIKKyAgICB0"
    "b3RhbF9jZW50czogaW50ICAgICAgICAgICMgdGhlIGNvbnRyYWN0OiBhbiBpbnRlZ2VyIG9mIGNlbnRzCisKKworU1RBVFVTRVMg"
    "PSAoIm5ldyIsICJwYWlkIiwgInNoaXBwZWQiKQpkaWZmIC0tZ2l0IGEvc3JjL29yZGVycy9hcGkucHkgYi9zcmMvb3JkZXJzL2Fw"
    "aS5weQpuZXcgZmlsZSBtb2RlIDEwMDY0NAotLS0gL2Rldi9udWxsCisrKyBiL3NyYy9vcmRlcnMvYXBpLnB5CkBAIC0wLDAgKzEs"
    "MjEgQEAKKyIiIk9yZGVyIGVuZHBvaW50cyAoc3ludGhldGljIGNhbmFyeSBwcm9qZWN0KS4iIiIKK2Zyb20gLmR0byBpbXBvcnQg"
    "T3JkZXJPdXQsIFNUQVRVU0VTCitmcm9tIC5yZXBvIGltcG9ydCBnZXRfb3JkZXIsIGxpc3Rfb3JkZXJzCisKKworZGVmIHJlYWRf"
    "b3JkZXIob3JkZXJfaWQ6IHN0ciwgdGVuYW50X2lkOiBzdHIpIC0+IGRpY3Q6CisgICAgcm93ID0gZ2V0X29yZGVyKG9yZGVyX2lk"
    "KQorICAgIGlmIHJvdyBpcyBOb25lOgorICAgICAgICByZXR1cm4geyJlcnJvciI6ICJub3QgZm91bmQifSwgNDA0CisgICAgcmV0"
    "dXJuIHsiaWQiOiByb3dbImlkIl0sICJzdGF0dXMiOiByb3dbInN0YXR1cyJdLCAidG90YWwiOiByb3dbInRvdGFsX2NlbnRzIl0g"
    "LyAxMDAuMH0KKworCitkZWYgcmVhZF9vcmRlcnModGVuYW50X2lkOiBzdHIsIHN0YXR1czogc3RyIHwgTm9uZSA9IE5vbmUpIC0+"
    "IGxpc3RbZGljdF06CisgICAgcmV0dXJuIFtPcmRlck91dChyWyJpZCJdLCByWyJzdGF0dXMiXSwgclsidG90YWxfY2VudHMiXSku"
    "X19kaWN0X18gZm9yIHIgaW4gbGlzdF9vcmRlcnModGVuYW50X2lkLCBzdGF0dXMpXQorCisKK2RlZiBzZXRfc3RhdHVzKG9yZGVy"
    "X2lkOiBzdHIsIHRlbmFudF9pZDogc3RyLCBzdGF0dXM6IHN0cikgLT4gZGljdDoKKyAgICBpZiBzdGF0dXMgbm90IGluIFNUQVRV"
    "U0VTOgorICAgICAgICByZXR1cm4geyJlcnJvciI6ICJ1bmtub3duIHN0YXR1cyJ9LCA0MDAKKyAgICAjIGNhbmNlbCBpcyBub3Qg"
    "YSBzdGF0dXMgdGhpcyBzZXJ2aWNlIGtub3dzOiBzZWUgdGhlIG1vY2ssIHN0ZXAgMworICAgIHJldHVybiB7ImlkIjogb3JkZXJf"
    "aWQsICJzdGF0dXMiOiBzdGF0dXN9CmRpZmYgLS1naXQgYS90ZXN0cy90ZXN0X29yZGVycy5weSBiL3Rlc3RzL3Rlc3Rfb3JkZXJz"
    "LnB5Cm5ldyBmaWxlIG1vZGUgMTAwNjQ0Ci0tLSAvZGV2L251bGwKKysrIGIvdGVzdHMvdGVzdF9vcmRlcnMucHkKQEAgLTAsMCAr"
    "MSwyMCBAQAoraW1wb3J0IHB5dGVzdAorCitmcm9tIHNyYy5vcmRlcnMuYXBpIGltcG9ydCByZWFkX29yZGVyLCByZWFkX29yZGVy"
    "cywgc2V0X3N0YXR1cworCisKK0BweXRlc3QubWFyay5jYXNlKCJDQU4tMDAxL1RDLTAxIikKK2RlZiB0ZXN0X3JlYWRfb3JkZXJf"
    "cmV0dXJuc190aGVfdG90YWxfaW5fY2VudHMobW9ua2V5cGF0Y2gpOgorICAgIG1vbmtleXBhdGNoLnNldGF0dHIoInNyYy5vcmRl"
    "cnMuYXBpLmdldF9vcmRlciIsIGxhbWJkYSBvaWQ6IHsiaWQiOiBvaWQsICJzdGF0dXMiOiAicGFpZCIsICJ0b3RhbF9jZW50cyI6"
    "IDEyNTB9KQorICAgIG91dCA9IHJlYWRfb3JkZXIoIm8tMSIsICJ0LTEiKQorICAgIGFzc2VydCBvdXQgICMgdGhlIHJlc3BvbnNl"
    "IGlzIHRydXRoeSDigJQgc2VlIFRDLTAxIGV4cGVjdGVkOiB0b3RhbF9jZW50cyA9PSAxMjUwCisKKworQHB5dGVzdC5tYXJrLmNh"
    "c2UoIkNBTi0wMDEvVEMtMDIiKQorZGVmIHRlc3RfbGlzdF9vcmRlcnNfaXNfc2NvcGVkX3RvX3RoZV90ZW5hbnQobW9ua2V5cGF0"
    "Y2gpOgorICAgIG1vbmtleXBhdGNoLnNldGF0dHIoInNyYy5vcmRlcnMuYXBpLmxpc3Rfb3JkZXJzIiwgbGFtYmRhIHQsIHM9Tm9u"
    "ZTogW3siaWQiOiAiby0xIiwgInN0YXR1cyI6ICJuZXciLCAidG90YWxfY2VudHMiOiA1fV0pCisgICAgYXNzZXJ0IHJlYWRfb3Jk"
    "ZXJzKCJ0LTEiKSA9PSBbeyJpZCI6ICJvLTEiLCAic3RhdHVzIjogIm5ldyIsICJ0b3RhbF9jZW50cyI6IDV9XQorCisKK2RlZiB0"
    "ZXN0X3NldF9zdGF0dXNfcmVqZWN0c191bmtub3duKCk6CisgICAgYXNzZXJ0IHNldF9zdGF0dXMoIm8tMSIsICJ0LTEiLCAidGVs"
    "ZXBvcnRlZCIpWzFdID09IDQwMApkaWZmIC0tZ2l0IGEvZG9jcy9zcGVjL0NBTi0wMDEvc3BlYy5mZWF0dXJlIGIvZG9jcy9zcGVj"
    "L0NBTi0wMDEvc3BlYy5mZWF0dXJlCm5ldyBmaWxlIG1vZGUgMTAwNjQ0Ci0tLSAvZGV2L251bGwKKysrIGIvZG9jcy9zcGVjL0NB"
    "Ti0wMDEvc3BlYy5mZWF0dXJlCkBAIC0wLDAgKzEsMTkgQEAKK0ZlYXR1cmU6IE9yZGVycyAoc3ludGhldGljIGNhbmFyeSBmZWF0"
    "dXJlIENBTi0wMDEpCisKKyAgU2NlbmFyaW86IFJlYWQgYW4gb3JkZXIgd2l0aCBpdHMgdG90YWwgICAgICAgICAgIyBUQy0wMQor"
    "ICAgIEdpdmVuIGFuIG9yZGVyICJvLTEiIG9mIDEyLjUwIGZvciB0ZW5hbnQgInQtMSIKKyAgICBXaGVuIHRoZSBBUEkgcmVhZHMg"
    "Im8tMSIKKyAgICBUaGVuIHRoZSByZXNwb25zZSBjYXJyaWVzIHRvdGFsX2NlbnRzIDEyNTAKKworICBTY2VuYXJpbzogTGlzdCB0"
    "aGUgdGVuYW50J3Mgb3JkZXJzIG9ubHkgICAgICAgICAjIFRDLTAyCisgICAgR2l2ZW4gb3JkZXJzIGZvciB0ZW5hbnRzICJ0LTEi"
    "IGFuZCAidC0yIgorICAgIFdoZW4gdGhlIEFQSSBsaXN0cyBvcmRlcnMgZm9yICJ0LTEiCisgICAgVGhlbiBvbmx5ICJ0LTEiIG9y"
    "ZGVycyBhcmUgcmV0dXJuZWQKKworICBTY2VuYXJpbzogQ2FuY2VsIGFuIG9yZGVyICAgICAgICAgICAgICAgICAgICAgICAgIyBU"
    "Qy0wMworICAgIEdpdmVuIGEgcGFpZCBvcmRlciAiby0xIiBmb3IgdGVuYW50ICJ0LTEiCisgICAgV2hlbiB0aGUgY3VzdG9tZXIg"
    "Y2FuY2VscyAiby0xIgorICAgIFRoZW4gdGhlIG9yZGVyIHN0YXR1cyBpcyAiY2FuY2VsbGVkIgorICAgIEFuZCB0aGUgY3VzdG9t"
    "ZXIgc2VlcyB0aGUgY2FuY2VsbGVkIHN0YXRlIChtb2NrIHN0ZXAgMykKKworICAjIFRDLTAzIGlzIHNwZWNpZmllZCBieSB0aGUg"
    "YnVzaW5lc3Mgb3duZXI7IHRoZSBtb2NrIHNob3dzIHRoZSBjYW5jZWxsZWQgc3RhdGUgYXQgI3N0ZXAtMwpkaWZmIC0tZ2l0IGEv"
    "ZG9jcy9zcGVjL0NBTi0wMDEvbW9jay5odG1sIGIvZG9jcy9zcGVjL0NBTi0wMDEvbW9jay5odG1sCm5ldyBmaWxlIG1vZGUgMTAw"
    "NjQ0Ci0tLSAvZGV2L251bGwKKysrIGIvZG9jcy9zcGVjL0NBTi0wMDEvbW9jay5odG1sCkBAIC0wLDAgKzEsOSBAQAorPCFkb2N0"
    "eXBlIGh0bWw+Cis8bWFpbj4KKyAgPHNlY3Rpb24gaWQ9InN0ZXAtMSI+PGgyPllvdXIgb3JkZXI8L2gyPjxwPlRvdGFsOiA8Yj4x"
    "Mi41MDwvYj48L3A+PC9zZWN0aW9uPgorICA8c2VjdGlvbiBpZD0ic3RlcC0yIj48aDI+WW91ciBvcmRlcnM8L2gyPjx1bD48bGk+"
    "by0xIMK3IHBhaWQ8L2xpPjwvdWw+PC9zZWN0aW9uPgorICA8c2VjdGlvbiBpZD0ic3RlcC0zIiBkYXRhLXN0YXRlPSJjYW5jZWxs"
    "ZWQiPgorICAgIDxoMj5PcmRlciBjYW5jZWxsZWQ8L2gyPgorICAgIDxwPllvdXIgb3JkZXIgby0xIHdhcyBjYW5jZWxsZWQuIEEg"
    "cmVmdW5kIG9mIDEyLjUwIGlzIG9uIGl0cyB3YXkuPC9wPgorICA8L3NlY3Rpb24+Cis8L21haW4+CmRpZmYgLS1naXQgYS8uY2xh"
    "dWRlL3NraWxscy9vcmRlcnMtaGVscGVyL1NLSUxMLm1kIGIvLmNsYXVkZS9za2lsbHMvb3JkZXJzLWhlbHBlci9TS0lMTC5tZApu"
    "ZXcgZmlsZSBtb2RlIDEwMDY0NAotLS0gL2Rldi9udWxsCisrKyBiLy5jbGF1ZGUvc2tpbGxzL29yZGVycy1oZWxwZXIvU0tJTEwu"
    "bWQKQEAgLTAsMCArMSw4IEBACistLS0KK25hbWU6IG9yZGVycy1oZWxwZXIKK2Rlc2NyaXB0aW9uOiAiSGVscGVyIHNraWxsIGZv"
    "ciB0aGUgb3JkZXJzIHN1cmZhY2UgKHN5bnRoZXRpYyBjYW5hcnkgcHJvamVjdCkuIgorLS0tCisKKyMgb3JkZXJzLWhlbHBlcgor"
    "CitVc2Ugd2hlbiB0b3VjaGluZyBzcmMvb3JkZXJzLyoqLiBSZWFkcyB0aGUgRFRPIGNvbnRyYWN0IGZpcnN0LgpkaWZmIC0tZ2l0"
    "IGEvZG9jcy9wcm9qZWN0X2xvZy9nb3Zlcm5hbmNlX3ZlcnNpb25zLmpzb24gYi9kb2NzL3Byb2plY3RfbG9nL2dvdmVybmFuY2Vf"
    "dmVyc2lvbnMuanNvbgotLS0gYS9kb2NzL3Byb2plY3RfbG9nL2dvdmVybmFuY2VfdmVyc2lvbnMuanNvbgorKysgYi9kb2NzL3By"
    "b2plY3RfbG9nL2dvdmVybmFuY2VfdmVyc2lvbnMuanNvbgpAQCAtMSw4ICsxLDkgQEAKIHsKICAgImZyYW1ld29ya192ZXJzaW9u"
    "IjogIjguNi4wIiwKICAgInRlbXBsYXRlcyI6IHsKICAgICAicnVsZXMvdGVzdGluZy5tZCI6IHsKICAgICAgICJ2ZXJzaW9uIjog"
    "IjEuMi4wIiwKICAgICAgICJjaGFuZ2Vsb2ciOiBbCisgICAgICAgICIxLjIuMDogZmVhdChDQU4tMDAxKSDigJQgdGhlIG9yZGVy"
    "cyBydWxlOiBldmVyeSByZWFkIHNjb3BlZCB0byB0aGUgdGVuYW50IiwKICAgICAgICAgIjEuMi4wOiBmZWF0KEVWT0wtMDQwKSDi"
    "gJQgaW5pdGlhbCIKICAgICAgIF0K"
)

EXPECTED: dict[str, list[dict]] = {
    "security": [
        {"id": "s1", "what": "a read without the tenant predicate (an order of another tenant is readable by id)",
         "at": [["src/orders/repo.py", 9], ["src/orders/api.py", 7]]},
        {"id": "s2", "what": "a credential in code (the planted line carries the canary-secret marker)",
         "at": [["src/orders/repo.py", 23]]},
    ],
    "correctness": [
        {"id": "c1", "what": "a dishonest test — the assertion never reaches the expected result it names",
         "at": [["tests/test_orders.py", 10]]},
        {"id": "c2", "what": "the contract publishes total_cents (an integer), the handler returns total (a float)",
         "at": [["src/orders/api.py", 10], ["src/orders/dto.py", 9]]},
    ],
    "governance": [
        {"id": "g1", "what": "an artefact added without its manifest entry",
         "at": [[".claude/skills/orders-helper/SKILL.md", 4]]},
        {"id": "g2", "what": "a manifest changelog line added without its version bump",
         "at": [["docs/project_log/governance_versions.json", 7]]},
    ],
    "fidelity": [
        {"id": "f1", "what": "a specified scenario (TC-03, cancel an order) with no test",
         "at": [["docs/spec/CAN-001/spec.feature", 13], ["tests/test_orders.py", 19], ["src/orders/api.py", 20]]},   # a critic may fold the untested scenario and the unimplemented state into one finding at the stub
        {"id": "f2", "what": "a mock state (#step-3, cancelled) that no code implements",
         "at": [["docs/spec/CAN-001/mock.html", 5], ["src/orders/api.py", 20], ["src/orders/dto.py", 12]]},
    ],
}


def fixture() -> str:
    return base64.b64decode(FIXTURE_B64).decode("utf-8")


def added_lines(diff: str, positions: dict[str, dict[int, int]] | None = None) -> dict[str, dict[int, str]]:
    """path → {line in the NEW file: text} for every `+` line, from the hunk headers. `positions`, when given, is
    filled with path → {line of the DIFF TEXT: line in the new file} — a critic handed the raw diff may count
    the diff's own lines; the judge accepts both coordinates."""
    out: dict[str, dict[int, str]] = {}
    path, new_no = None, 0
    for i, raw in enumerate(diff.splitlines(), 1):
        if raw.startswith("+++ "):
            path = raw[4:].strip()
            path = path[2:] if path.startswith("b/") else path
            out.setdefault(path, {})
            if positions is not None:
                positions.setdefault(path, {})
            continue
        m = re.match(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@", raw)
        if m:
            new_no = int(m.group(1))
            continue
        if path is None or raw.startswith("---") or raw.startswith("diff "):
            continue
        if raw.startswith("+"):
            out[path][new_no] = raw[1:]
            if positions is not None:
                positions[path][i] = new_no
            new_no += 1
        elif raw.startswith("-"):
            continue
        elif raw.startswith(" ") or raw == "":
            new_no += 1
    return out


def consistency(repo: Path | None = None) -> list[str]:
    """The fixture holds its own promises: every anchor is an added line, the planted credential carries its marker and
    is invisible at rest, the two coordinate spaces never overlap and the tolerance reaches no two planted defects of
    one lens at once (both against the project's tolerance when a repo is at hand), and — with a repo — every lens's
    agent is in the roster. The judge refuses a fixture that breaks a promise: a false green is never a verdict."""
    problems: list[str] = []
    try:
        diff = fixture()
    except Exception as e:   # noqa: BLE001 — a fixture that does not decode is the finding
        return [f"the fixture does not decode: {e}"]
    added = added_lines(diff)
    for lens, items in EXPECTED.items():
        for it in items:
            for f, n in it["at"]:
                if n not in added.get(f, {}):
                    problems.append(f"{lens}/{it['id']}: anchor {f}:{n} is not an added line of the fixture")
    secret = [n for n, t in added.get("src/orders/repo.py", {}).items() if "canary-secret" in t and "BILLING" in t]
    if not secret:
        problems.append("the planted credential's own line does not carry the `canary-secret` marker")
    at_rest = Path(__file__).read_text(encoding="utf-8", errors="replace")
    planted = next((t for t in added.get("src/orders/repo.py", {}).values() if "canary-secret" in t), "")
    value = planted.split('"')[1] if planted.count('"') >= 2 else ""
    if not value or value in at_rest:   # the credential's value itself, never spelled in this file
        problems.append("the planted credential is visible at rest (or absent) — the fixture must stay encoded in this file")
    # the two coordinate spaces never overlap: a critic may number the diff text or the new file; the filler that leads
    # the diff keeps every anchored file's diff-text lines far above every anchor, so neither reading lands on another anchor
    positions: dict[str, dict[int, int]] = {}
    added_lines(diff, positions)
    anchored = {f for items in EXPECTED.values() for it in items for f, _ in it["at"]}
    lowest_diff_line = min((d for f in anchored for d in positions.get(f, {})), default=0)
    highest_anchor = max(n for items in EXPECTED.values() for it in items for _, n in it["at"])
    highest_new_line = max((n for f in anchored for n in added.get(f, {})), default=0)   # a new-file reading that equals a diff-text line would be remapped: the bound is the longest anchored file, not the highest anchor
    bound = max(highest_anchor, highest_new_line)
    tol = DEFAULT_TOLERANCE
    if repo is not None:
        try:
            tol = tolerance(repo)
        except GateFault as e:
            problems.append(_home(str(e)))
    if lowest_diff_line <= bound + tol:
        problems.append(f"the diff text's lines of the anchored files start at {lowest_diff_line}, within reach of the new file's numbering (to {bound}, tolerance to {bound + tol}) — lead the diff with a longer filler or lower agents.canary.line_tolerance")
    # the tolerance reaches no two planted defects of one lens at once: one finding between two anchors of the same file
    # would credit both (a shared anchor — the same coordinate under two items — is on purpose and not a pair)
    for lens, items in EXPECTED.items():
        for i, a in enumerate(items):
            for b in items[i + 1:]:
                for f, n in a["at"]:
                    for f2, n2 in b["at"]:
                        if f == f2 and n != n2 and 2 * tol >= abs(n - n2):
                            problems.append(f"rules/agents.md: agents.canary.line_tolerance {tol} reaches two planted defects of the {lens} lens at once ({f}: {n} and {n2} are {abs(n - n2)} apart) — keep it under {abs(n - n2) / 2:g}")
    if repo is not None:
        from . import agents as agents_mod
        try:
            names = {r.get("name") for r in agents_mod.policy(repo)["roster"] if isinstance(r, dict)}   # the reader holds the roster to a list
            for lens, agent in LENS_AGENT.items():
                if agent not in names:
                    problems.append(f"rules/agents.md: lens {lens}: its agent {agent} is not in the roster")
        except GateFault as e:
            problems.append(_home(str(e)))
    return list(dict.fromkeys(problems))   # a problem said once (a policy that cannot be read fails the tolerance and the roster alike)


def _home(fault: str) -> str:
    """A policy fault filed where it comes from: the config file it names, the rule otherwise."""
    m = re.search(r"config/[\w.-]+\.json", fault)
    return (m.group(0) + ": " if m else "rules/agents.md: ") + fault


def tolerance(repo: Path) -> int:
    from . import agents as agents_mod   # the one policy home
    pol = agents_mod.policy(repo)
    c = pol.get("canary") if isinstance(pol.get("canary"), dict) else None
    v = c.get("line_tolerance") if c else None
    if isinstance(v, bool) or not isinstance(v, int) or v < 0:
        raise GateFault("agents.canary.line_tolerance must be a non-negative integer in rules/agents.md — the canary's match window is a key (EVOL-059)")
    return v


def findings(text: str) -> list[tuple[str, int, str]]:
    """The contract's own finding shape (agents.FINDING) — one definition; a line outside it is not a finding here either."""
    from . import agents as agents_mod
    out = []
    for line in text.splitlines():
        m = agents_mod.FINDING.match(line)
        if m:
            f, n = m.group("loc").rsplit(":", 1)
            f = f[2:] if f.startswith(("./", "a/", "b/")) else f
            out.append((f, int(n), m.group("sev")))
    return out


def _record_path(repo: Path) -> Path:
    return repo / STATE_DIR / RECORD


def read_record(repo: Path) -> dict:
    p = _record_path(repo)
    if not p.is_file():
        return {"judged": {}, "seen": {}}
    try:
        d = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        raise GateFault(f"the canary record {p.relative_to(repo)} is unreadable ({e}) — delete it and judge the lenses again") from None
    shaped = (isinstance(d, dict) and isinstance(d.get("judged", {}), dict) and isinstance(d.get("seen", {}), dict)
              and all(isinstance(v, dict) for v in d.get("judged", {}).values()) and all(isinstance(v, dict) for v in d.get("seen", {}).values()))
    if not shaped:
        raise GateFault(f"the canary record {p.relative_to(repo)} is not the record's shape (judged, seen: a mapping per lens) — delete it and judge the lenses again")
    d.setdefault("judged", {}); d.setdefault("seen", {})
    return d


def _write_record(repo: Path, d: dict) -> None:
    p = _record_path(repo)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(".tmp")
    tmp.write_text(json.dumps(d, indent=0, sort_keys=True), encoding="utf-8")
    tmp.replace(p)


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _lens(lens: str) -> str:
    if lens not in EXPECTED:
        raise GateFault(f"lens `{lens}` is not one of {', '.join(LENSES)}")
    return lens


def judge(repo: Path, lens: str, text: str, model: str) -> dict:
    """Compare a critic's return over the fixture to the lens's planted defects; record; red when any was missed."""
    lens = _lens(lens)
    model = (model or "").strip()
    if not model:
        raise GateFault("--judge needs --model: the id the critic's return carries on its `Model:` line (the harness states it; `unknown` when it does not)")
    tol = tolerance(repo)
    broken = consistency(repo)
    if broken:
        raise GateFault("the fixture is inconsistent under this project's policy — a verdict here could be a false green; `gate.py canary --check` names it: " + broken[0])
    positions: dict[str, dict[int, int]] = {}
    added_lines(fixture(), positions)
    from . import agents as agents_mod
    all_findings = findings(text)
    if not all_findings and not agents_mod.NO_FINDINGS.search(text or ""):   # the contract's one regex (agents --check-return reads the same)
        raise GateFault("the return carries no finding in the contract shape and no `no findings` line — hold it to the contract (gate.py agents --check-return) before judging; a formatting fault is not model drift")
    def _key(f: str) -> str:   # the fixture's own path for the one the critic wrote: exact, or by its tail (an absolute or prefixed path still names the file)
        return f if f in positions else next((p for p in positions if f.endswith("/" + p)), f)   # exact first, then the tail
    got = [(_key(f), {n, positions.get(_key(f), {}).get(n, n)}) for f, n, sev in all_findings if sev in SEVERITY_ABOVE_INFO]   # one finding, both readings: the new file's line, or the diff text's mapped to it
    found, missed = [], []
    for it in EXPECTED[lens]:
        hit = any(f == af and any(abs(x - an) <= tol for x in ns) for f, ns in got for af, an in it["at"])
        (found if hit else missed).append(it["id"])
    d = read_record(repo)
    d["judged"][lens] = {"model": model, "at": _now(), "found": found, "missed": missed}
    _write_record(repo, d)
    return {"ok": not missed, "lens": lens, "model": model, "found": found, "missed": missed, "tolerance": tol,
            "findings": len(got), "reason": ("every planted defect found" if not missed else
                                             "missed: " + ", ".join(f"{m} ({next(i['what'] for i in EXPECTED[lens] if i['id'] == m)})" for m in missed))}


def seen(repo: Path, lens: str, model: str) -> dict:
    lens = _lens(lens)
    model = (model or "").strip() or "unknown"
    d = read_record(repo)
    d["seen"][lens] = {"model": model, "at": _now()}
    _write_record(repo, d)
    return {"ok": True, "lens": lens, "model": model}


def plan(repo: Path, all_: bool = False) -> dict:
    """The lenses owed a canary. One definition: on a fixture the judge would refuse, nothing is owed and the fault is
    named (`fault`) — the spawn reader and both spawn sites read this, never a second reading."""
    d = read_record(repo)
    broken = consistency(repo)
    owed, lenses = [], {}
    for lens in LENSES:
        j, s = d["judged"].get(lens) or {}, d["seen"].get(lens) or {}
        judged, current = j.get("model"), s.get("model")
        if all_:
            why = "on demand"
        elif not judged:
            why = "never judged"
        elif current and current != judged:
            why = f"the model moved: judged on `{judged}`, last ran on `{current}`"
        elif current == "unknown" or judged == "unknown":
            why = "the model is unknown (the return carried no id) — judged until it is known"
        else:
            why = ""
        lenses[lens] = {"agent": LENS_AGENT[lens], "judged_on": judged, "last_ran_on": current, "missed": j.get("missed"), "reason": why or "judged on the model it last ran on"}
        if why and not broken:
            owed.append(lens)
    out = {"owed": owed, "lenses": lenses, "fixture_ok": not broken}
    if broken:
        out["fault"] = "the fixture is inconsistent under this project's policy — no lens is owed until the fault is cured; gate.py canary --check names it: " + broken[0]
    return out


def render_plan(r: dict) -> str:
    head = ("FAULT — nothing owed until the fault below is cured" if r.get("fault") else
            "owed — " + ", ".join(r["owed"]) if r["owed"] else "nothing owed — every lens judged on the model it last ran on")
    lines = [f"canary: {head}"]
    for lens, v in r["lenses"].items():
        lines.append(f"  {'→' if lens in r['owed'] else '·'} {lens} ({v['agent']}): judged on {v['judged_on'] or '—'} · last ran on {v['last_ran_on'] or '—'}"
                     + (f" · missed {', '.join(v['missed'])}" if v.get("missed") else "") + f" — {v['reason']}")
    if r.get("fault"):
        lines.append("  ✗ " + r["fault"])
    if r["owed"]:
        lines.append("  run: for each owed lens — gate.py agents --resolve --class work-critic, the fixture (gate.py canary --fixture) as the diff, the return "
                     "check, then gate.py canary --judge --lens <lens> --model <the return's Model: line>; post the verdict on the tracking item; a red canary opens the spawn policy's review by RDR")
    return "\n".join(lines)


def render_judge(r: dict) -> str:
    return (f"canary: {'ok' if r['ok'] else 'RED'} — {r['lens']} on {r['model']}: found {', '.join(r['found']) or 'none'}; "
            f"{r['reason']} ({r['findings']} finding(s) above informational read, ±{r['tolerance']} lines)"
            + ("" if r["ok"] else "\n  a red canary never blocks the train: it opens the review of the spawn policy (rules/agents.md → families, ladder, resolve rows) by RDR with the user"))
