# Generated by Phase: IMPLEMENT | Feature: EVOL-043
"""Retired-vocabulary ratchet: a term a decision record retires stops being writable across the governed tree.

Config (`config/quality.json` → `retired_terms`): [{"term": "…", "record": "ADR-…", "exempt": [globs]}].
Exemption classes, always on (history is not rewritten): docs/project_log/**, the governance manifest,
config/quality.json itself, worklogs. Scan set = coherence-context.json audit.root_sets minus audit.exclusions.
"""
from __future__ import annotations

from pathlib import Path

from .common import any_glob, fnmatch_any, key, load_coherence, tracked_files

HISTORY_EXEMPT = ("docs/project_log/**", "**/governance_versions.json", "config/quality.json", "**/*.log.jsonl",
                  ".claude/state/**", "**/CHANGELOG*")


def scan(repo: Path) -> list[dict]:
    terms = key(repo, "retired_terms", default=[]) or []
    if not terms:
        return []
    cc = load_coherence(repo).get("audit", {})
    roots = cc.get("root_sets") or ["."]
    exclusions = cc.get("exclusions") or []
    hits: list[dict] = []
    for rel in tracked_files(repo):
        if not any(rel == r.rstrip("/") or rel.startswith(r.rstrip("/") + "/") or r == "." for r in roots):
            continue
        if any(rel.startswith(x) or fnmatch_any(Path(rel).name, [x]) for x in exclusions):
            continue
        if any_glob(rel, HISTORY_EXEMPT):
            continue
        try:
            text = (repo / rel).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for t in terms:
            term = t.get("term", "")
            if not term or any_glob(rel, t.get("exempt") or []):
                continue
            for n, line in enumerate(text.splitlines(), 1):
                if term in line:
                    hits.append({"path": rel, "line": n, "term": term, "record": t.get("record", "?")})
    return hits


def render(hits: list[dict]) -> str:
    if not hits:
        return "retired-terms: ok — no retired term written in the governed tree."
    out = [f"retired-terms: FAIL — {len(hits)} occurrence(s) of retired vocabulary:"]
    out += [f"  {h['path']}:{h['line']}: `{h['term']}` (retired by {h['record']})" for h in hits[:50]]
    if len(hits) > 50:
        out.append(f"  … {len(hits) - 50} more")
    out.append("A retired term is history, not law: rewrite the sentence, or declare an exemption glob on the term in config/quality.json.")
    return "\n".join(out)
