# Generated by Phase: IMPLEMENT | Feature: EVOL-051
"""One full verification loop per change (EVOL-051): the documentation class, the path-to-gate map, the seal.

documentation  `config/quality.json → documentation` — the ONE definition of a documentation path (root-anchored
               globs `paths`, minus `exclusions`, which are code whatever their extension). Read by the push-gate
               preflight (its review-lane skip), the planning gate (its exemption) and the seal (its classification).
gates          `verification.gates.<name>` — what each full-loop gate READS (`reads`, root-anchored globs like the
               documentation class) and the command that runs it (`command`, may be shared: a suite executed once
               feeds every gate that declares that command).
seal           an untracked state file per branch (`verification.seal.dir`, default `.claude/state/`): per gate the
               hash of its read-set — mode + git blob id of every file ON DISK, computed as git commits it (clean
               filters applied, a symlink by its target text), tracked and untracked, i.e. the tree the next commit
               carries — and its outcome; a full loop also records the whole tree. `plan` names the gates owed now
               (every gate whose read-set moved since its green — or since the merge-base with the diff base when it
               was never recorded; every gate when a changed path no gate reads and no documentation class covers —
               an unmapped path owes the full loop, fail closed); `write` records a gate's run (`--full` seals the
               tree and refuses when any recorded read-set moved after its run); `check` (a profile member)
               recomputes every read-set at HEAD and refuses a push whose seal does not cover the tree the commit
               carries. The seal is a LOCAL CLAIM written by the loop that ran — like the LAW-13 review marker: the
               push honours it, nothing re-runs the gates to verify it; at CI it is not on the runner (n/a with the
               reason). A repo whose config says the seal is not required (the framework repo: CI's T2 suite is its
               loop) reports n/a with the reason; the key absent = required; the config absent = RED, never a fault.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from .common import GateFault, _glob_regex, key

DEFAULT_SEAL_DIR = ".claude/state"
CI_REASON = ("the seal is local state honoured at the push (pre-push, gate.py profile --run) and is not on this runner; "
             "CI does not run the loop — a push that bypasses the hook bypasses the loop; the project's own CI test job, "
             "when it has one, is the compensating control")


# ─── documentation: one definition ──────────────────────────────────────────────

def documentation_cfg(repo: Path) -> dict:
    d = key(repo, "documentation", default=None)
    if not isinstance(d, dict):
        raise GateFault("config key `documentation` is missing from config/quality.json — the one definition of a documentation path (paths, exclusions) lives there (SETUP materialises it; SETUP --upgrade moves planning.docs_exempt into it)")
    out = {}
    for k in ("paths", "exclusions"):
        v = d.get(k, [])
        if not isinstance(v, list) or not all(isinstance(x, str) for x in v):
            raise GateFault(f"documentation.{k} must be a list of globs")
        out[k] = v
    if not out["paths"]:
        raise GateFault("documentation.paths is empty — a class that matches nothing makes every change code")
    return out


def _norm_path(rel: str) -> str:
    rel = str(rel).replace("\\", "/")
    while rel.startswith("./"):
        rel = rel[2:]
    return rel


def _root_match(rel: str, globs: list[str]) -> bool:
    """Root-anchored: `docs/**` never covers `src/docs/x.py`; `**/*.md` covers every depth."""
    return any(re.fullmatch(_glob_regex(g), rel) for g in globs)


def is_documentation(rel: str, cfg: dict) -> tuple[bool, str]:
    rel = _norm_path(rel)
    if _root_match(rel, cfg["exclusions"]):
        return False, "a documentation.exclusions path — code whatever its extension"
    if _root_match(rel, cfg["paths"]):
        return True, "a documentation path"
    return False, "not a documentation path"


def _git(repo: Path, *args, input_: str | None = None) -> str:
    try:
        r = subprocess.run(["git", "-C", str(repo), "-c", "core.quotepath=false", *args], capture_output=True, text=True, timeout=120, input=input_)
    except (OSError, subprocess.TimeoutExpired) as e:
        raise GateFault(f"git {' '.join(args)} could not run: {e}") from None
    if r.returncode != 0:
        raise GateFault(f"git {' '.join(args)} failed: {(r.stderr.strip().splitlines() or ['(no message)'])[-1]}")
    return r.stdout


def diff_paths(repo: Path, base: str) -> list[str]:
    """The paths of base...HEAD (no rename pairing: a rename is a removal and an addition)."""
    return [p for p in _git(repo, "diff", "--name-only", "--no-renames", f"{base}...HEAD").splitlines() if p]


def docs_only(repo: Path, base: str) -> dict:
    """Every path of base...HEAD is documentation? {ok, code: [offending paths], changed: n}."""
    cfg = documentation_cfg(repo)
    paths = diff_paths(repo, base)
    code = [p for p in paths if not is_documentation(p, cfg)[0]]
    return {"ok": not code and bool(paths), "changed": len(paths), "code": code,
            "reason": "no change" if not paths else ("every changed path is documentation" if not code else f"{len(code)} path(s) are code: {', '.join(code[:5])}")}


# ─── the map and the seal ───────────────────────────────────────────────────────

def vcfg(repo: Path) -> dict:
    v = key(repo, "verification", default=None)
    if not isinstance(v, dict):
        raise GateFault("config key `verification` is missing from config/quality.json — the path-to-gate map, the seal and the digest artefacts live there (SETUP materialises it; SETUP --upgrade adds it)")
    seal = v.get("seal") if isinstance(v.get("seal"), dict) else {}
    required = seal.get("required", True)
    if not isinstance(required, bool):
        raise GateFault("verification.seal.required must be true or false")
    d = _norm_path(str(seal.get("dir") or DEFAULT_SEAL_DIR)).rstrip("/")
    if not d or d.startswith("/") or ".." in d.split("/"):
        raise GateFault(f"verification.seal.dir `{seal.get('dir')}` must be a folder inside the repository (a relative path without `..`)")
    gates = v.get("gates")
    if not isinstance(gates, dict):
        raise GateFault("verification.gates must be a mapping gate → {reads: [globs], command: str|null}")
    out_gates: dict[str, dict] = {}
    for name, g in gates.items():
        if not isinstance(g, dict) or not isinstance(g.get("reads"), list) or not g["reads"] or not all(isinstance(x, str) for x in g["reads"]):
            raise GateFault(f"verification.gates.{name} must declare a non-empty `reads` list of globs — a gate that declares nothing can never be owed, which is the defect")
        cmd = g.get("command")
        if cmd is not None and not isinstance(cmd, str):
            raise GateFault(f"verification.gates.{name}.command must be a string or null")
        out_gates[str(name)] = {"reads": g["reads"], "command": cmd or None}
    arts = v.get("digest_artefacts", ["design.md"])
    if not isinstance(arts, list) or not all(isinstance(x, str) for x in arts):
        raise GateFault("verification.digest_artefacts must be a list of file names under docs/spec/{ID}/")
    return {"required": required, "reason": str(seal.get("reason") or ""), "dir": d, "gates": out_gates, "digest_artefacts": arts}


def blob_id(data: bytes) -> str:
    """The git blob id of `data` as stored — used for symlinks (their target text); regular files go through
    `git hash-object` so the clean filters apply, exactly as the commit will carry them."""
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


def _mode(fp: Path) -> str:
    if fp.is_symlink():
        return "120000"
    return "100755" if os.access(fp, os.X_OK) else "100644"


def tree_entries(repo: Path, ref: str | None = None, skip: str = DEFAULT_SEAL_DIR) -> dict[str, str]:
    """path → `mode:blob`. ref None: the files ON DISK (tracked + untracked, not ignored) hashed as git commits them —
    the tree the next commit carries; a ref: `git ls-tree -r` of that commit. The seal's own folder is never part
    of the tree it seals."""
    skip = skip.rstrip("/") + "/"
    if ref:
        out = {}
        for line in _git(repo, "ls-tree", "-r", ref).splitlines():
            meta, _, path = line.partition("\t")
            parts = meta.split()
            if len(parts) >= 3 and parts[1] == "blob" and not path.startswith(skip):
                out[path] = f"{parts[0]}:{parts[2]}"
        return out
    names = set(_git(repo, "ls-files").splitlines()) | set(_git(repo, "ls-files", "--others", "--exclude-standard").splitlines())
    regular, out = [], {}
    for path in sorted(n for n in names if n and not n.startswith(skip)):
        fp = repo / path
        if fp.is_symlink():
            out[path] = f"120000:{blob_id(os.readlink(fp).encode())}"
        elif fp.is_file():
            regular.append(path)
    if regular:
        ids = _git(repo, "hash-object", "--stdin-paths", input_="\n".join(regular) + "\n").split()
        if len(ids) != len(regular):
            raise GateFault("git hash-object returned a different number of ids than paths — the tree on disk cannot be hashed")
        for path, h in zip(regular, ids):
            out[path] = f"{_mode(repo / path)}:{h}"
    return out


def _in_readset(path: str, reads: list[str]) -> bool:
    return _root_match(_norm_path(path), reads)


def readset_hash(entries: dict[str, str], globs: list[str]) -> str:
    rows = sorted(f"{p}\0{b}" for p, b in entries.items() if _in_readset(p, globs))
    return hashlib.sha256("\n".join(rows).encode()).hexdigest()


def _slug(branch: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "-", branch).strip("-") or "detached"


def current_branch(repo: Path) -> str:
    return _git(repo, "branch", "--show-current").strip()


def seal_path(repo: Path, branch: str, cfg: dict | None = None) -> Path:
    cfg = cfg or vcfg(repo)
    return repo / cfg["dir"] / f"seal-{_slug(branch)}.json"


def read_seal(repo: Path, branch: str, cfg: dict | None = None) -> dict | None:
    p = seal_path(repo, branch, cfg)
    if not p.is_file():
        return None
    try:
        d = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        raise GateFault(f"the seal {p} is unreadable ({e}) — delete it and run the full loop again") from None
    if not isinstance(d, dict) or not isinstance(d.get("gates"), dict):
        raise GateFault(f"the seal {p} has no `gates` map — delete it and run the full loop again")
    if d.get("branch") != branch:
        raise GateFault(f"the seal {p} was written for branch `{d.get('branch')}`, not `{branch}` — delete it and run the full loop again")
    return d


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _delta(entries: dict[str, str], tree: dict[str, str]) -> list[str]:
    return sorted(p for p in set(entries) | set(tree) if entries.get(p) != tree.get(p))


def _owed(cfg: dict, seal: dict | None, entries: dict[str, str], doc: dict, base_entries: dict[str, str], base: str) -> dict:
    """The gates owed against `entries` (the tree on disk or at a ref). The reference is the seal's tree when a full
    loop sealed one, else the merge-base's tree: a gate is owed when its read-set moved since its recorded green
    (or since the base when it was never recorded); a changed path no gate reads and no documentation covers owes
    the full loop. Every owed gate names the paths that moved."""
    gates = cfg["gates"]
    seal = seal or {"gates": {}}
    sealed_tree = isinstance(seal.get("tree"), dict)
    tree = seal["tree"] if sealed_tree else base_entries
    against = "its last full seal" if sealed_tree else f"the merge-base with {base} (no full seal on this branch)"
    delta = _delta(entries, tree)
    against_key = "seal" if sealed_tree else "merge-base"
    moved: dict[str, list[str]] = {}
    for name, g in gates.items():
        rec = seal["gates"].get(name)
        now = readset_hash(entries, g["reads"])
        if rec and rec.get("ok"):
            if rec.get("hash") != now:
                moved[name] = [p for p in delta if _in_readset(p, g["reads"])] or ["(a path the seal's tree does not show)"]
        elif readset_hash(base_entries, g["reads"]) != now:
            moved[name] = [p for p in _delta(entries, base_entries) if _in_readset(p, g["reads"])]
    unmapped = [p for p in delta if not any(_in_readset(p, g["reads"]) for g in gates.values()) and not is_documentation(p, doc)[0]]
    if not gates:
        return {"owed": [], "full": True, "unmapped": delta, "moved": {}, "paths": [], "against": against_key,
                "reason": "verification.gates is empty — with no map every change is unmapped and the full loop has nothing to run; declare the loop's gates and what each reads"}
    if unmapped:
        return {"owed": sorted(gates), "full": True, "unmapped": unmapped, "moved": moved, "paths": unmapped, "against": against_key,
                "reason": f"{len(unmapped)} changed path(s) no gate reads and no documentation class covers ({', '.join(unmapped[:5])}, judged against {against}) — an unmapped path owes the full loop; declare its reader in verification.gates or its class in documentation"}
    if moved:
        paths = sorted({p for ps in moved.values() for p in ps})
        return {"owed": sorted(moved), "full": False, "unmapped": [], "moved": moved, "paths": paths, "against": against_key,
                "reason": f"read-set moved since its green (judged against {against}): {', '.join(sorted(moved))} — {', '.join(paths[:6])}"}
    return {"owed": [], "full": False, "unmapped": [], "moved": {}, "paths": [], "against": against_key, "reason": f"nothing owed — every read-set is as its green left it (judged against {against})"}


def _base_of(repo: Path, branch: str, base: str | None) -> str:
    if not base:
        from .branch import diff_base   # the one resolver
        base = diff_base(repo, branch)
    return base


def _reference(repo: Path, base: str, ref: str = "HEAD") -> str:
    """The merge-base of the diff base and `ref`: what the branch forked from — never the base's tip, which moves
    under everyone's feet."""
    try:
        return _git(repo, "merge-base", base, ref).strip() or base
    except GateFault:
        raise GateFault(f"the diff base `{base}` is not a commit this clone knows — fetch it (git fetch origin) or pass --base") from None


def _cfg_or_red(repo: Path) -> tuple[dict | None, dict | None]:
    """Governance not delivered is never infrastructure: a missing block is RED, not a fault."""
    try:
        return vcfg(repo), None
    except GateFault as e:
        return None, {"ok": False, "required": True, "owed": [], "full": True, "unmapped": [], "paths": [], "reason": str(e)}


def _not_required(cfg: dict) -> dict | None:
    if cfg["required"]:
        return None
    if not cfg["reason"]:
        return {"ok": False, "required": True, "owed": [], "full": False, "unmapped": [], "paths": [], "reason": "verification.seal.required is false without a `reason` — say where this repo's loop runs instead (fail closed)"}
    return {"ok": True, "required": False, "owed": [], "full": False, "unmapped": [], "paths": [], "reason": cfg["reason"]}


def plan(repo: Path, branch: str | None = None, base: str | None = None) -> dict:
    """What the loop runs NOW, on the tree on disk: the gates owed, grouped into executions (one per distinct command)."""
    cfg, red = _cfg_or_red(repo)
    if red:
        return {**red, "executions": []}
    branch = branch or current_branch(repo)
    nr = _not_required(cfg)
    if nr:
        return {**nr, "branch": branch, "executions": []}
    doc = documentation_cfg(repo)
    base = _base_of(repo, branch, base)
    entries = tree_entries(repo, skip=cfg["dir"])
    o = _owed(cfg, read_seal(repo, branch, cfg), entries, doc, tree_entries(repo, _reference(repo, base), skip=cfg["dir"]), base)
    execs: dict[str, list[str]] = {}
    for name in o["owed"]:
        cmd = cfg["gates"][name]["command"] or f"<{name}>"
        execs.setdefault(cmd, []).append(name)
    ok = bool(cfg["gates"]) or not o["full"]
    return {"ok": ok, "required": True, "branch": branch, "owed": o["owed"], "full": o["full"], "unmapped": o["unmapped"], "paths": o["paths"], "against": o["against"],
            "executions": [{"command": c, "gates": g} for c, g in execs.items()], "reason": o["reason"]}


def write(repo: Path, gates: list[str], ok: bool, summary: str = "", full: bool = False, branch: str | None = None) -> dict:
    """Record a run of `gates` (their read-set hashes on disk NOW — call it right after the execution, before any
    auto-fix touches the tree) with its outcome. `full` also seals the tree: every gate not recorded in this call
    must already hold a green record whose read-set is still what it hashed — a read-set that moved after its run
    is refused, never re-hashed."""
    cfg = vcfg(repo)
    branch = branch or current_branch(repo)
    unknown = [g for g in gates if g not in cfg["gates"]]
    if unknown:
        raise GateFault(f"unknown gate(s) {', '.join(unknown)} — the map is verification.gates: {', '.join(cfg['gates']) or '(empty)'}")
    if not gates and not full:
        raise GateFault("seal --write needs --gates a,b (or --full to seal the tree over green records)")
    entries = tree_entries(repo, skip=cfg["dir"])
    seal = read_seal(repo, branch, cfg) or {"branch": branch, "gates": {}}
    if full:
        if not ok:
            raise GateFault("--full seals a green loop; a red run is recorded per gate without --full")
        stale, missing = [], []
        for name, g in cfg["gates"].items():
            if name in gates:
                continue
            rec = seal["gates"].get(name)
            if not rec or not rec.get("ok"):
                missing.append(name)
            elif rec.get("hash") != readset_hash(entries, g["reads"]):
                stale.append(name)
        if missing:
            raise GateFault(f"a full loop seals every gate of the map; not green yet: {', '.join(sorted(missing))}")
        if stale:
            raise GateFault(f"read-set moved after its run (an auto-fix or an edit touched what it read): re-run {', '.join(sorted(stale))} before sealing the tree")
    for g in gates:
        seal["gates"][g] = {"ok": bool(ok), "hash": readset_hash(entries, cfg["gates"][g]["reads"]), "at": _now(), "summary": summary}
    if full:
        seal["tree"] = entries
        seal["full_at"] = _now()
    p = seal_path(repo, branch, cfg)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(".tmp")
    tmp.write_text(json.dumps(seal, indent=0), encoding="utf-8")
    tmp.replace(p)
    return {"ok": True, "path": str(p.relative_to(repo)), "gates": gates, "full": full}


def check(repo: Path, branch: str | None = None, ref: str = "HEAD", control_point: str = "push", base: str | None = None) -> dict:
    """The push's question: does the seal cover the tree `ref` carries? ok / red with the gates owed and the paths
    that moved. At `static` (before the loop has run) the answer is the plan's — advisory, never red. At `ci` the seal
    is not on the runner: n/a with the honest reason."""
    cfg, red = _cfg_or_red(repo)
    if red:
        return red
    branch = branch or current_branch(repo)
    nr = _not_required(cfg)
    if nr:
        return nr
    if control_point == "ci":
        return {"ok": True, "required": False, "owed": [], "full": False, "unmapped": [], "paths": [], "reason": CI_REASON}
    if control_point == "static":
        pl = plan(repo, branch, base)
        return {**pl, "ok": True, "advisory": True, "reason": f"the loop has not run yet — owed now: {', '.join(pl['owed']) or 'nothing'} ({pl['reason']})"}
    if not cfg["gates"]:
        return {"ok": False, "required": True, "owed": [], "full": True, "unmapped": [], "paths": [], "reason": "verification.gates is empty — with no map every change is unmapped; declare the loop's gates and what each reads"}
    doc = documentation_cfg(repo)
    base = _base_of(repo, branch, base)
    entries = tree_entries(repo, ref, skip=cfg["dir"])
    o = _owed(cfg, read_seal(repo, branch, cfg), entries, doc, tree_entries(repo, _reference(repo, base, ref), skip=cfg["dir"]), base)
    return {"ok": not o["owed"], "required": True, "owed": o["owed"], "full": o["full"], "unmapped": o["unmapped"], "paths": o["paths"], "against": o["against"], "ref": ref, "reason": o["reason"]}


def validate(repo: Path) -> list[dict]:
    """The map is sound: documentation defined; every gate reads something; a repo that owes no seal says where its loop runs."""
    f: list[dict] = []
    try:
        documentation_cfg(repo)
    except GateFault as e:
        f.append({"path": "config/quality.json", "reason": str(e)})
    try:
        cfg = vcfg(repo)
    except GateFault as e:
        f.append({"path": "config/quality.json", "reason": str(e)}); return f
    if cfg["required"] and not cfg["gates"]:
        f.append({"path": "config/quality.json", "reason": "verification.seal.required is true and verification.gates is empty — every change would owe a loop nothing can run"})
    if not cfg["required"] and not cfg["reason"]:
        f.append({"path": "config/quality.json", "reason": "verification.seal.required is false without a `reason` — say where this repo's loop runs instead"})
    return f


def render(res: dict) -> str:
    if not res.get("required", True):
        return f"seal: n/a — {res['reason']}"
    if res.get("advisory"):
        return f"seal: ok (advisory, static round) — {res['reason']}"
    if res["ok"]:
        return f"seal: ok — {res['reason']}"
    what = "the full loop" if res.get("full") else ", ".join(res["owed"])
    paths = res.get("paths") or []
    tail = f"\n  moved: {', '.join(paths[:10])}{' …' if len(paths) > 10 else ''}" if paths else ""
    return (f"seal: RED — {res['reason']}\n  owed: {what} — run it (factory-build-verification § Full Verification Gate → python3 scripts/gate.py seal --plan), "
            f"commit the bytes it sealed (the whole tree on disk, the loop hashed it), push again{tail}")
