# Generated by Phase: IMPLEMENT | Feature: EVOL-043
"""Injection budgets: one home (`config/quality.json` → `budgets`), one reader that runs the REAL producer
against its worst-case input and measures what it emits. Not the file size — the bytes a session receives.

  session_start  scripts/validate-governance.sh --banner
  prompt_submit  scripts/governance-onprompt.sh under GOVERNANCE_ONPROMPT_WORST_CASE=1 (snapshot reload + warning)
  pre_edit       .claude/hooks/deliver-governance.sh on the path that matches the most defect classes
  snapshot       .context/governance_snapshot.md (bytes on disk; n/a where no snapshot exists)
  law_sentence_max_chars / dc_invariant_max_chars  shape budgets, checked over the corpus
"""
from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

from .common import GateFault, any_glob, key
from .corpus import catalog, laws

REQUIRED = ("session_start", "prompt_submit", "pre_edit", "snapshot", "law_sentence_max_chars", "dc_invariant_max_chars")


def _run(repo: Path, cmd: list[str], stdin: str = "", env: dict | None = None) -> str:
    try:
        r = subprocess.run(cmd, cwd=str(repo), input=stdin, capture_output=True, text=True, timeout=120,
                           env={**os.environ, **(env or {})})
    except (OSError, subprocess.TimeoutExpired) as e:
        raise GateFault(f"producer {' '.join(cmd)} could not run: {e}") from None
    return r.stdout


def worst_case_path(repo: Path) -> str:
    """The path that the most defect classes and families govern (sample paths derived from their globs)."""
    cat = catalog(repo)
    candidates: set[str] = set()
    for f in cat["families"]:
        for g in f["surface"]:
            candidates.add(_sample(g))
    for d in cat["dcs"]:
        for g in d["paths"]:
            if g != "*":
                candidates.add(_sample(g))
    # a path can sit under several globs at once (src/** AND **/migrations/**): combine directory prefixes
    globs = [g.strip().strip("`") for f in cat["families"] for g in f["surface"]] + \
            [g.strip().strip("`") for d in cat["dcs"] for g in d["paths"]]
    prefixes = {g[:-3] + "/" for g in globs if g.endswith("/**") and "*" not in g[:-3]}
    for pre in prefixes:
        for c in list(candidates):
            if not c.startswith(pre):
                candidates.add(pre + c)
    if not candidates:
        return "src/example.py"
    def score(p: str) -> int:
        return sum(1 for d in cat["dcs"] if d["paths"] == ["*"] or any_glob(p, d["paths"])) \
            + sum(1 for f in cat["families"] if any_glob(p, f["surface"]))
    return max(sorted(candidates), key=score)


def _sample(glob: str) -> str:
    """A concrete path under a glob: `src/**` → `src/x/x.py`, `**/*.sql` → `x/x.sql`, `infra/` → `infra/x`."""
    g = glob.strip().strip("`")
    if g.endswith("/"):
        return g + "x"
    parts = g.split("/")
    out = []
    for p in parts:
        if p == "**":
            out.append("x")
        elif "*" in p:
            out.append(p.replace("**", "x").replace("*", "x") if "." in p else "x")
        else:
            out.append(p)
    path = "/".join(out)
    return path if "." in Path(path).name else path + "/x.py"


def measure(repo: Path) -> dict:
    """Bytes emitted by each producer. Raises GateFault when a required key is missing."""
    budgets = key(repo, "budgets", required=True)
    missing = [k for k in REQUIRED if not isinstance(budgets.get(k), int)]
    if missing:
        raise GateFault(f"config/quality.json budgets missing integer keys: {', '.join(missing)}")
    rows: dict[str, dict] = {}
    banner = repo / "scripts/validate-governance.sh"
    rows["session_start"] = {"budget": budgets["session_start"],
                             "bytes": len(_run(repo, ["bash", str(banner), "--banner"]).encode()) if banner.is_file() else 0,
                             "producer": "scripts/validate-governance.sh --banner"}
    onprompt = repo / "scripts/governance-onprompt.sh"
    rows["prompt_submit"] = {"budget": budgets["prompt_submit"],
                             "bytes": len(_run(repo, ["bash", str(onprompt)], '{"session_id":"budget","prompt":"x"}',
                                              {"GOVERNANCE_ONPROMPT_WORST_CASE": "1"}).encode()) if onprompt.is_file() else 0,
                             "producer": "scripts/governance-onprompt.sh (worst case: reload + warning)"}
    deliver = repo / ".claude/hooks/deliver-governance.sh"
    wpath = worst_case_path(repo)
    rows["pre_edit"] = {"budget": budgets["pre_edit"],
                        "bytes": len(_run(repo, ["bash", str(deliver)],
                                          json.dumps({"tool_input": {"file_path": wpath}, "session_id": "budget-fresh"})).encode())
                        if deliver.is_file() else 0,
                        "producer": f".claude/hooks/deliver-governance.sh on {wpath}"}
    snap = repo / ".context/governance_snapshot.md"
    rows["snapshot"] = {"budget": budgets["snapshot"], "bytes": snap.stat().st_size if snap.is_file() else None,
                        "producer": ".context/governance_snapshot.md" + ("" if snap.is_file() else " (absent — n/a here)")}
    allv = laws(repo)
    longest_law = max((len(l["sentence"]) for l in allv["universal"] + allv["project"]), default=0)
    rows["law_sentence_max_chars"] = {"budget": budgets["law_sentence_max_chars"], "bytes": longest_law,
                                      "producer": "longest law sentence in the index"}
    longest_dc = max((len(d["invariant"]) for d in catalog(repo)["dcs"]), default=0)
    rows["dc_invariant_max_chars"] = {"budget": budgets["dc_invariant_max_chars"], "bytes": longest_dc,
                                      "producer": "longest defect-class invariant"}
    for r in rows.values():
        r["ok"] = r["bytes"] is None or r["bytes"] <= r["budget"]
    return rows


def render(rows: dict) -> str:
    out = ["| injection point | budget | measured | producer | |", "|---|---|---|---|---|"]
    for k, r in rows.items():
        out.append(f"| {k} | {r['budget']} | {'n/a' if r['bytes'] is None else r['bytes']} | {r['producer']} | {'ok' if r['ok'] else 'OVERFLOW'} |")
    return "\n".join(out)
