# Generated by Phase: IMPLEMENT | Feature: EVOL-044
"""Coherence gates (EVOL-044): artefact currency and manifest ↔ frontmatter version parity.
(Body ↔ sentence parity lives in corpus.parity — the same reader.)

currency        An artefact that certifies a build declares WHAT it certified in its frontmatter:
                    certifies:
                      subject: diff | tree
                      base: origin/main          # diff only — the range base the review ran on
                      paths: ["src/**", …]       # tree only — the paths the verdict covers
                      hash: <sha256>
                The gate recomputes the hash THE WAY THE TOOLCHAIN COMPUTES IT (`certify()` below — the
                same function the writer calls through `gate.py certify`) and reports STALE when it differs:
                the artefact must be re-taken, not re-blessed. A certifying artefact (config key
                `coherence.certifying_artefacts` globs) whose status is terminal and carries no `certifies:`
                is red too. Frontmatter is read by the one parser (gates.common.read_frontmatter).
manifest-parity A governed file whose frontmatter carries `version:` and its manifest entry are one digit and
                move together; divergence is reported with the manifest as the source of truth. Unreadable
                frontmatter is red (it cannot be compared).
"""
from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path

from .common import GateFault, any_glob, key, load_coherence, read_frontmatter, tracked_files

TERMINAL = {"APPROVED", "PASSED", "PASS", "SECURE", "IMPLEMENTED_AND_VERIFIED"}
DEFAULT_CERTIFYING = ["docs/spec/*/qa/qa_report*.md", "docs/spec/*/review/peer_review_*.md",
                      "docs/spec/*/review/sec_audit*.md", "docs/spec/*/smoke_e2e_report.md"]


# ─── the hash, computed once for writers and checkers ────────────────────────────

def certify(repo: Path, subject: str, base: str = "origin/main", paths: list[str] | None = None) -> str:
    """The certification hash. `diff`: the factory-code-review content hash (sha256 over sorted path\\0blob-sha
    of is_code ∪ is_test files in base..HEAD — the same pipeline the push gate verifies), or `EMPTY`.
    `tree`: sha256 over sorted path\\0blob-sha of every tracked file under `paths` at HEAD."""
    if subject == "diff":
        dct = repo / ".claude/skills/factory-pr-review/scripts/detect_change_type.py"
        crh = repo / ".claude/skills/factory-code-review/scripts/code_review_hash.py"
        if not dct.is_file() or not crh.is_file():
            raise GateFault("the review-hash pipeline (factory-pr-review detect_change_type.py + factory-code-review code_review_hash.py) is not delivered — run factory-sync.sh")
        try:
            classified = subprocess.run(["python3", str(dct), "--git-range", f"{base}..HEAD"], cwd=str(repo), capture_output=True, text=True, timeout=120)
            hashed = subprocess.run(["python3", str(crh)], cwd=str(repo), input=classified.stdout, capture_output=True, text=True, timeout=120)
        except (OSError, subprocess.TimeoutExpired) as e:
            raise GateFault(f"the review-hash pipeline could not run: {e}") from None
        if classified.returncode != 0 or hashed.returncode != 0:
            raise GateFault(f"the review-hash pipeline failed on {base}..HEAD: {(hashed.stderr or classified.stderr).strip().splitlines()[-1:] or ['(no message)']}")
        return hashed.stdout.strip()
    if subject == "tree":
        if not paths:
            raise GateFault("certify --subject tree needs the paths the verdict covers (e.g. src/** tests/**)")
        try:
            out = subprocess.run(["git", "-C", str(repo), "ls-files", "-s"], capture_output=True, text=True, timeout=60)
        except (OSError, subprocess.TimeoutExpired) as e:
            raise GateFault(f"git ls-files could not run: {e}") from None
        if out.returncode != 0:
            raise GateFault("not a git repository — a tree certification needs tracked files")
        entries = []
        for line in out.stdout.splitlines():
            meta, _, path = line.partition("\t")
            blob = meta.split()[1] if len(meta.split()) > 1 else ""
            if any_glob(path, paths):
                entries.append(f"{path}\0{blob}")
        return hashlib.sha256("\n".join(sorted(entries)).encode()).hexdigest()
    raise GateFault(f"unknown certification subject `{subject}` — use diff or tree")


# ─── currency ───────────────────────────────────────────────────────────────────

def _is_terminal(fm: dict) -> bool:
    return any(str(fm.get(k, "")).upper() in TERMINAL for k in ("status", "verdict", "overall_verdict"))


def currency(repo: Path) -> list[dict]:
    """Every certifying artefact in a terminal state: `certifies` present and its hash equal to a fresh
    computation. Returns findings [{path, reason}]; empty = green."""
    globs = key(repo, "coherence.certifying_artefacts", default=DEFAULT_CERTIFYING) or DEFAULT_CERTIFYING
    findings: list[dict] = []
    for rel in tracked_files(repo):
        if not any_glob(rel, globs):
            continue
        try:
            fm = read_frontmatter(repo / rel)
        except GateFault as e:
            findings.append({"path": rel, "reason": f"frontmatter unreadable: {e}"})
            continue
        if not _is_terminal(fm):
            continue
        cert = fm.get("certifies")
        if not isinstance(cert, dict) or not cert.get("subject") or not cert.get("hash"):
            findings.append({"path": rel, "reason": "certifies-missing: a terminal verdict must declare what it certified (certifies.subject + hash)"})
            continue
        try:
            fresh = certify(repo, str(cert["subject"]), str(cert.get("base") or "origin/main"), cert.get("paths") or None)
        except GateFault as e:
            findings.append({"path": rel, "reason": f"cannot recompute: {e}"})
            continue
        if fresh != str(cert["hash"]):
            findings.append({"path": rel, "reason": f"STALE: certified {cert['subject']} {str(cert['hash'])[:12]}… but the subject is now {fresh[:12]}… — re-take the verdict, never re-bless it"})
    return findings


# ─── manifest ↔ frontmatter parity ───────────────────────────────────────────────

def manifest_path(repo: Path) -> Path:
    primary = (load_coherence(repo).get("audit", {}).get("manifest_paths") or {}).get("primary")
    for candidate in ([primary] if primary else []) + [".context/templates/setup/governance_versions.json", "docs/project_log/governance_versions.json"]:
        if candidate and (repo / candidate).is_file():
            return repo / candidate
    raise GateFault("no governance manifest found (coherence-context audit.manifest_paths.primary)")


ROOTS = {"templates": ".context/templates/setup/", "agent_templates": ".context/templates/", "framework_core": ""}


def manifest_parity(repo: Path) -> list[dict]:
    """Every manifest entry whose file carries a frontmatter `version:` must equal the manifest version."""
    mp = manifest_path(repo)
    try:
        m = json.loads(mp.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        raise GateFault(f"{mp.relative_to(repo)} is not readable JSON ({e})") from None
    findings: list[dict] = []
    for section, root in ROOTS.items():
        for k, e in (m.get(section) or {}).items():
            if k.startswith("_") or not isinstance(e, dict) or "version" not in e:
                continue
            p = repo / (e.get("path") or (root + k)) if section != "templates" else repo / (root + k)
            if section == "templates" and not p.is_file():
                p = repo / (e.get("target") or "")   # downstream: the materialised target
            if not p.is_file() or p.suffix != ".md":
                continue
            try:
                fm = read_frontmatter(p)
            except GateFault as ex:
                findings.append({"path": str(p.relative_to(repo)), "reason": f"frontmatter unreadable: {ex}"})
                continue
            fv = fm.get("version")
            if fv is None:
                continue
            if str(fv) != str(e["version"]):
                findings.append({"path": str(p.relative_to(repo)), "reason": f"frontmatter version {fv} ≠ manifest {e['version']} — the manifest is the source of truth: set the frontmatter to {e['version']} (or bump both in one commit)"})
    return findings


def render(name: str, findings: list[dict]) -> str:
    if not findings:
        return f"{name}: ok"
    out = [f"{name}: FAIL — {len(findings)} finding(s):"] + [f"  {f['path']}: {f['reason']}" for f in findings]
    return "\n".join(out)
