# Generated by Phase: IMPLEMENT | Feature: EVOL-051
"""Governance digest currency of the feature's planning artefacts (EVOL-051) — the loop checks what the push checks.

For the feature the branch names (`feature/{ID}…`, `epic/{ID}…`), every planning artefact listed in
`verification.digest_artefacts` that exists under `docs/spec/{ID}/` (`design.md`, `dev_plan.md` by default —
technical artefacts; the journey is business-pure, LAW-16, and carries no digest) is judged on two predicates:

  fingerprint   frontmatter `governance_digest_version` equals the current governance fingerprint — the snapshot's
                `constitution_hash[:8]`, the GCRP identity BLUEPRINT writes into design.md and IMPLEMENT Step 0b reads.
  completeness  the artefact names every rule the corpus binds to this change's surface (`applicable` over the
                branch diff — the one resolver): a bound rule the digest never mentions is an incomplete digest.

Absent, stale or incomplete → red, in the static round before the critics and at the push (a profile member) — one
predicate, never a copy. No feature on the branch, or no artefact yet → ok with the reason. A project without a
governance snapshot is a fault (GCRP: it must exist).
"""
from __future__ import annotations

import re
from pathlib import Path

from . import corpus
from .coherence import FEATURE_IN_BRANCH
from .common import GateFault, context, read_frontmatter
from .seal import current_branch, diff_paths, vcfg

SNAPSHOT = ".context/governance_snapshot.md"
DIGEST_KEY = "governance_digest_version"


def feature_id(branch: str) -> str | None:
    m = FEATURE_IN_BRANCH.match(branch or "")
    return m.group(1) if m else None


def fingerprint(repo: Path) -> str | None:
    """constitution_hash[:8] of the governance snapshot; None in the framework repo (no constitution)."""
    p = repo / SNAPSHOT
    if not p.is_file():
        if context(repo) == "meta":
            return None
        raise GateFault(f"{SNAPSHOT} is missing — the governance snapshot is the GCRP identity every digest is checked against (SETUP materialises it; validate-governance.sh regenerates it)")
    fm = read_frontmatter(p)
    h = str(fm.get("constitution_hash") or "").strip()
    if not h or h.lower() in ("null", "none"):
        if context(repo) == "meta":
            return None
        raise GateFault(f"{SNAPSHOT} carries no constitution_hash — regenerate the snapshot")
    return h[:8]


def bound_rules(repo: Path, base: str) -> list[str]:
    """The rule names (file stems) the corpus binds to the branch's change: path-bound and always-on."""
    paths = diff_paths(repo, base)
    res = corpus.applicable(repo, {}, paths or None)
    return sorted({Path(r["path"]).stem for r in res["active"]["rules"]})


def check(repo: Path, base: str, branch: str | None = None) -> dict:
    branch = branch or current_branch(repo)
    fid = feature_id(branch)
    if not fid:
        return {"ok": True, "feature": None, "artefacts": [], "reason": f"`{branch or 'detached'}` names no feature — no planning artefact to judge"}
    cfg = vcfg(repo)
    folder = repo / "docs/spec" / fid
    present = [a for a in cfg["digest_artefacts"] if (folder / a).is_file()]
    if not present:
        return {"ok": True, "feature": fid, "artefacts": [], "reason": f"docs/spec/{fid}/ carries none of {', '.join(cfg['digest_artefacts'])} yet — nothing to judge"}
    fp = fingerprint(repo)
    rules = bound_rules(repo, base)
    rows, red = [], []
    for a in present:
        p = folder / a
        rel = f"docs/spec/{fid}/{a}"
        try:
            fm = read_frontmatter(p)
        except GateFault as e:
            rows.append({"artefact": rel, "ok": False, "reason": f"unreadable frontmatter: {e}"}); red.append(rel); continue
        have = str(fm.get(DIGEST_KEY) or "").strip()
        text = p.read_text(encoding="utf-8", errors="replace")
        problems = []
        if not have:
            problems.append(f"no `{DIGEST_KEY}` in the frontmatter — the digest was never generated (BLUEPRINT § GCD writes it; IMPLEMENT --plan and DEVOPS copy it)")
        elif fp is not None and have[:8] != fp:
            problems.append(f"stale: digest {have[:8]}, corpus {fp} — regenerate (BLUEPRINT --refine {fid})")
        missing = [r for r in rules if not re.search(r"(?<![\w-])" + re.escape(r) + r"(?![\w-])", text)]
        if missing:
            problems.append(f"incomplete: bound rule(s) never named — {', '.join(missing)}")
        rows.append({"artefact": rel, "ok": not problems, "reason": "; ".join(problems) or "current and complete"})
        if problems:
            red.append(rel)
    return {"ok": not red, "feature": fid, "fingerprint": fp, "bound": rules, "artefacts": rows,
            "reason": f"{len(red)} of {len(rows)} planning artefact(s) stale or incomplete" if red else f"{len(rows)} planning artefact(s) current and complete"}


def render(res: dict) -> str:
    if res["ok"] and not res.get("artefacts"):
        return f"digests: ok — {res['reason']}"
    lines = [f"digests: {'ok' if res['ok'] else 'RED'} — {res['reason']} (feature {res['feature']}, corpus {res.get('fingerprint') or '—'})"]
    for r in res.get("artefacts", []):
        lines.append(f"  {'✓' if r['ok'] else '✗'} {r['artefact']}: {r['reason']}")
    return "\n".join(lines)
