# Generated by Phase: IMPLEMENT | Feature: EVOL-046
"""Gate profiles per control point (EVOL-046): no gate is optional — it changes its control point.

mode       ONE key, `delivery_mode` at the top of the governance manifest (`development` | `production`), read by
           ONE definition that fails closed: an absent key, an unknown value or an unreadable manifest is
           `production`; no environment variable overrides it.
profile    derived from the mode and the branch class (gates/branch.py): `light` only for a sub-increment while
           the project is in development mode; `full` for everything else — the train close, a plain branch, a
           malformed or unclassifiable name, and every branch in production mode.
members    the gate members, enumerated by PROPERTY: `light` = the members that need no build and no database;
           `full` = every member. Each member names its owner — the reader runs the script members at the push /
           CI control points (all-report: every member reports, one verdict names every red member and what was
           skipped); agent-run members (the full verification loop, the sweep, the smoke) are owed to their owner
           at their control point and listed as such. The light profile writes no seal.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

from . import branch as branch_mod
from .common import GateFault, context

MODES = ("development", "production")
STRICTEST = "production"

# name, needs_build, needs_database, owner, runner (None = agent-run), meta_only
MEMBERS = [
    ("retired-terms",    False, False, "gate.py",                 ["gate", "retired-terms"], False),
    ("budget",           False, False, "gate.py",                 ["gate", "budget"], False),
    ("law-parity",       False, False, "gate.py",                 ["gate", "laws", "--parity"], False),
    ("manifest-parity",  False, False, "gate.py",                 ["gate", "manifest-parity"], False),
    ("currency",         False, False, "gate.py",                 ["gate", "currency", "--base", "{base}"], False),
    ("surface",          False, False, "gate.py",                 ["gate", "surface", "--base", "{base}", "--branch", "{branch}"], False),
    ("runtime-surface",  False, False, "gate.py",                 ["gate", "runtime-surface"], False),
    ("agents",           False, False, "gate.py",                 ["gate", "agents"], False),
    ("seal",             False, False, "gate.py",                 ["gate", "seal", "--check", "--base", "{base}", "--branch", "{branch}", "--control-point", "{control_point}"], False),
    ("digests",          False, False, "gate.py",                 ["gate", "digests", "--base", "{base}", "--branch", "{branch}"], False),
    ("governance",       False, False, "validate-governance.sh (framework repo: manifest drift / orphan / stale)", ["bash", "scripts/validate-governance.sh", "--base", "{base_branch}"], True),   # a project has no framework manifest; manifest-parity covers its own
    ("adr-sync",         False, False, "check-adr-constitution-sync.sh", ["bash", "scripts/check-adr-constitution-sync.sh", "{base}"], False),
    ("applicability",    False, False, "check-applicability-frontmatter.sh", ["bash", "scripts/check-applicability-frontmatter.sh"], False),
    ("secrets",          False, False, "pre-commit / pre-push step 2 (per pushed ref)", None, False),
    ("coherence-audit",  False, False, "preflight Step 0 (marker)", None, False),
    ("code-review",      False, False, "preflight Block 20 (marker)", None, False),
    ("sast",             True,  False, "BVL full loop (the security lens per phase; repo-wide at the loop)", None, False),
    ("complexity",       True,  False, "BVL full loop (MCP, after the tests)", None, False),
    ("tests",            True,  False, "BVL full loop", None, False),
    ("lint",             True,  False, "BVL full loop", None, False),
    ("typecheck",        True,  False, "BVL full loop", None, False),
    ("build",            True,  False, "BVL full loop", None, False),
    ("format",           True,  False, "BVL full loop", None, False),
    ("seed-alignment",   False, True,  "BVL full loop", None, False),
    ("preventive-sweep", True,  True,  "DEVOPS --deploy (pre-deploy)", None, False),
    ("smoke-e2e",        True,  True,  "QA --verify on the deployed build", None, False),
]


def manifest_path(repo: Path) -> Path:
    return repo / (".context/templates/setup/governance_versions.json" if context(repo) == "meta" else "docs/project_log/governance_versions.json")


def mode(repo: Path) -> dict:
    """{mode, reason}. Fail-closed: anything but a known value in a readable manifest is the strictest mode."""
    p = manifest_path(repo)
    try:
        doc = json.loads(p.read_text(encoding="utf-8"))
        v = doc.get("delivery_mode") if isinstance(doc, dict) else None
    except FileNotFoundError:
        return {"mode": STRICTEST, "reason": f"{p.relative_to(repo)} is absent — strictest mode"}
    except (OSError, json.JSONDecodeError) as e:
        return {"mode": STRICTEST, "reason": f"{p.relative_to(repo)} is not readable JSON ({e.__class__.__name__}) — strictest mode"}
    if v not in MODES:
        return {"mode": STRICTEST, "reason": f"delivery_mode is {v!r} (not one of {', '.join(MODES)}) — strictest mode"}
    return {"mode": v, "reason": f"delivery_mode: {v} ({p.relative_to(repo)})"}


def profile(repo: Path, branch: str | None = None, control_point: str = "push") -> dict:
    m = mode(repo)
    try:
        info = branch_mod.branch_class(repo, branch)
    except GateFault as e:          # detached HEAD, no name: nothing to be light about
        info = {"branch": branch or "", "class": "unknown"}
        why = str(e)
    else:
        why = ""
    light = m["mode"] == "development" and info["class"] == "sub-increment"
    if control_point == "static":   # the static round before the critics (EVOL-051): every member that needs no build and no database, whatever the class or the mode
        light = True
    reason = ("the static round before the critics: every member that needs no build and no database" if control_point == "static" else
              f"sub-increment pushed to its train ({info.get('train')}) in development mode" if light else
              why or (f"{info['class']} branch" if m["mode"] == "development" else f"{m['mode']} mode: every branch owes the full profile"))
    return {"mode": m["mode"], "mode_reason": m["reason"], "branch": info["branch"], "class": info["class"],
            "profile": "light" if light else "full", "reason": reason}


def owed(prof: str) -> list[dict]:
    out = []
    for name, nb, nd, owner, runner, meta_only in MEMBERS:
        if prof == "light" and (nb or nd):
            continue
        out.append({"member": name, "needs_build": nb, "needs_database": nd, "owner": owner, "runnable": runner is not None, "meta_only": meta_only})
    return out


def _cmd(repo: Path, runner: list[str], base: str, branch: str, control_point: str = "push") -> list[str]:
    gate = str(Path(__file__).resolve().parent.parent / "gate.py")   # the reader that is running — the delivered one
    out = []
    for tok in runner:
        bb = re.sub(r"^refs/remotes/", "", base)
        bb = bb.split("/", 1)[1] if "/" in bb else bb   # origin/x → x (validate-governance re-qualifies it)
        tok = tok.replace("{base}", base).replace("{base_branch}", bb).replace("{branch}", branch).replace("{control_point}", control_point)
        out.append(tok)
    if out[0] == "gate":
        out = [sys.executable, gate, "--repo", str(repo)] + out[1:]
    return out


def run(repo: Path, branch: str | None = None, base: str | None = None, control_point: str = "push", only: list[str] | None = None) -> dict:
    """All-report run of the script members owed at this control point. Never stops at the first red."""
    pr = profile(repo, branch, control_point)
    br = pr["branch"] or ""
    try:
        base = base or branch_mod.diff_base(repo, branch)
        if "/" not in base:
            raise GateFault(f"the base must be a remote ref (origin/…), not `{base}` — a local branch may be stale")
    except GateFault as e:   # unknown name, detached HEAD, a train or base not on the remote: nothing can be measured → RED, never a pass
        return {**pr, "control_point": control_point, "base": None, "results": [], "owed_elsewhere": [],
                "verdict": "RED", "summary": f"no diff base — nothing was measured: {e}"}
    ctx = context(repo)
    results, elsewhere = [], []
    for name, nb, nd, owner, runner, meta_only in MEMBERS:
        if pr["profile"] == "light" and (nb or nd):
            continue
        if runner is None:
            elsewhere.append({"member": name, "owner": owner})   # owed at its own control point — listed, never dropped
            continue
        if only and name not in only:
            continue
        if meta_only and ctx != "meta":
            results.append({"member": name, "rc": 0, "status": "n/a", "tail": "framework repo only", "output": ""})
            continue
        cmd = _cmd(repo, runner, base, br, control_point)
        if cmd[0] == "bash" and not (repo / cmd[1]).is_file():   # governance not delivered is a red on the delivery, never an infra pass
            results.append({"member": name, "rc": 1, "status": "RED", "tail": f"{cmd[1]} is not delivered — run scripts/factory-sync.sh", "output": f"{cmd[1]} is not delivered — run scripts/factory-sync.sh"})
            continue
        try:
            r = subprocess.run(cmd, cwd=str(repo), capture_output=True, text=True, timeout=900)
            rc, text = r.returncode, (r.stdout + r.stderr)
        except (OSError, subprocess.TimeoutExpired) as e:
            rc, text = 2, f"could not run: {e}"
        clean = re.sub(r"\x1b\[[0-9;]*m", "", text).strip()
        tail = " ".join(ln.strip() for ln in clean.splitlines()[-3:])
        results.append({"member": name, "rc": rc, "status": "ok" if rc == 0 else ("RED" if rc == 1 else "FAULT"), "tail": tail[:400],
                        "output": "" if rc == 0 else clean[-6000:]})   # a red member keeps its evidence
    red = [r["member"] for r in results if r["rc"] == 1]
    faults = [r["member"] for r in results if r["rc"] not in (0, 1)]
    verdict = "RED" if red else ("FAULT" if faults else "ok")
    parts = ([f"red: {', '.join(red)}"] if red else []) + ([f"could not run: {', '.join(faults)}"] if faults else [])
    return {**pr, "control_point": control_point, "base": base, "results": results, "owed_elsewhere": elsewhere,
            "verdict": verdict, "summary": " · ".join(parts)}


def render(rep: dict) -> str:
    lines = [f"profile: {rep['profile']} — {rep['reason']} · {rep['mode_reason']}"]
    if rep.get("base") is None and rep.get("results") == []:
        return "\n".join(lines + [f"  {rep['summary']}"])
    lines.append(f"  control point {rep['control_point']} · base {rep['base']} · {len(rep['results'])} member(s) ran, every one reports:")
    for r in rep["results"]:
        mark = "·" if r["status"] == "n/a" else ("✓" if r["rc"] == 0 else ("✗" if r["rc"] == 1 else "?"))
        lines.append(f"  {mark} {r['member']}" + (f" — {r['tail']}" if r["status"] == "n/a" else ("" if r["rc"] == 0 else f" — {r['status']}")))
        if r["rc"] != 0:
            lines.extend("      " + ln for ln in (r.get("output") or r["tail"]).splitlines() if ln.strip())
    if rep["owed_elsewhere"]:
        lines.append("  owed at their own control point (not run here): " + ", ".join(f"{e['member']} → {e['owner']}" for e in rep["owed_elsewhere"]))
    skipped = [m for m in (n for n, nb, nd, *_ in MEMBERS if nb or nd)] if rep["profile"] == "light" else []
    if skipped:
        lines.append("  skipped by the light profile (need a build or a database — owed at their own control point: the train close, the deployment): " + ", ".join(skipped))
    lines.append(f"verdict: {rep['verdict']}" + (f" — {rep['summary']}" if rep["summary"] else " — the light profile writes no seal" if rep["profile"] == "light" else ""))
    return "\n".join(lines)


# ─── one definition ──────────────────────────────────────────────────────────────

SECOND_DEFINITION = [
    (re.compile(r"(?i)protected[_-]?branches\s*=|\bprotected=\("), "a protected-branch list — ask `gate.py branch-class --protected`"),
    (re.compile(r"\b(main|master|develop)\|(main|master|develop)\b|\bmain master\b|\bmaster main\b|\bin main\b|\bin master\b|== *[\"']?(main|master)[\"']?\b"),
     "a branch regex, list or comparison — ask `gate.py branch-class`"),
    (re.compile(r"(?i)delivery.?mode"), "a read of the delivery mode — ask `gate.py profile`"),
    (re.compile(r"(?i)(DELIVERY|FACTORY)_MODE|\bGATE_PROFILE\s*="), "an environment override of the mode or profile — none exists"),
]
SCAN = [".claude/hooks/*.sh", "scripts/hooks/*", "scripts/*.sh", ".github/workflows/*", ".claude/skills/factory-pr-review/scripts/preflight.sh",
        ".context/templates/setup/claude/hooks/*.sh", ".context/templates/setup/scripts/hooks/*", ".context/templates/setup/scripts/*.sh",
        ".context/templates/setup/workflows/*"]


# writers of the key by role, never readers: SETUP materialises it; the smoke plays SETUP on a scratch project
WRITERS = {"scripts/materialize-synthetic.sh"}


def one_definition(repo: Path) -> list[dict]:
    """Hooks, scripts, workflows and the preflight never keep their own branch list, mode read or mode override."""
    findings = []
    for pattern in SCAN:
        for p in sorted(repo.glob(pattern)):
            if not p.is_file() or str(p.relative_to(repo)) in WRITERS:
                continue
            for n, line in enumerate(p.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
                code = re.split(r"(?:^|\s)#", line, 1)[0]   # a comment starts the line or follows whitespace — `${1#x}` is code
                for rx, what in SECOND_DEFINITION:
                    if rx.search(code):
                        findings.append({"path": str(p.relative_to(repo)), "line": n, "reason": what})
                        break   # one finding per line
    return findings
