# Generated by Agent: SETUP | Framework: myrmion-AI-factory | Feature: EVOL-053
"""Test-case traceability at collection (EVOL-053) — the Python home of the case → test link.

The ONE place a test states the case it proves is the `case` marker on the test (or its class, or the module's
`pytestmark`), with one literal string argument `FEATURE/CASE` — the feature folder under docs/spec/ and the case id
its test_plan.md declares (the grammar is `traceability.id_pattern` in config/quality.json), e.g. FEAT-001/TC-01.

This plugin refuses collection — never a silent skip — when a marker carries an id that is malformed or that no plan
declares: the declared set is read through the one reader (`python3 scripts/gate.py traceability --declared --json`),
never re-derived here. It also refuses to run without `--strict-markers` (an unregistered marker is a typo, not a
link) and warns on a test that carries `case` together with `skip` / `skipif` / `xfail` (a skipped test proves no
case; the push gate does not count it as a link). When the project's config says `traceability.required: false`,
the plugin does nothing. The push and CI run the same reader (`gate.py traceability`, a member of the gate profile).

Wire it once:
  - flat layout (tests/ without __init__.py):      tests/conftest.py → pytest_plugins = ["conftest_traceability"]
  - package layout (tests/__init__.py present):    root conftest.py  → pytest_plugins = ["tests.conftest_traceability"]
  and `addopts = --strict-markers` (pytest.ini / pyproject [tool.pytest.ini_options]), `testpaths = tests`.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

_STATE: dict = {}


def _repo_root() -> Path:
    here = Path(__file__).resolve()
    for p in [here.parent, *here.parents]:
        if (p / "scripts" / "gate.py").is_file():
            return p
    return here.parent.parent


def _declared() -> dict:
    """{required, declared: set, error}. Read once per session through the one reader."""
    if _STATE:
        return _STATE
    repo = _repo_root()
    gate = repo / "scripts" / "gate.py"
    if not gate.is_file():
        _STATE.update(required=True, declared=set(), error=f"the gate reader {gate} is not delivered — run factory-sync.sh / SETUP --upgrade")
        return _STATE
    try:
        r = subprocess.run([sys.executable, str(gate), "--repo", str(repo), "traceability", "--declared", "--json"], capture_output=True, text=True, timeout=120)
    except (OSError, subprocess.TimeoutExpired) as e:
        _STATE.update(required=True, declared=set(), error=f"the traceability reader could not run: {e}")
        return _STATE
    try:
        d = json.loads(r.stdout)
    except ValueError:
        _STATE.update(required=True, declared=set(), error=(r.stderr.strip().splitlines() or [f"the reader exited {r.returncode} with no JSON"])[-1])
        return _STATE
    if d.get("required") is False:
        _STATE.update(required=False, declared=set(), error=None)
        return _STATE
    _STATE.update(required=True, declared=set(d.get("declared", [])), error=None)
    return _STATE


def pytest_configure(config):
    config.addinivalue_line("markers", "case(id): the test-plan case this test proves — FEATURE/CASE, e.g. FEAT-001/TC-01 (EVOL-053 traceability home)")
    if not getattr(config.option, "strict_markers", False):
        raise pytest.UsageError("test-case traceability (EVOL-053): run pytest with --strict-markers (addopts in pytest.ini / pyproject) — an unregistered marker is a typo, not a link")


def pytest_collection_modifyitems(config, items):
    problems: list[str] = []
    state = None
    for item in items:
        markers = list(item.iter_markers(name="case"))
        if not markers:
            continue
        state = state or _declared()
        if not state["required"]:
            return   # the project declares no test plan: nothing to validate
        for m in markers:
            if len(m.args) != 1 or not isinstance(m.args[0], str) or not m.args[0].strip():
                problems.append(f"{item.nodeid}: @pytest.mark.case needs one literal string id (FEATURE/CASE)")
                continue
            qid = m.args[0].strip()
            if state["error"]:
                problems.append(f"{item.nodeid}: cannot validate `{qid}` — {state['error']}")
                continue
            if qid not in state["declared"]:
                problems.append(f"{item.nodeid}: `{qid}` names no case any test_plan.md declares (malformed or unknown)")
        if any(item.iter_markers(name=n) for n in ("skip", "skipif", "xfail")):
            item.warn(pytest.PytestWarning(f"{item.nodeid}: carries `case` and `skip`/`xfail` — a skipped test proves no case; the push gate does not count it as a link"))
    if problems:
        raise pytest.UsageError("test-case traceability (EVOL-053): collection refused —\n  " + "\n  ".join(problems))
