#!/bin/bash
# ============================================================================
# scripts/auto-tag.sh — SemVer Auto-Tagging from Conventional Commits
# ============================================================================
# Generated by Agent: SETUP | Framework: mi-AI-Factory
#
# Analyzes conventional commit messages since the last git tag and determines
# the next SemVer version. Can be run locally or as part of CI/CD pipelines.
#
# Usage:
#   ./scripts/auto-tag.sh                      # Dry-run (shows what would happen)
#   ./scripts/auto-tag.sh --apply              # Create and push tag
#   ./scripts/auto-tag.sh --apply --no-push    # Create tag locally only
#   ./scripts/auto-tag.sh --apply --ci         # CI mode: create, push, emit TAG=vX.Y.Z
#
# Conventional Commit → Version Bump Mapping:
#   BREAKING CHANGE: or feat!:              → MAJOR bump
#   feat:                                   → MINOR bump
#   fix:, docs:, refactor:, perf:, chore:  → PATCH bump
#
# Requirements: git
# ============================================================================

set -euo pipefail

# ── Colors ──
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ── Args ──
APPLY=false
PUSH=true
CI_MODE=false

for arg in "$@"; do
  case "$arg" in
    --apply)    APPLY=true ;;
    --no-push)  PUSH=false ;;
    --ci)       CI_MODE=true ;;
    --help|-h)
      echo "Usage: $0 [--apply] [--no-push] [--ci]"
      echo "  --apply    Create the tag (default: dry-run)"
      echo "  --no-push  Don't push the tag to origin"
      echo "  --ci       CI mode: emit TAG=vX.Y.Z for pipeline parsing"
      exit 0
      ;;
    *)
      echo -e "${RED}Unknown argument: $arg${NC}"
      exit 1
      ;;
  esac
done

# ── Get last version tag ──
# Filter to v* pattern only — defensive snapshot tags (pre-*, snapshot-*, etc.)
# are ignored so they don't break SemVer parsing.
LAST_TAG=$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null || echo "")
FIRST_RELEASE=false

if [ -z "$LAST_TAG" ]; then
  LAST_TAG="v0.0.0"
  FIRST_RELEASE=true
  echo -e "${YELLOW}📌 No previous tags found. Starting from v0.0.0${NC}"
else
  echo -e "${BLUE}📌 Last tag: ${LAST_TAG}${NC}"
fi

# ── Get commits since last tag ──
# Use %B (full commit message including body) to detect BREAKING CHANGE: in footers
if [ "$FIRST_RELEASE" = true ]; then
  COMMITS=$(git log --pretty=format:"%B" 2>/dev/null || echo "")
else
  COMMITS=$(git log "${LAST_TAG}..HEAD" --pretty=format:"%B" 2>/dev/null || echo "")
fi

if [ -z "$COMMITS" ]; then
  echo -e "${YELLOW}⚠️  No new commits since ${LAST_TAG}. Nothing to tag.${NC}"
  exit 0
fi

COMMIT_COUNT=$(echo "$COMMITS" | wc -l)
echo -e "${BLUE}📋 ${COMMIT_COUNT} commits since ${LAST_TAG}${NC}"

# ── Parse SemVer ──
VERSION="${LAST_TAG#v}"
MAJOR=$(echo "$VERSION" | cut -d. -f1)
MINOR=$(echo "$VERSION" | cut -d. -f2)
PATCH=$(echo "$VERSION" | cut -d. -f3)

# ── Determine bump type from commits ──
BUMP="patch"

if echo "$COMMITS" | grep -qiE "^feat!:|BREAKING CHANGE:"; then
  BUMP="major"
elif echo "$COMMITS" | grep -qiE "^feat(\(.*\))?:"; then
  BUMP="minor"
fi

# ── Governance-aware override ──
# After computing bump from commits, compare the RESULTING version against
# framework_version in governance manifest. If governance declares a higher
# version than what commits would produce, use governance version.
# This prevents silent under-bumping at ALL levels (MAJOR, MINOR, PATCH).
MANIFEST=".context/templates/setup/governance_versions.json"
GOV_OVERRIDE=false

if [ -f "$MANIFEST" ] && command -v python3 &>/dev/null; then
  GOV_VERSION=$(python3 -c "
import json
with open('${MANIFEST}') as f:
    print(json.load(f).get('framework_version', '0.0.0'))
" 2>/dev/null || echo "")

  if [ -n "$GOV_VERSION" ]; then
    GOV_MAJOR=$(echo "$GOV_VERSION" | cut -d. -f1)
    GOV_MINOR=$(echo "$GOV_VERSION" | cut -d. -f2)
    GOV_PATCH=$(echo "$GOV_VERSION" | cut -d. -f3)

    echo -e "${BLUE}📋 Governance framework_version: ${GOV_VERSION} (last tag: ${LAST_TAG})${NC}"
  fi
else
  echo -e "${BLUE}ℹ️  No governance manifest found, using commit-only heuristics${NC}"
fi

# ── Calculate new version from commits ──
case "$BUMP" in
  major)
    MAJOR=$((MAJOR + 1))
    MINOR=0
    PATCH=0
    ;;
  minor)
    MINOR=$((MINOR + 1))
    PATCH=0
    ;;
  patch)
    PATCH=$((PATCH + 1))
    ;;
esac

NEW_TAG="v${MAJOR}.${MINOR}.${PATCH}"

# ── Post-calculation governance comparison ──
# Compare computed version against governance. If governance is higher, override.
if [ -n "${GOV_VERSION:-}" ]; then
  COMPUTED_TAG="$NEW_TAG"

  # SemVer comparison: is GOV_VERSION > computed version?
  GOV_GT=false
  if [ "$GOV_MAJOR" -gt "$MAJOR" ]; then
    GOV_GT=true
  elif [ "$GOV_MAJOR" -eq "$MAJOR" ] && [ "$GOV_MINOR" -gt "$MINOR" ]; then
    GOV_GT=true
  elif [ "$GOV_MAJOR" -eq "$MAJOR" ] && [ "$GOV_MINOR" -eq "$MINOR" ] && [ "$GOV_PATCH" -gt "$PATCH" ]; then
    GOV_GT=true
  fi

  if [ "$GOV_GT" = true ]; then
    echo -e "${YELLOW}⚠️  Governance override: framework_version v${GOV_VERSION} > computed ${COMPUTED_TAG}${NC}"
    MAJOR="$GOV_MAJOR"
    MINOR="$GOV_MINOR"
    PATCH="$GOV_PATCH"
    NEW_TAG="v${MAJOR}.${MINOR}.${PATCH}"
    GOV_OVERRIDE=true

    # Determine effective bump type for logging
    COMPUTED_MAJOR=$(echo "${COMPUTED_TAG#v}" | cut -d. -f1)
    if [ "$GOV_MAJOR" -gt "$COMPUTED_MAJOR" ]; then
      BUMP="major"
    elif [ "$GOV_MINOR" -gt "$(echo "${COMPUTED_TAG#v}" | cut -d. -f2)" ]; then
      BUMP="minor"
    else
      BUMP="patch"
    fi
    echo -e "${YELLOW}   Override: ${COMPUTED_TAG} → ${NEW_TAG} (effective bump: ${BUMP})${NC}"
  else
    echo -e "${GREEN}✅ Governance alignment OK: framework v${GOV_VERSION} ≤ computed ${NEW_TAG}${NC}"
  fi
fi

echo -e "${GREEN}🏷️  Version bump: ${BUMP} → ${NEW_TAG}${NC}"
echo ""

# ── Show commits summary (SIGPIPE-safe: head can close pipe early) ──
echo "Commits included:"
if [ "$FIRST_RELEASE" = true ]; then
  git log --pretty=format:"  - %s (%h)" | head -20 || true
else
  git log "${LAST_TAG}..HEAD" --pretty=format:"  - %s (%h)" | head -20 || true
fi
echo ""

# ── Apply or dry-run ──
if [ "$APPLY" = true ]; then
  git tag -a "$NEW_TAG" -m "Release ${NEW_TAG} (${BUMP} bump)"
  echo -e "${GREEN}✅ Tag ${NEW_TAG} created${NC}"

  if [ "$PUSH" = true ]; then
    git push origin "$NEW_TAG"
    echo -e "${GREEN}✅ Tag ${NEW_TAG} pushed to origin${NC}"
  else
    echo -e "${YELLOW}⚠️  Tag created locally. Push with: git push origin ${NEW_TAG}${NC}"
  fi

  # CI mode: emit machine-parseable output for pipeline consumption
  if [ "$CI_MODE" = true ]; then
    echo "TAG=${NEW_TAG}"
    echo "BUMP=${BUMP}"
    echo "PREVIOUS=${LAST_TAG}"
  fi
else
  echo -e "${YELLOW}🔍 DRY-RUN: Would create tag ${NEW_TAG}${NC}"
  echo -e "${YELLOW}   Run with --apply to create the tag${NC}"

  if [ "$CI_MODE" = true ]; then
    echo "TAG=${NEW_TAG}"
    echo "BUMP=${BUMP}"
    echo "PREVIOUS=${LAST_TAG}"
    echo "DRY_RUN=true"
  fi
fi
