#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# factory-sync.sh — Framework Governance Sync Tool (Claude Code Edition)
# ═══════════════════════════════════════════════════════════════════════════════
# Synchronizes framework governance files from the framework source to a target
# project. Works on both greenfield (pre-materialization) and materialized
# projects. For framework-owned files the template-variant under
# `.context/templates/setup/scripts/**` is preferred over the meta variant to
# avoid propagating meta-only constructs (e.g. auto-tag governance-aware
# override) to downstream projects.
#
# WHAT IT SYNCS (framework-owned, overwritten unless --preserve-local):
#   .claude/commands/*.md
#   .claude/instructions/Factory-*.instructions.md
#   .claude/skills/factory-*/  (entire tree: SKILL.md + references/ + scripts/ + assets/)
#   .claude/hooks/*.sh
#   scripts/auto-tag.sh, security-scan.sh, validate-governance.sh
#   scripts/governance-onprompt.sh, governance-oncompact.sh, governance-onedit.sh
#   scripts/install-hooks.sh, factory-sync.sh, project_summarization.py
#   scripts/hooks/{commit-msg,pre-commit,pre-push}
#   .context/templates/ (full tree — consumed by SETUP --upgrade)
#
# WHAT IT DOES NOT TOUCH (project-owned):
#   CLAUDE.md (root)                — owned by SETUP --generate/--upgrade from template
#   docs/                            — constitution, rules, setup, specs, project_log
#   src/, tests/, config/, infra/, contracts/, migrations/
#   .context/governance_snapshot.md  — regenerated by --upgrade
#   .claude/settings.json            — project-specific permissions/hook wiring
#
# USAGE:
#   $FRAMEWORK/scripts/factory-sync.sh /path/to/target-project
#
#   Flags:
#     --dry-run          Show what would change without modifying files
#     --verbose          Show detailed file-by-file output
#     --force            Skip confirmation prompt
#     --greenfield       Force pre-materialization mode even when docs/spec/ has feature dirs (override the "instantiated project with missing setup.md" guard)
#     --preserve-local   Do NOT overwrite targets that differ from source (report only)
#
# ═══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

# ── Colors ──
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# ── Globals ──
DRY_RUN=false
VERBOSE=false
FORCE=false
GREENFIELD=false
PRESERVE_LOCAL=false
ADDED=0
UPDATED=0
UNCHANGED=0
DELETED=0
ERRORS=0
PRESERVED=0
HAS_SKILL_ORPHANS=false
HAS_ORPHANS=false

# ── Resolve framework source path ──
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Parse arguments ──
TARGET_PROJECT=""
for arg in "$@"; do
  case "$arg" in
    --dry-run)         DRY_RUN=true ;;
    --verbose)         VERBOSE=true ;;
    --force)           FORCE=true ;;
    --greenfield)      GREENFIELD=true ;;
    --preserve-local)  PRESERVE_LOCAL=true ;;
    -*)                echo -e "${RED}Unknown option: $arg${NC}"; exit 1 ;;
    *)                 TARGET_PROJECT="$arg" ;;
  esac
done

if [[ -z "$TARGET_PROJECT" ]]; then
  echo -e "${RED}Usage: factory-sync.sh <target-project-path> [--dry-run] [--verbose] [--force] [--greenfield] [--preserve-local]${NC}"
  exit 1
fi

# Resolve to absolute path
TARGET_PROJECT="$(cd "$TARGET_PROJECT" && pwd)"

# ── Validate paths ──
if [[ ! -f "$FRAMEWORK_ROOT/CLAUDE.md" ]] || [[ ! -d "$FRAMEWORK_ROOT/.context/templates/setup" ]]; then
  echo -e "${RED}ERROR: Framework root not found at: $FRAMEWORK_ROOT${NC}"
  echo "Expected CLAUDE.md + .context/templates/setup/ in framework directory."
  exit 1
fi

IS_GREENFIELD=false
# Detection contract:
#   docs/setup.md present  → fully instantiated (post /setup --generate). Sync proceeds normally.
#   docs/setup.md absent   → pre-instantiation. Two sub-cases:
#     (a) docs/spec/ holds feature directories → suspicious (setup.md lost while spec
#         work was already in progress). ERROR unless --greenfield.
#     (b) otherwise → legitimate "framework-installed but instantiation-pending" state.
#         Auto-greenfield. Common case: a previous factory-sync seeded skills/hooks/
#         CLAUDE.md on a target before /setup ran (Nexus-Tech-Link is canonical).
if [[ ! -f "$TARGET_PROJECT/docs/setup.md" ]]; then
  HAS_SPEC_DIRS=false
  if [[ -d "$TARGET_PROJECT/docs/spec" ]] && [[ -n "$(find "$TARGET_PROJECT/docs/spec" -mindepth 1 -maxdepth 1 -type d -print -quit 2>/dev/null)" ]]; then
    HAS_SPEC_DIRS=true
  fi

  if $GREENFIELD || ! $HAS_SPEC_DIRS; then
    IS_GREENFIELD=true
  else
    echo -e "${RED}ERROR: Target has docs/spec/ feature directories but no docs/setup.md${NC}"
    echo "This indicates an instantiated project where setup.md was lost while spec work was already in progress — investigate before sync."
    echo "Pass --greenfield to force pre-materialization mode."
    exit 1
  fi
fi

if [[ "$FRAMEWORK_ROOT" == "$TARGET_PROJECT" ]]; then
  echo -e "${RED}ERROR: Source and target are the same directory.${NC}"
  exit 1
fi

# ── Read versions ──
FW_VERSION=$(grep -o '"framework_version": "[^"]*"' "$FRAMEWORK_ROOT/.context/templates/setup/governance_versions.json" | head -1 | cut -d'"' -f4)
if $IS_GREENFIELD; then
  PROJ_VERSION="greenfield"
elif [[ -f "$TARGET_PROJECT/docs/project_log/governance_versions.json" ]]; then
  PROJ_VERSION=$(grep -o '"framework_version": "[^"]*"' "$TARGET_PROJECT/docs/project_log/governance_versions.json" | head -1 | cut -d'"' -f4)
else
  PROJ_VERSION="unknown"
fi

# ── Header ──
echo ""
echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}  Factory Governance Sync (Claude Code)${NC}"
echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"
echo -e "  Framework:  ${CYAN}$FRAMEWORK_ROOT${NC}"
echo -e "  Target:     ${CYAN}$TARGET_PROJECT${NC}"
echo -e "  FW version: ${GREEN}$FW_VERSION${NC}  <-  Project: ${YELLOW}$PROJ_VERSION${NC}"
if $IS_GREENFIELD; then
  echo -e "  ${YELLOW}⚠ Greenfield mode: target has no docs/setup.md yet. Sync will seed the working tree; run /setup --init afterwards.${NC}"
fi
if $PRESERVE_LOCAL; then
  echo -e "  Mode:       ${CYAN}PRESERVE-LOCAL (targets that differ will NOT be overwritten)${NC}"
fi
if $DRY_RUN; then
  echo -e "  Mode:       ${YELLOW}DRY RUN (no files will be modified)${NC}"
fi
echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"
echo ""

# ── Sync helper ──
sync_file() {
  local src="$1"
  local dst="$2"
  local rel_path="${dst#$TARGET_PROJECT/}"

  if [[ ! -f "$src" ]]; then
    if $VERBOSE; then
      echo -e "  ${RED}SKIP${NC} $rel_path (source missing)"
    fi
    return
  fi

  # Guard: skip empty source files to avoid wiping target implementations
  if [[ ! -s "$src" ]]; then
    if $VERBOSE; then
      echo -e "  ${YELLOW}SKIP${NC} $rel_path (source is empty)"
    fi
    return
  fi

  if [[ -f "$dst" ]]; then
    # Compare files
    if cmp -s "$src" "$dst"; then
      UNCHANGED=$((UNCHANGED + 1))
      if $VERBOSE; then
        echo -e "  ${BLUE}=${NC}  $rel_path"
      fi
      return
    fi
    # File differs — either update or preserve based on flag
    if $PRESERVE_LOCAL; then
      PRESERVED=$((PRESERVED + 1))
      echo -e "  ${CYAN}◆${NC}  $rel_path ${CYAN}(local mod preserved — run without --preserve-local to overwrite)${NC}"
      return
    fi
    if ! $DRY_RUN; then
      mkdir -p "$(dirname "$dst")"
      cp "$src" "$dst"
    fi
    UPDATED=$((UPDATED + 1))
    echo -e "  ${YELLOW}~${NC}  $rel_path"
  else
    # New file
    if ! $DRY_RUN; then
      mkdir -p "$(dirname "$dst")"
      cp "$src" "$dst"
    fi
    ADDED=$((ADDED + 1))
    echo -e "  ${GREEN}+${NC}  $rel_path"
  fi
}

# Sync a directory of files matching a pattern
sync_dir() {
  local src_dir="$1"
  local dst_dir="$2"
  local pattern="${3:-*}"

  if [[ ! -d "$src_dir" ]]; then
    return
  fi

  for src_file in "$src_dir"/$pattern; do
    [[ -f "$src_file" ]] || continue
    local filename
    filename="$(basename "$src_file")"
    sync_file "$src_file" "$dst_dir/$filename"
  done
}

# Sync skill directories — copies the FULL tree of each factory-* skill
# (SKILL.md + any references/, scripts/, assets/, README.md, etc.).
# Multi-file skills (e.g. factory-pr-review) carry runtime artefacts beyond
# SKILL.md; SKILL-only sync would leave them inert.
sync_skills() {
  local src_dir="$1"
  local dst_dir="$2"

  for skill_dir in "$src_dir"/factory-*/; do
    [[ -d "$skill_dir" ]] || continue
    # Strip trailing slash from glob expansion so sync_tree's
    # ${src_file#$src_root/} relative-path computation works correctly.
    skill_dir="${skill_dir%/}"
    local skill_name
    skill_name="$(basename "$skill_dir")"
    sync_tree "$skill_dir" "$dst_dir/$skill_name"
  done
}

# Sync an entire directory tree recursively
sync_tree() {
  local src_root="$1"
  local dst_root="$2"

  [[ -d "$src_root" ]] || return

  while IFS= read -r -d '' src_file; do
    local rel="${src_file#$src_root/}"
    sync_file "$src_file" "$dst_root/$rel"
  done < <(find "$src_root" -type f -print0 | sort -z)
}

# Detect orphan files in a tree (recursive)
detect_tree_orphans() {
  local src_root="$1"
  local dst_root="$2"

  [[ -d "$dst_root" ]] || return

  while IFS= read -r -d '' dst_file; do
    local rel="${dst_file#$dst_root/}"
    if [[ ! -f "$src_root/$rel" ]]; then
      local rel_path="${dst_file#$TARGET_PROJECT/}"
      echo -e "  ${RED}!${NC}  $rel_path ${RED}(orphan -- not in framework)${NC}"
      DELETED=$((DELETED + 1))
    fi
  done < <(find "$dst_root" -type f -print0 | sort -z)
}

# Detect orphan files in target that no longer exist in framework
detect_orphans() {
  local src_dir="$1"
  local dst_dir="$2"
  local pattern="${3:-*}"
  local prefix="${4:-}"

  [[ -d "$dst_dir" ]] || return

  for dst_file in "$dst_dir"/$pattern; do
    [[ -f "$dst_file" ]] || continue
    local filename
    filename="$(basename "$dst_file")"

    # Only check Factory-prefixed files (framework-owned)
    if [[ -n "$prefix" && "$filename" != "$prefix"* ]]; then
      continue
    fi

    if [[ ! -f "$src_dir/$filename" ]]; then
      local rel_path="${dst_file#$TARGET_PROJECT/}"
      echo -e "  ${RED}!${NC}  $rel_path ${RED}(orphan -- exists in project but not in framework)${NC}"
      DELETED=$((DELETED + 1))
    fi
  done
}

# ── Confirmation ──
if ! $DRY_RUN && ! $FORCE; then
  echo -e "This will ${BOLD}overwrite${NC} framework-owned governance files in the target project."
  echo -e "Project-specific files (docs/, src/, config/, etc.) will ${GREEN}NOT${NC} be touched."
  echo ""
  read -rp "Continue? [y/N] " confirm
  if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
    echo "Aborted."
    exit 0
  fi
  echo ""
fi

# ═══════════════════════════════════════════════════════════════════════════════
# SYNC CATEGORIES
# ═══════════════════════════════════════════════════════════════════════════════

echo -e "${BOLD}[1/7] CLAUDE.md (Root Governance — SKIPPED by factory-sync)${NC}"
echo -e "  ${CYAN}ℹ Materialized-project CLAUDE.md is managed by SETUP --generate / --upgrade"
echo -e "    from .context/templates/setup/claude/CLAUDE.md (EVOL-018).${NC}"
echo ""

echo -e "${BOLD}[2/7] Commands (.claude/commands/)${NC}"
sync_dir "$FRAMEWORK_ROOT/.claude/commands" "$TARGET_PROJECT/.claude/commands" "*.md"
echo ""

echo -e "${BOLD}[3/7] Instructions (.claude/instructions/)${NC}"
sync_dir "$FRAMEWORK_ROOT/.claude/instructions" "$TARGET_PROJECT/.claude/instructions" "Factory-*.instructions.md"
detect_orphans "$FRAMEWORK_ROOT/.claude/instructions" "$TARGET_PROJECT/.claude/instructions" "Factory-*.instructions.md" "Factory-"
echo ""

echo -e "${BOLD}[4/7] Skills (.claude/skills/)${NC}"
sync_skills "$FRAMEWORK_ROOT/.claude/skills" "$TARGET_PROJECT/.claude/skills"
# Check for orphan skill directories
HAS_SKILL_ORPHANS=false
if [[ -d "$TARGET_PROJECT/.claude/skills" ]]; then
  for dst_skill in "$TARGET_PROJECT/.claude/skills/"factory-*/; do
    [[ -d "$dst_skill" ]] || continue
    skill_name="$(basename "$dst_skill")"
    if [[ ! -d "$FRAMEWORK_ROOT/.claude/skills/$skill_name" ]]; then
      echo -e "  ${RED}!${NC}  .claude/skills/$skill_name/ ${YELLOW}(not in framework -- possible rename or removal)${NC}"
      HAS_SKILL_ORPHANS=true
      DELETED=$((DELETED + 1))
    fi
  done
fi
echo ""

echo -e "${BOLD}[5/7] Claude Code Hooks (.claude/hooks/)${NC}"
sync_dir "$FRAMEWORK_ROOT/.claude/hooks" "$TARGET_PROJECT/.claude/hooks" "*.sh"
detect_orphans "$FRAMEWORK_ROOT/.claude/hooks" "$TARGET_PROJECT/.claude/hooks" "*.sh" "check-"
echo ""

echo -e "${BOLD}[6/7] Base Scripts (scripts/)${NC}"
# Framework-owned scripts. For each, prefer the template-variant under
# .context/templates/setup/scripts/ over the meta variant at $FRAMEWORK_ROOT/scripts/.
# Rationale: some scripts (e.g. auto-tag.sh) have a meta-only variant that must NOT
# propagate to downstream projects (e.g. governance-aware override in auto-tag reads
# the FRAMEWORK manifest; downstream projects have their own manifest).
resolve_script_src() {
  local name="$1"
  local tpl="$FRAMEWORK_ROOT/.context/templates/setup/scripts/$name"
  local meta="$FRAMEWORK_ROOT/scripts/$name"
  if [[ -f "$tpl" ]]; then
    echo "$tpl"
  else
    echo "$meta"
  fi
}
for script in auto-tag.sh install-hooks.sh security-scan.sh validate-governance.sh governance-onprompt.sh governance-oncompact.sh governance-onedit.sh generate-governance-snapshot.sh check-inventory-drift.sh check-applicability-frontmatter.sh check-iteration-id-format.sh migrate-iteration-frontmatter.sh project_summarization.py check-adr-constitution-sync.sh check-complexity-config.sh reconcile_inventory.py check-inventory-freshness.py; do
  sync_file "$(resolve_script_src "$script")" "$TARGET_PROJECT/scripts/$script"
done
# factory-sync.sh exists only in framework_core (no template variant by design).
sync_file "$FRAMEWORK_ROOT/scripts/factory-sync.sh" "$TARGET_PROJECT/scripts/factory-sync.sh"
# Git hooks — template-variant preferred when present.
for hook in commit-msg pre-commit pre-push; do
  tpl="$FRAMEWORK_ROOT/.context/templates/setup/scripts/hooks/$hook"
  src="$([[ -f "$tpl" ]] && echo "$tpl" || echo "$FRAMEWORK_ROOT/scripts/hooks/$hook")"
  sync_file "$src" "$TARGET_PROJECT/scripts/hooks/$hook"
done
echo ""

echo -e "${BOLD}[7/7] Templates (.context/templates/)${NC}"
sync_tree "$FRAMEWORK_ROOT/.context/templates" "$TARGET_PROJECT/.context/templates"
detect_tree_orphans "$FRAMEWORK_ROOT/.context/templates" "$TARGET_PROJECT/.context/templates"
echo ""

# ═══════════════════════════════════════════════════════════════════════════════
# ORPHAN DETECTION — non-framework files in framework directories
# ═══════════════════════════════════════════════════════════════════════════════

echo -e "${BOLD}Orphan Check${NC}"

# Check for instruction files in target that aren't in framework
for dst_file in "$TARGET_PROJECT/.claude/instructions/"*.instructions.md; do
  [[ -f "$dst_file" ]] || continue
  filename="$(basename "$dst_file")"
  # Only check Factory-prefixed
  [[ "$filename" == Factory-* ]] || continue
  if [[ ! -f "$FRAMEWORK_ROOT/.claude/instructions/$filename" ]]; then
    echo -e "  ${RED}!${NC}  .claude/instructions/$filename ${YELLOW}(not in framework -- possible rename or removal)${NC}"
    HAS_ORPHANS=true
    DELETED=$((DELETED + 1))
  fi
done

# DELETED is the single source of truth: all orphan-detection paths (the
# manual instructions loop above, detect_orphans() in instructions/hooks, and
# detect_tree_orphans() in templates) bump DELETED. The per-category flags
# HAS_ORPHANS / HAS_SKILL_ORPHANS are retained only to suppress per-loop
# redundant messaging; the summary below keys off DELETED directly.
if [[ $DELETED -eq 0 ]]; then
  echo -e "  ${GREEN}No orphans detected${NC}"
fi
echo ""

# ═══════════════════════════════════════════════════════════════════════════════
# SUMMARY
# ═══════════════════════════════════════════════════════════════════════════════

echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"
echo -e "  ${GREEN}Added:${NC}     $ADDED"
echo -e "  ${YELLOW}Updated:${NC}   $UPDATED"
echo -e "  ${BLUE}Unchanged:${NC} $UNCHANGED"
if [[ $PRESERVED -gt 0 ]]; then
  echo -e "  ${CYAN}Preserved:${NC} $PRESERVED (targets differ — not overwritten due to --preserve-local)"
fi
if [[ $DELETED -gt 0 ]]; then
  echo -e "  ${RED}Orphans:${NC}   $DELETED (review manually)"
fi
if [[ $ERRORS -gt 0 ]]; then
  echo -e "  ${RED}Errors:${NC}    $ERRORS"
fi
echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"

if $DRY_RUN; then
  echo -e "${YELLOW}DRY RUN — no files were modified. Run without --dry-run to apply.${NC}"
fi

exit 0
