#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# factory-sync.sh — Framework Governance Sync Tool (Claude Code Edition)
# ═══════════════════════════════════════════════════════════════════════════════
# Synchronizes framework governance files (commands, instructions, skills,
# scripts, templates, CLAUDE.md) from the framework source to a target project.
#
# WHAT IT SYNCS (framework-owned, overwritten):
#   CLAUDE.md
#   .claude/commands/*.md
#   .claude/instructions/Factory-*.instructions.md
#   .claude/skills/Factory-*/SKILL.md
#   scripts/{auto-tag,install-hooks,security-scan,validate-governance}.sh
#   scripts/hooks/{commit-msg,pre-commit,pre-push}
#   scripts/project_summarization.py
#   .context/templates/ (full tree — used by SETUP --upgrade)
#
# WHAT IT DOES NOT TOUCH (project-owned):
#   docs/  (constitution, rules, setup, specs — materialized)
#   src/, tests/, config/, infra/, contracts/, migrations/
#   .context/governance_snapshot.md (regenerated by --upgrade)
#   .claude/settings.json (project-specific permissions)
#   Scripts generated by SETUP --generate (check-structure, lint-format, etc.)
#
# USAGE:
#   # Option A: explicit paths
#   /path/to/mi-AI-Factory-for-Claude/scripts/factory-sync.sh /path/to/target-project
#
#   # Option B: with FACTORY_FRAMEWORK_PATH env var
#   export FACTORY_FRAMEWORK_PATH="/path/to/mi-AI-Factory-for-Claude"
#   $FACTORY_FRAMEWORK_PATH/scripts/factory-sync.sh /path/to/target-project
#
#   # Option C: from within the target project
#   $FACTORY_FRAMEWORK_PATH/scripts/factory-sync.sh .
#
#   # Flags:
#   --dry-run    Show what would change without modifying files
#   --verbose    Show detailed file-by-file output
#   --force      Skip confirmation prompt
#
# ═══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

# ── Colors ──
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# ── Globals ──
DRY_RUN=false
VERBOSE=false
FORCE=false
ADDED=0
UPDATED=0
UNCHANGED=0
DELETED=0
ERRORS=0

# ── Resolve framework source path ──
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Parse arguments ──
TARGET_PROJECT=""
for arg in "$@"; do
  case "$arg" in
    --dry-run)  DRY_RUN=true ;;
    --verbose)  VERBOSE=true ;;
    --force)    FORCE=true ;;
    -*)         echo -e "${RED}Unknown option: $arg${NC}"; exit 1 ;;
    *)          TARGET_PROJECT="$arg" ;;
  esac
done

if [[ -z "$TARGET_PROJECT" ]]; then
  echo -e "${RED}Usage: factory-sync.sh <target-project-path> [--dry-run] [--verbose] [--force]${NC}"
  exit 1
fi

# Resolve to absolute path
TARGET_PROJECT="$(cd "$TARGET_PROJECT" && pwd)"

# ── Validate paths ──
if [[ ! -f "$FRAMEWORK_ROOT/CLAUDE.md" ]]; then
  echo -e "${RED}ERROR: Framework root not found at: $FRAMEWORK_ROOT${NC}"
  echo "Expected CLAUDE.md in framework directory."
  exit 1
fi

if [[ ! -f "$TARGET_PROJECT/docs/setup.md" ]]; then
  echo -e "${RED}ERROR: Target does not look like a Factory project: $TARGET_PROJECT${NC}"
  echo "Expected docs/setup.md in project directory."
  exit 1
fi

if [[ "$FRAMEWORK_ROOT" == "$TARGET_PROJECT" ]]; then
  echo -e "${RED}ERROR: Source and target are the same directory.${NC}"
  exit 1
fi

# ── Read versions ──
FW_VERSION=$(grep -o '"framework_version": "[^"]*"' "$FRAMEWORK_ROOT/.context/templates/setup/governance_versions.json" | head -1 | cut -d'"' -f4)
PROJ_VERSION="unknown"
if [[ -f "$TARGET_PROJECT/docs/project_log/governance_versions.json" ]]; then
  PROJ_VERSION=$(grep -o '"framework_version": "[^"]*"' "$TARGET_PROJECT/docs/project_log/governance_versions.json" | head -1 | cut -d'"' -f4)
fi

# ── Header ──
echo ""
echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}  Factory Governance Sync (Claude Code)${NC}"
echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"
echo -e "  Framework:  ${CYAN}$FRAMEWORK_ROOT${NC}"
echo -e "  Target:     ${CYAN}$TARGET_PROJECT${NC}"
echo -e "  FW version: ${GREEN}$FW_VERSION${NC}  <-  Project: ${YELLOW}$PROJ_VERSION${NC}"
if $DRY_RUN; then
  echo -e "  Mode:       ${YELLOW}DRY RUN (no files will be modified)${NC}"
fi
echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"
echo ""

# ── Sync helper ──
sync_file() {
  local src="$1"
  local dst="$2"
  local rel_path="${dst#$TARGET_PROJECT/}"

  if [[ ! -f "$src" ]]; then
    if $VERBOSE; then
      echo -e "  ${RED}SKIP${NC} $rel_path (source missing)"
    fi
    return
  fi

  # Guard: skip empty source files to avoid wiping target implementations
  if [[ ! -s "$src" ]]; then
    if $VERBOSE; then
      echo -e "  ${YELLOW}SKIP${NC} $rel_path (source is empty)"
    fi
    return
  fi

  if [[ -f "$dst" ]]; then
    # Compare files
    if cmp -s "$src" "$dst"; then
      UNCHANGED=$((UNCHANGED + 1))
      if $VERBOSE; then
        echo -e "  ${BLUE}=${NC}  $rel_path"
      fi
      return
    fi
    # File differs — update
    if ! $DRY_RUN; then
      mkdir -p "$(dirname "$dst")"
      cp "$src" "$dst"
    fi
    UPDATED=$((UPDATED + 1))
    echo -e "  ${YELLOW}~${NC}  $rel_path"
  else
    # New file
    if ! $DRY_RUN; then
      mkdir -p "$(dirname "$dst")"
      cp "$src" "$dst"
    fi
    ADDED=$((ADDED + 1))
    echo -e "  ${GREEN}+${NC}  $rel_path"
  fi
}

# Sync a directory of files matching a pattern
sync_dir() {
  local src_dir="$1"
  local dst_dir="$2"
  local pattern="${3:-*}"

  if [[ ! -d "$src_dir" ]]; then
    return
  fi

  for src_file in "$src_dir"/$pattern; do
    [[ -f "$src_file" ]] || continue
    local filename
    filename="$(basename "$src_file")"
    sync_file "$src_file" "$dst_dir/$filename"
  done
}

# Sync skill directories (each has SKILL.md inside)
sync_skills() {
  local src_dir="$1"
  local dst_dir="$2"

  for skill_dir in "$src_dir"/Factory-*/; do
    [[ -d "$skill_dir" ]] || continue
    local skill_name
    skill_name="$(basename "$skill_dir")"
    local src_skill="$skill_dir/SKILL.md"
    local dst_skill="$dst_dir/$skill_name/SKILL.md"
    sync_file "$src_skill" "$dst_skill"
  done
}

# Sync an entire directory tree recursively
sync_tree() {
  local src_root="$1"
  local dst_root="$2"

  [[ -d "$src_root" ]] || return

  while IFS= read -r -d '' src_file; do
    local rel="${src_file#$src_root/}"
    sync_file "$src_file" "$dst_root/$rel"
  done < <(find "$src_root" -type f -print0 | sort -z)
}

# Detect orphan files in a tree (recursive)
detect_tree_orphans() {
  local src_root="$1"
  local dst_root="$2"

  [[ -d "$dst_root" ]] || return

  while IFS= read -r -d '' dst_file; do
    local rel="${dst_file#$dst_root/}"
    if [[ ! -f "$src_root/$rel" ]]; then
      local rel_path="${dst_file#$TARGET_PROJECT/}"
      echo -e "  ${RED}!${NC}  $rel_path ${RED}(orphan -- not in framework)${NC}"
      DELETED=$((DELETED + 1))
    fi
  done < <(find "$dst_root" -type f -print0 | sort -z)
}

# Detect orphan files in target that no longer exist in framework
detect_orphans() {
  local src_dir="$1"
  local dst_dir="$2"
  local pattern="${3:-*}"
  local prefix="${4:-}"

  [[ -d "$dst_dir" ]] || return

  for dst_file in "$dst_dir"/$pattern; do
    [[ -f "$dst_file" ]] || continue
    local filename
    filename="$(basename "$dst_file")"

    # Only check Factory-prefixed files (framework-owned)
    if [[ -n "$prefix" && "$filename" != "$prefix"* ]]; then
      continue
    fi

    if [[ ! -f "$src_dir/$filename" ]]; then
      local rel_path="${dst_file#$TARGET_PROJECT/}"
      echo -e "  ${RED}!${NC}  $rel_path ${RED}(orphan -- exists in project but not in framework)${NC}"
      DELETED=$((DELETED + 1))
    fi
  done
}

# ── Confirmation ──
if ! $DRY_RUN && ! $FORCE; then
  echo -e "This will ${BOLD}overwrite${NC} framework-owned governance files in the target project."
  echo -e "Project-specific files (docs/, src/, config/, etc.) will ${GREEN}NOT${NC} be touched."
  echo ""
  read -rp "Continue? [y/N] " confirm
  if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
    echo "Aborted."
    exit 0
  fi
  echo ""
fi

# ═══════════════════════════════════════════════════════════════════════════════
# SYNC CATEGORIES
# ═══════════════════════════════════════════════════════════════════════════════

echo -e "${BOLD}[1/6] CLAUDE.md (Root Governance)${NC}"
sync_file "$FRAMEWORK_ROOT/CLAUDE.md" "$TARGET_PROJECT/CLAUDE.md"
echo ""

echo -e "${BOLD}[2/6] Commands (.claude/commands/)${NC}"
sync_dir "$FRAMEWORK_ROOT/.claude/commands" "$TARGET_PROJECT/.claude/commands" "*.md"
echo ""

echo -e "${BOLD}[3/6] Instructions (.claude/instructions/)${NC}"
sync_dir "$FRAMEWORK_ROOT/.claude/instructions" "$TARGET_PROJECT/.claude/instructions" "Factory-*.instructions.md"
detect_orphans "$FRAMEWORK_ROOT/.claude/instructions" "$TARGET_PROJECT/.claude/instructions" "Factory-*.instructions.md" "Factory-"
echo ""

echo -e "${BOLD}[4/6] Skills (.claude/skills/)${NC}"
sync_skills "$FRAMEWORK_ROOT/.claude/skills" "$TARGET_PROJECT/.claude/skills"
# Check for orphan skill directories
HAS_SKILL_ORPHANS=false
if [[ -d "$TARGET_PROJECT/.claude/skills" ]]; then
  for dst_skill in "$TARGET_PROJECT/.claude/skills/"Factory-*/; do
    [[ -d "$dst_skill" ]] || continue
    skill_name="$(basename "$dst_skill")"
    if [[ ! -d "$FRAMEWORK_ROOT/.claude/skills/$skill_name" ]]; then
      echo -e "  ${RED}!${NC}  .claude/skills/$skill_name/ ${YELLOW}(not in framework -- possible rename or removal)${NC}"
      HAS_SKILL_ORPHANS=true
      DELETED=$((DELETED + 1))
    fi
  done
fi
echo ""

echo -e "${BOLD}[5/6] Base Scripts (scripts/)${NC}"
# Framework-owned scripts only
for script in auto-tag.sh install-hooks.sh security-scan.sh validate-governance.sh factory-sync.sh project_summarization.py; do
  sync_file "$FRAMEWORK_ROOT/scripts/$script" "$TARGET_PROJECT/scripts/$script"
done
# Hooks
for hook in commit-msg pre-commit pre-push; do
  sync_file "$FRAMEWORK_ROOT/scripts/hooks/$hook" "$TARGET_PROJECT/scripts/hooks/$hook"
done
echo ""

echo -e "${BOLD}[6/6] Templates (.context/templates/)${NC}"
sync_tree "$FRAMEWORK_ROOT/.context/templates" "$TARGET_PROJECT/.context/templates"
detect_tree_orphans "$FRAMEWORK_ROOT/.context/templates" "$TARGET_PROJECT/.context/templates"
echo ""

# ═══════════════════════════════════════════════════════════════════════════════
# ORPHAN DETECTION — non-framework files in framework directories
# ═══════════════════════════════════════════════════════════════════════════════

echo -e "${BOLD}Orphan Check${NC}"
HAS_ORPHANS=false

# Check for instruction files in target that aren't in framework
for dst_file in "$TARGET_PROJECT/.claude/instructions/"*.instructions.md; do
  [[ -f "$dst_file" ]] || continue
  filename="$(basename "$dst_file")"
  # Only check Factory-prefixed
  [[ "$filename" == Factory-* ]] || continue
  if [[ ! -f "$FRAMEWORK_ROOT/.claude/instructions/$filename" ]]; then
    echo -e "  ${RED}!${NC}  .claude/instructions/$filename ${YELLOW}(not in framework -- possible rename or removal)${NC}"
    HAS_ORPHANS=true
    DELETED=$((DELETED + 1))
  fi
done

if ! $HAS_ORPHANS && ! $HAS_SKILL_ORPHANS; then
  echo -e "  ${GREEN}No orphans detected${NC}"
fi
echo ""

# ═══════════════════════════════════════════════════════════════════════════════
# SUMMARY
# ═══════════════════════════════════════════════════════════════════════════════

echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"
echo -e "  ${GREEN}Added:${NC}     $ADDED"
echo -e "  ${YELLOW}Updated:${NC}   $UPDATED"
echo -e "  ${BLUE}Unchanged:${NC} $UNCHANGED"
if [[ $DELETED -gt 0 ]]; then
  echo -e "  ${RED}Orphans:${NC}   $DELETED (review manually)"
fi
if [[ $ERRORS -gt 0 ]]; then
  echo -e "  ${RED}Errors:${NC}    $ERRORS"
fi
echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"

if $DRY_RUN; then
  echo -e "${YELLOW}DRY RUN — no files were modified. Run without --dry-run to apply.${NC}"
fi

exit 0
