#!/usr/bin/env python3
# Generated by Phase: IMPLEMENT | Feature: EVOL-043
"""gate — the framework's one reader. Every hook, gate and pre-flight asks it; none re-derives.

  gate.py [--repo DIR] key <dotted> [--required]   print a config key (config/quality.json); fail-closed with --required
  gate.py context                                  meta | downstream
  gate.py laws [--json] [--parity]                 the law index (universal + project); --parity checks every body
  gate.py law-sentences --file F                   `ID<TAB>sentence` per law of a governance source (ceremony gate)
  gate.py applicable [--phase P] [--scope S] [--change-type T] [--command C] [--agent A] [--framework F…]
                     [--paths p…] [--format json|rollcall] [--feature ID]
  gate.py digest --paths p… [--budget N]           the slice of law governing paths, within budget (bytes)
  gate.py deliver --path p [--session SID] | --hook-json    PreToolUse envelope (additionalContext), deduped per session
  gate.py snapshot-sections [--profile lite|full]  stack config + rules manifest + law index + families (+ bodies)
  gate.py budget                                   run every producer at worst case; exit 1 on overflow, dead/absent producer or missing key
  gate.py retired-terms                            the retired-vocabulary ratchet; exit 1 on a hit
  gate.py certify --subject diff|tree [--base B] [--branch B] [--paths p…] [--json]   the certifies: block a verdict embeds (paths + hash); diff base = gate.py diff-base
  gate.py currency [--base B] [--branch B]         the push's verdict artefacts still certify their files; exit 1 stale/missing/unknown branch · 2 could not judge
  gate.py manifest-parity                          frontmatter version == manifest version for every governed file; exit 1 on drift
  gate.py branch-class [--branch B] [--protected] [--json]   protected · sub-increment · train · increment · feature · fix · docs · chore · epic · unknown
  gate.py diff-base [--branch B]                   the ONE diff base (sub-increment → its train; else the default base branch); exit 1 on an unknown name
  gate.py surface [--base B] [--branch B] [--json] files + lines of base...HEAD vs surface.ceiling_*; exit 1 over the ceiling without a Surface-Escape trailer
  gate.py profile [--branch B] [--json]            the gate profile this push owes (delivery_mode × branch class → light | full, fail-closed to full)
  gate.py profile --run [--control-point push|ci] [--base B] [--branch B] [--json]   run every script member of the profile, all-report; exit 1 any red · 2 a member could not run
  gate.py one-definition                           hooks / workflows / preflight keep no branch list, mode read or mode override; exit 1 on a finding
  gate.py runtime-surface [--json]                 parity: every path a deploying job or its scripts read is on surface.runtime_surface, a hard exclusion or a declared read; exit 1 on a finding
  gate.py runtime-surface --changed [--base B]     did base...HEAD touch the runtime surface (or a hard exclusion)? exit 0 touched · 1 untouched (the machinery may skip) · 2 could not judge

Exit: 0 ok · 1 gate red · 2 the tool could not do its job (plain language, LAW-08) · 3 the reader itself is missing or broken (governance not delivered).
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
try:
    from gates import branch as branch_mod, budget as budget_mod, coherence, corpus, profile as profile_mod, retired, runtime  # noqa: E402
    from gates.common import GateFault, context, key, repo_root  # noqa: E402
except Exception as e:  # missing OR broken package (SyntaxError included) — it ships next to this file (SETUP / factory-sync)
    print(f"gate: the scripts/gates package is missing or broken ({type(e).__name__}: {e}) — re-run SETUP --generate or factory-sync.sh", file=sys.stderr)
    sys.exit(3)   # 3 = the reader itself is not delivered: hooks treat it as governance missing (block), never as one member's fault


def cmd_key(repo, a):
    v = key(repo, a.dotted, required=a.required)
    print(json.dumps(v) if not isinstance(v, str) else v)
    return 0


def cmd_laws(repo, a):
    if a.parity:
        problems = corpus.parity(repo)
        print("\n".join(problems) if problems else "laws --parity: ok — every law resolves its one body and quotes its sentence.")
        return 1 if problems else 0
    out = corpus.laws(repo)
    if a.json:
        print(json.dumps(out, indent=2, ensure_ascii=False))
    else:
        for group in ("universal", "project"):
            for l in out[group]:
                print(f"{l['id']}  {l['title']} — {l['sentence']}  [{l['body']}]")
    return 0


def cmd_law_sentences(repo, a):
    text = Path(a.file).read_text(encoding="utf-8", errors="replace")
    for id_, sentence in corpus.law_sentences(text):
        print(f"{id_}\t{sentence}")
    return 0


def _ctx(a) -> dict:
    return {k: v for k, v in {"phase": a.phase, "scope": a.scope, "change_type": a.change_type, "command": a.command,
                              "framework": a.framework or [], "agent": a.agent}.items() if v}


def cmd_applicable(repo, a):
    res = corpus.applicable(repo, _ctx(a), a.paths or None)
    print(json.dumps(res, indent=2, ensure_ascii=False) if a.format == "json" else corpus.rollcall(res, a.command or "", a.feature or ""))
    return 0


def cmd_digest(repo, a):
    b = a.budget or key(repo, "budgets.pre_edit", required=True)
    print(corpus.digest(repo, a.paths, int(b))[0])
    return 0


def cmd_deliver(repo, a):
    """Stdout = the JSON envelope a PreToolUse hook prints for its context to reach the model."""
    path, sid = a.path, a.session or ""
    if a.hook_json:  # the hook's own stdin payload
        try:
            payload = json.load(sys.stdin)
            path = (payload.get("tool_input") or {}).get("file_path") or ""
            sid = payload.get("session_id") or ""
        except (ValueError, AttributeError):
            path = ""
    if not path:
        return 0
    b = key(repo, "budgets.pre_edit", required=True)
    try:
        rel = str(Path(path).resolve().relative_to(repo))
    except ValueError:
        rel = path
    text, fingerprint = corpus.digest(repo, [rel], int(b))
    sid = "".join(ch for ch in sid if ch.isalnum() or ch in "-_") or "session"
    marker = repo / ".claude/state" / f"governance-delivered-{sid}.txt"
    note = ""
    try:
        seen = set(marker.read_text(encoding="utf-8").split())
    except OSError:
        seen = set()
    if fingerprint in seen:
        text = f'<governance-at-edit paths="{rel}" delivered="earlier-this-session" fingerprint="{fingerprint}" />'
    else:
        try:
            marker.parent.mkdir(parents=True, exist_ok=True)
            with marker.open("a", encoding="utf-8") as fh:
                fh.write(fingerprint + "\n")
        except OSError as e:
            note = f"\n(dedupe marker not writable: {e.__class__.__name__} — full payload will repeat)"
    print(json.dumps({"hookSpecificOutput": {"hookEventName": "PreToolUse", "additionalContext": text + note}}))
    return 0


def cmd_snapshot_sections(repo, a):
    print(corpus.snapshot_sections(repo, a.profile))
    return 0


def cmd_budget(repo, a):
    rows = budget_mod.measure(repo)
    print(budget_mod.render(rows))
    bad = [k for k, r in rows.items() if not r["ok"]]
    if bad:
        print(f"budget: RED at {', '.join(bad)} — an overflow means shrink the producer or raise the key with its record; an empty emission means the producer is dead.", file=sys.stderr)
        return 1
    print("budget: ok — every producer within its key.")
    return 0


def cmd_retired(repo, a):
    hits = retired.scan(repo)
    print(retired.render(hits))
    return 1 if hits else 0


def _base(repo, a):
    """--base when given, else the one resolver (a sub-increment measures against its train)."""
    return a.base or branch_mod.diff_base(repo, a.branch)


def cmd_branch_class(repo, a):
    info = branch_mod.branch_class(repo, a.branch)
    if a.protected:
        if info["protected"]:
            print(f"{info['branch']}: protected ({info['class']})")
            return 1
        return 0
    print(json.dumps(info) if a.json else f"{info['branch']}: {info['class']}" + (f" (train {info['train']})" if info.get("train") else ""))
    return 0


def cmd_diff_base(repo, a):
    try:
        print(branch_mod.diff_base(repo, a.branch))
    except branch_mod.UnknownBranch as e:
        print(f"diff-base: RED — {e}", file=sys.stderr)
        return 1
    return 0


def cmd_surface(repo, a):
    try:
        s = branch_mod.surface(repo, a.base, a.branch)
    except branch_mod.UnknownBranch as e:
        print(f"surface: RED — {e}", file=sys.stderr)
        return 1
    print(json.dumps(s) if a.json else branch_mod.render_surface(s))
    return 0 if s["ok"] else 1


def cmd_profile(repo, a):
    if a.run:
        rep = profile_mod.run(repo, a.branch, a.base, a.control_point)
        print(json.dumps(rep, indent=2) if a.json else profile_mod.render(rep))
        return {"ok": 0, "RED": 1}.get(rep["verdict"], 2)
    pr = profile_mod.profile(repo, a.branch)
    pr["members"] = profile_mod.owed(pr["profile"])
    print(json.dumps(pr, indent=2) if a.json else f"profile: {pr['profile']} — {pr['reason']} · {pr['mode_reason']}\n  members: " + ", ".join(m["member"] for m in pr["members"]))
    return 0


def cmd_runtime_surface(repo, a):
    if a.changed:
        base = a.base or "HEAD^1"
        c = runtime.changed(repo, base)
        print(json.dumps(c) if a.json else f"runtime-surface: {'touched' if c['touched'] else 'untouched'} — {c['reason']}" + (f"\n  {' '.join(c['hits'] + c['always'])}" if c["hits"] or c["always"] else ""))
        return 0 if c["touched"] else 1
    findings, stats = runtime.parity(repo)
    print(coherence.render("runtime-surface", findings, f"{stats['literals']} path(s) read by {len(stats['workflows'])} deploying workflow(s), {stats['declared']} declared read(s)"))
    return 1 if findings else 0


def cmd_one_definition(repo, a):
    f = profile_mod.one_definition(repo)
    print(coherence.render("one-definition", [{"path": f"{x['path']}:{x['line']}", "reason": x["reason"]} for x in f], "hooks, workflows and the preflight keep no second definition"))
    return 1 if f else 0


def cmd_certify(repo, a):
    try:   # a tree certification needs no base — never classify a branch for it (QA often runs on a tag / detached checkout)
        base = _base(repo, a) if a.subject == "diff" else None
    except branch_mod.UnknownBranch as e:
        print(f"certify: RED — {e}", file=sys.stderr)
        return 1
    c = coherence.certify(repo, a.subject, base, a.paths)
    if a.json:
        print(json.dumps(c))
    else:  # ready to paste under `certifies:` in the artefact frontmatter
        print(f"  subject: {c['subject']}\n  paths: {json.dumps(c['paths'])}\n  hash: \"{c['hash']}\"")
    return 0


def cmd_currency(repo, a):
    try:
        base = _base(repo, a)
    except branch_mod.UnknownBranch as e:
        print(f"currency: RED — {e}", file=sys.stderr)
        return 1
    findings, faults = coherence.currency(repo, base)
    print(coherence.render("currency", findings))
    for f in faults:
        print(f"currency: could not judge {f['path']}: {f['reason']}", file=sys.stderr)
    return 1 if findings else (2 if faults else 0)


def cmd_manifest_parity(repo, a):
    findings, stats = coherence.manifest_parity(repo)
    print(coherence.render("manifest-parity", findings, f"{stats['compared']} compared, {stats['no_version']} without a frontmatter version"))
    return 1 if findings else 0


def build_parser():
    ap = argparse.ArgumentParser(prog="gate.py", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default=None)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("key"); p.add_argument("dotted"); p.add_argument("--required", action="store_true"); p.set_defaults(fn=cmd_key)
    p = sub.add_parser("context"); p.set_defaults(fn=lambda r, a: print(context(r)) or 0)
    p = sub.add_parser("laws"); p.add_argument("--json", action="store_true"); p.add_argument("--parity", action="store_true"); p.set_defaults(fn=cmd_laws)
    p = sub.add_parser("law-sentences"); p.add_argument("--file", required=True); p.set_defaults(fn=cmd_law_sentences)
    p = sub.add_parser("applicable")
    for opt in ("--phase", "--scope", "--change-type", "--command", "--feature", "--agent"):
        p.add_argument(opt, default=None)
    p.add_argument("--framework", nargs="*", default=None); p.add_argument("--paths", nargs="*", default=None)
    p.add_argument("--format", choices=("json", "rollcall"), default="rollcall"); p.set_defaults(fn=cmd_applicable)
    p = sub.add_parser("digest"); p.add_argument("--paths", nargs="+", required=True); p.add_argument("--budget", type=int, default=None); p.set_defaults(fn=cmd_digest)
    p = sub.add_parser("deliver"); p.add_argument("--path", default=""); p.add_argument("--session", default=""); p.add_argument("--hook-json", action="store_true"); p.set_defaults(fn=cmd_deliver)
    p = sub.add_parser("snapshot-sections"); p.add_argument("--profile", choices=("lite", "full"), default="lite"); p.set_defaults(fn=cmd_snapshot_sections)
    p = sub.add_parser("budget"); p.set_defaults(fn=cmd_budget)
    p = sub.add_parser("retired-terms"); p.set_defaults(fn=cmd_retired)
    p = sub.add_parser("certify"); p.add_argument("--subject", choices=("diff", "tree"), required=True); p.add_argument("--base", default=None); p.add_argument("--branch", default=None); p.add_argument("--paths", nargs="*", default=None); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_certify)
    p = sub.add_parser("currency"); p.add_argument("--base", default=None); p.add_argument("--branch", default=None); p.set_defaults(fn=cmd_currency)
    p = sub.add_parser("manifest-parity"); p.set_defaults(fn=cmd_manifest_parity)
    p = sub.add_parser("branch-class"); p.add_argument("--branch", default=None); p.add_argument("--protected", action="store_true"); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_branch_class)
    p = sub.add_parser("diff-base"); p.add_argument("--branch", default=None); p.set_defaults(fn=cmd_diff_base)
    p = sub.add_parser("surface"); p.add_argument("--base", default=None); p.add_argument("--branch", default=None); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_surface)
    p = sub.add_parser("profile"); p.add_argument("--run", action="store_true"); p.add_argument("--control-point", choices=("push", "ci"), default="push"); p.add_argument("--base", default=None); p.add_argument("--branch", default=None); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_profile)
    p = sub.add_parser("one-definition"); p.set_defaults(fn=cmd_one_definition)
    p = sub.add_parser("runtime-surface"); p.add_argument("--changed", action="store_true"); p.add_argument("--base", default=None); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_runtime_surface)
    return ap


def main(argv=None) -> int:
    a = build_parser().parse_args(argv)
    repo = Path(a.repo).resolve() if a.repo else repo_root()
    try:
        return a.fn(repo, a)
    except GateFault as e:
        print(f"gate: {e}", file=sys.stderr)
        return 2
    except Exception as e:  # LAW-08: never a raw trace unless asked
        if os.environ.get("GATE_DEBUG") == "1":
            raise
        print(f"gate: the tool could not do its job ({type(e).__name__}: {e}). Set GATE_DEBUG=1 for the trace.", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
