#!/usr/bin/env python3
# Generated by Phase: IMPLEMENT | Feature: EVOL-043
"""gate — the framework's one reader. Every hook, gate and pre-flight asks it; none re-derives.

  gate.py [--repo DIR] key <dotted> [--required]   print a config key (config/quality.json); fail-closed with --required
  gate.py context                                  meta | downstream
  gate.py laws [--json] [--parity]                 the law index (universal + project); --parity checks every body
  gate.py law-sentences --file F                   `ID<TAB>sentence` per law of a governance source (ceremony gate)
  gate.py applicable [--phase P] [--scope S] [--change-type T] [--command C] [--agent A] [--framework F…]
                     [--paths p…] [--format json|rollcall] [--feature ID]
  gate.py digest --paths p… [--budget N]           the slice of law governing paths, within budget (bytes)
  gate.py deliver --path p [--session SID] | --hook-json    PreToolUse envelope (additionalContext), deduped per session
  gate.py snapshot-sections [--profile lite|full]  stack config + rules manifest + law index + families (+ bodies)
  gate.py budget                                   run every producer at worst case; exit 1 on overflow, dead/absent producer or missing key
  gate.py retired-terms                            the retired-vocabulary ratchet; exit 1 on a hit
  gate.py certify --subject diff|tree [--base B] [--branch B] [--paths p…] [--json]   the certifies: block a verdict embeds (paths + hash); diff base = gate.py diff-base
  gate.py certify --subject worktree --paths p…   the on-disk hash (tracked + untracked) taken before and after a read-only run — the guard, never a verdict subject
  gate.py currency [--base B] [--branch B]         the push's verdict artefacts still certify their files; exit 1 stale/missing/unknown branch · 2 could not judge
  gate.py manifest-parity                          frontmatter version == manifest version for every governed file; exit 1 on drift
  gate.py branch-class [--branch B] [--protected] [--json]   protected · sub-increment · train · increment · feature · fix · docs · chore · epic · unknown
  gate.py diff-base [--branch B]                   the ONE diff base (sub-increment → its train; else the default base branch); exit 1 on an unknown name
  gate.py surface [--base B] [--branch B] [--json] files + lines of base...HEAD vs surface.ceiling_*; exit 1 over the ceiling without a Surface-Escape trailer
  gate.py profile [--branch B] [--json]            the gate profile this push owes (delivery_mode × branch class → light | full, fail-closed to full)
  gate.py profile --run [--control-point push|ci] [--base B] [--branch B] [--json]   run every script member of the profile, all-report; exit 1 any red · 2 a member could not run
  gate.py one-definition                           hooks / workflows / preflight keep no branch list, mode read or mode override; exit 1 on a finding
  gate.py runtime-surface [--json]                 parity: every path a deploying job or its scripts read is on surface.runtime_surface, a hard exclusion or a declared read; exit 1 on a finding
  gate.py runtime-surface --changed [--base B]     did base...HEAD touch the runtime surface (or a hard exclusion)? exit 0 touched · 1 untouched (the machinery may skip) · 2 could not judge
  gate.py plan --path P [--branch B]               may this write happen? governed path × branch class × approved plan; exit 0 pass · 1 blocked (reason + resolution) · 2 fault
  gate.py plan --status [--branch B]               one advisory line for the prompt hook (exit 0 always)
  gate.py plan --enter [--branch B]                may this session enter plan mode? exit 1 on a class a framework phase already plans (one stage, never two)
  gate.py plan --record --hook-json                write the approval marker from the harness's PostToolUse ExitPlanMode payload on stdin — refuses anything else
  gate.py documentation --path P | --changed [--base B]   the ONE definition of a documentation path (config: documentation); --changed exit 0 = every path of base...HEAD is documentation
  gate.py seal --plan [--branch B --base B]        the gates the loop owes NOW on the tree on disk, grouped into executions (one per command); full when unmapped
  gate.py seal --write --gates a,b --ok|--red [--summary S] [--full]   record a run (read-set hashes on disk, right after the execution); --full seals the tree over green records (refused when a read-set moved after its run)
  gate.py seal --check [--branch B --base B --ref R --control-point P]   the push's question: the seal covers the tree the commit carries; exit 1 gates owed · n/a when not required
  gate.py seal --validate                          the map is sound (documentation defined, every gate reads something)
  gate.py digests [--base B --branch B --control-point P] [--json]   the feature's planning artefacts carry a current, complete governance digest (fingerprint; every bound rule referenced as rules/<name>.md — the change on disk vs the merge-base); exit 1 stale/incomplete
  gate.py traceability [--json]                    every declared test case (docs/spec/*/test_plan.md) has a linking test at the ONE home (config: traceability); unknown or malformed links red; the baseline only shrinks; exit 1 red · n/a when not required
  gate.py traceability --declared --json           the declared qualified case ids (FEATURE/CASE) and the manual ones — what the pytest plugin validates at collection; a listing, rc 0
  gate.py traceability --baseline --init|--refresh   record the unlinked debt once / shrink it (never adds)
  gate.py agents [--json]                          validate the roster and the class policy (rules/agents.md + agents.families): tools per class, budgets, pointers, critic ≠ writer family, ladder, rows, spawn sites, vendored lenses; exit 1 on a finding · 2 policy/manifest unreadable
  gate.py agents --resolve --class C [--surface S --files N --lines M --round R]   per-spawn model alias + effort; exit 1 when the round is over the class cap
  gate.py agents --fallback --class C --family F   the next rung after a provider error; refused for a writer class; `separation: false` when a critic lands on the writer's family
  gate.py agents --digest --agent NAME             the slice of law governing the agent's surface (always-on rules included), within its class budget
  gate.py agents --spawn --agent NAME --model M [--hook-json]   the model handed to a roster agent is its family's alias; exit 1 refused (the PreToolUse Agent hook)
  gate.py agents --check-return --class C < return.md   refuse a return missing its governance block / a critic finding outside the shape or without a real probe

Exit: 0 ok · 1 gate red · 2 the tool could not do its job (plain language, LAW-08) · 3 the reader itself is missing or broken (governance not delivered).
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
try:
    from gates import agents as agents_mod, branch as branch_mod, budget as budget_mod, coherence, corpus, digests as digests_mod, planning, profile as profile_mod, retired, runtime, seal as seal_mod, traceability as trace_mod  # noqa: E402
    from gates.common import GateFault, context, key, repo_root  # noqa: E402
except Exception as e:  # missing OR broken package (SyntaxError included) — it ships next to this file (SETUP / factory-sync)
    print(f"gate: the scripts/gates package is missing or broken ({type(e).__name__}: {e}) — re-run SETUP --generate or factory-sync.sh", file=sys.stderr)
    sys.exit(3)   # 3 = the reader itself is not delivered: hooks treat it as governance missing (block), never as one member's fault


def cmd_key(repo, a):
    v = key(repo, a.dotted, required=a.required)
    print(json.dumps(v) if not isinstance(v, str) else v)
    return 0


def cmd_laws(repo, a):
    if a.parity:
        problems = corpus.parity(repo)
        print("\n".join(problems) if problems else "laws --parity: ok — every law resolves its one body and quotes its sentence.")
        return 1 if problems else 0
    out = corpus.laws(repo)
    if a.json:
        print(json.dumps(out, indent=2, ensure_ascii=False))
    else:
        for group in ("universal", "project"):
            for l in out[group]:
                print(f"{l['id']}  {l['title']} — {l['sentence']}  [{l['body']}]")
    return 0


def cmd_law_sentences(repo, a):
    text = Path(a.file).read_text(encoding="utf-8", errors="replace")
    for id_, sentence in corpus.law_sentences(text):
        print(f"{id_}\t{sentence}")
    return 0


def _ctx(a) -> dict:
    return {k: v for k, v in {"phase": a.phase, "scope": a.scope, "change_type": a.change_type, "command": a.command,
                              "framework": a.framework or [], "agent": a.agent}.items() if v}


def cmd_applicable(repo, a):
    res = corpus.applicable(repo, _ctx(a), a.paths or None)
    print(json.dumps(res, indent=2, ensure_ascii=False) if a.format == "json" else corpus.rollcall(res, a.command or "", a.feature or ""))
    return 0


def cmd_digest(repo, a):
    b = a.budget or key(repo, "budgets.pre_edit", required=True)
    print(corpus.digest(repo, a.paths, int(b))[0])
    return 0


def cmd_deliver(repo, a):
    """Stdout = the JSON envelope a PreToolUse hook prints for its context to reach the model."""
    path, sid = a.path, a.session or ""
    if a.hook_json:  # the hook's own stdin payload
        try:
            payload = json.load(sys.stdin)
            path = (payload.get("tool_input") or {}).get("file_path") or ""
            sid = payload.get("session_id") or ""
        except (ValueError, AttributeError):
            path = ""
    if not path:
        return 0
    b = key(repo, "budgets.pre_edit", required=True)
    try:
        rel = str(Path(path).resolve().relative_to(repo))
    except ValueError:
        rel = path
    text, fingerprint = corpus.digest(repo, [rel], int(b))
    sid = "".join(ch for ch in sid if ch.isalnum() or ch in "-_") or "session"
    marker = repo / ".claude/state" / f"governance-delivered-{sid}.txt"
    note = ""
    try:
        seen = set(marker.read_text(encoding="utf-8").split())
    except OSError:
        seen = set()
    if fingerprint in seen:
        text = f'<governance-at-edit paths="{rel}" delivered="earlier-this-session" fingerprint="{fingerprint}" />'
    else:
        try:
            marker.parent.mkdir(parents=True, exist_ok=True)
            with marker.open("a", encoding="utf-8") as fh:
                fh.write(fingerprint + "\n")
        except OSError as e:
            note = f"\n(dedupe marker not writable: {e.__class__.__name__} — full payload will repeat)"
    print(json.dumps({"hookSpecificOutput": {"hookEventName": "PreToolUse", "additionalContext": text + note}}))
    return 0


def cmd_snapshot_sections(repo, a):
    print(corpus.snapshot_sections(repo, a.profile))
    return 0


def cmd_budget(repo, a):
    rows = budget_mod.measure(repo)
    print(budget_mod.render(rows))
    bad = [k for k, r in rows.items() if not r["ok"]]
    if bad:
        print(f"budget: RED at {', '.join(bad)} — an overflow means shrink the producer or raise the key with its record; an empty emission means the producer is dead.", file=sys.stderr)
        return 1
    print("budget: ok — every producer within its key.")
    return 0


def cmd_retired(repo, a):
    hits = retired.scan(repo)
    print(retired.render(hits))
    return 1 if hits else 0


def _base(repo, a):
    """--base when given, else the one resolver (a sub-increment measures against its train)."""
    return a.base or branch_mod.diff_base(repo, a.branch)


def cmd_branch_class(repo, a):
    info = branch_mod.branch_class(repo, a.branch)
    if a.protected:
        if info["protected"]:
            print(f"{info['branch']}: protected ({info['class']})")
            return 1
        return 0
    print(json.dumps(info) if a.json else f"{info['branch']}: {info['class']}" + (f" (train {info['train']})" if info.get("train") else ""))
    return 0


def cmd_diff_base(repo, a):
    try:
        print(branch_mod.diff_base(repo, a.branch))
    except branch_mod.UnknownBranch as e:
        print(f"diff-base: RED — {e}", file=sys.stderr)
        return 1
    return 0


def cmd_surface(repo, a):
    try:
        s = branch_mod.surface(repo, a.base, a.branch)
    except branch_mod.UnknownBranch as e:
        print(f"surface: RED — {e}", file=sys.stderr)
        return 1
    print(json.dumps(s) if a.json else branch_mod.render_surface(s))
    return 0 if s["ok"] else 1


def cmd_profile(repo, a):
    if a.run:
        rep = profile_mod.run(repo, a.branch, a.base, a.control_point)
        print(json.dumps(rep, indent=2) if a.json else profile_mod.render(rep))
        return {"ok": 0, "RED": 1}.get(rep["verdict"], 2)
    pr = profile_mod.profile(repo, a.branch, a.control_point)
    pr["members"] = profile_mod.owed(pr["profile"])
    print(json.dumps(pr, indent=2) if a.json else f"profile: {pr['profile']} — {pr['reason']} · {pr['mode_reason']}\n  members: " + ", ".join(m["member"] for m in pr["members"]))
    return 0


def cmd_runtime_surface(repo, a):
    if a.changed:
        base = a.base or "HEAD^1"
        c = runtime.changed(repo, base)
        print(json.dumps(c) if a.json else f"runtime-surface: {'touched' if c['touched'] else 'untouched'} — {c['reason']}" + (f"\n  {' '.join(c['hits'] + c['always'])}" if c["hits"] or c["always"] else ""))
        return 0 if c["touched"] else 1
    findings, stats = runtime.parity(repo)
    if a.json:
        print(json.dumps({"findings": findings, **stats}))
    else:
        print(coherence.render("runtime-surface", findings, f"{stats['literals']} path(s) read by {len(stats['workflows'])} deploying workflow(s), {stats['declared']} declared read(s)"))
    return 1 if findings else 0


def cmd_plan(repo, a):
    if a.record:
        try:
            payload = json.load(sys.stdin) if a.hook_json else {}
        except ValueError:
            payload = {}
        m = planning.record(repo, payload, a.branch)
        print(f"plan: approval recorded for {m['branch']} at {m['approved_at']} ({m['source']})")
        return 0
    if a.status:
        try:
            st = planning.status(repo, a.branch)
        except Exception as e:   # the advisory never fails the prompt
            st = {"line": f"planning: the reader could not judge ({type(e).__name__}: {e}). A write to a governed path will be BLOCKED until this is fixed."}
        print(st["line"])
        return 0
    if a.enter:
        e = planning.enter(repo, a.branch)
        print(("plan: BLOCKED — " if e["block"] else "plan: ok — ") + e["reason"])
        return 1 if e["block"] else 0
    if not a.path:
        print("gate: plan needs --path P, --status or --record", file=sys.stderr)
        return 2
    g = planning.gate(repo, a.path, a.branch)
    if g["block"]:
        print(f"plan: BLOCKED — {g['reason']}.\n{g['resolution']}")
        return 1
    print(f"plan: ok — {g['reason']}")
    return 0


def cmd_agents(repo, a):
    if a.resolve:
        r = agents_mod.resolve(repo, a.cls, a.surface or "", a.files or 0, a.lines or 0, a.round or 1)
        if not r["ok"]:
            print(json.dumps(r) if a.json else f"agents: REFUSED — {r['reason']}")
            return 1
        print(json.dumps(r) if a.json else f"agents: {r['class']} → model {r['model']} ({r['family']}) · effort {r['effort']} · tier {r['tier']} · round {r['round']} · {r['matched']}")
        return 0
    if a.fallback:
        r = agents_mod.fallback(repo, a.cls, a.family or "")
        print(json.dumps(r) if a.json else f"agents: {'fallback → ' + r['model'] + ' — ' if r['ok'] else 'REFUSED — '}{r['reason']}")
        return 0 if r["ok"] else 1
    if a.digest:
        text, fp, budget = agents_mod.digest(repo, a.agent)
        print(text); print(f"\n<!-- digest {fp} · {len(text.encode())} B within {budget} B -->")
        return 0
    if a.spawn:
        agent, model = a.agent, a.model
        if a.hook_json:   # the PreToolUse Agent payload: {"tool_input": {"subagent_type": …, "model": …}}
            try:
                ti = (json.loads(sys.stdin.read() or "{}") or {}).get("tool_input") or {}
            except (json.JSONDecodeError, AttributeError):
                ti = {}
            agent = str(ti.get("subagent_type") or agent or ""); model = str(ti.get("model") or model or "")
        r = agents_mod.spawn_check(repo, agent, model)
        print(json.dumps(r) if a.json else f"agents: spawn {'ok' if r['ok'] else 'REFUSED'} — {r['reason']}")
        return 0 if r["ok"] else 1
    if a.check_return:
        if a.cls not in agents_mod.policy(repo)["classes"]:
            raise GateFault(f"--check-return needs --class, one of {', '.join(agents_mod.policy(repo)['classes'])}")
        problems = agents_mod.check_return(sys.stdin.read(), a.cls)
        print("agents: return ok" if not problems else "agents: return REFUSED — " + "; ".join(problems))
        return 1 if problems else 0
    mp = coherence.manifest_path(repo)
    try:
        manifest = json.loads(mp.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        raise GateFault(f"the governance manifest {mp} is unreadable ({e}) — roster delivery cannot be judged") from None
    findings = agents_mod.validate(repo, manifest)
    if a.json:
        print(json.dumps(findings))
    else:
        print(coherence.render("agents", findings, "roster, tools per class, budgets, pointers, families, ladder, spawn sites"))
    return 1 if findings else 0


def cmd_documentation(repo, a):
    if a.changed:
        base = _base(repo, a)
        r = seal_mod.docs_only(repo, base)
        print(json.dumps(r) if a.json else f"documentation: {'ok' if r['ok'] else 'no'} — {r['reason']}")
        return 0 if r["ok"] else 1
    if not a.path:
        raise GateFault("documentation needs --path P or --changed")
    ok, why = seal_mod.is_documentation(a.path, seal_mod.documentation_cfg(repo))
    print(f"documentation: {'yes' if ok else 'no'} — {a.path}: {why}")
    return 0 if ok else 1


def cmd_seal(repo, a):
    if a.plan:
        r = seal_mod.plan(repo, a.branch, a.base)
        if a.json:
            print(json.dumps(r)); return 0 if r["ok"] else 1
        if not r["required"]:
            print(f"seal: n/a — {r['reason']}"); return 0
        if not r["ok"]:
            print(f"seal: RED — {r['reason']}"); return 1
        print(f"seal: plan — {r['reason']}")
        for e in r["executions"]:
            print(f"  run: {e['command']}  →  {', '.join(e['gates'])}")
        if not r["executions"]:
            print("  nothing owed")
        return 0
    if a.write:
        gates = [g.strip() for g in (a.gates or "").split(",") if g.strip()]
        if a.ok == a.red:
            raise GateFault("seal --write needs the outcome: --ok or --red (a forgotten flag is never a green)")
        r = seal_mod.write(repo, gates, ok=a.ok, summary=a.summary or "", full=a.full, branch=a.branch)
        print(json.dumps(r) if a.json else f"seal: recorded {', '.join(gates) or '(no gate)'} {'ok' if not a.red else 'RED'}{' · full loop sealed' if r['full'] else ''} → {r['path']}")
        return 0
    if a.validate:
        f = seal_mod.validate(repo)
        print(coherence.render("seal", f, "documentation defined, every gate reads something, the seal's home"))
        return 1 if f else 0
    r = seal_mod.check(repo, a.branch, a.ref or "HEAD", a.control_point, a.base)
    print(json.dumps(r) if a.json else seal_mod.render(r))
    return 0 if r["ok"] else 1


def cmd_digests(repo, a):
    base = _base(repo, a)
    r = digests_mod.check(repo, base, a.branch, a.control_point)
    print(json.dumps(r) if a.json else digests_mod.render(r))
    return 0 if r["ok"] else 1


def cmd_traceability(repo, a):
    if a.declared:
        c = trace_mod.cfg(repo)
        if not c["required"]:
            print(json.dumps({"declared": [], "required": False, "reason": c["reason"]}) if a.json else f"traceability: n/a — {c['reason']}"); return 0
        dec, bad = trace_mod.declared(repo, c)   # a listing, never a verdict: rc 0 — the findings are the check's
        print(json.dumps({"declared": sorted(dec), "required": True, "manual": sorted(q for q, d in dec.items() if d["manual"]), "malformed": bad}) if a.json else "\n".join(sorted(dec)))
        return 0
    if a.baseline:
        r = trace_mod.baseline(repo, init=a.init, refresh=a.refresh)
        print(json.dumps(r) if a.json else f"traceability: baseline {'recorded' if a.init else 'shrunk'} → {r['path']} ({len(r['unlinked'])} unlinked{', removed ' + ', '.join(r['removed']) if r['removed'] else ''})")
        return 0
    r = trace_mod.check(repo)
    print(json.dumps(r) if a.json else trace_mod.render(r))
    return 0 if r["ok"] else 1


def cmd_one_definition(repo, a):
    f = profile_mod.one_definition(repo)
    print(coherence.render("one-definition", [{"path": f"{x['path']}:{x['line']}", "reason": x["reason"]} for x in f], "hooks, workflows and the preflight keep no second definition"))
    return 1 if f else 0


def cmd_certify(repo, a):
    try:   # a tree / worktree certification needs no base — never classify a branch for it (QA often runs on a tag / detached checkout)
        base = _base(repo, a) if a.subject == "diff" else None
    except branch_mod.UnknownBranch as e:
        print(f"certify: RED — {e}", file=sys.stderr)
        return 1
    c = coherence.certify(repo, a.subject, base, a.paths)
    if a.json:
        print(json.dumps(c))
    else:  # ready to paste under `certifies:` in the artefact frontmatter
        print(f"  subject: {c['subject']}\n  paths: {json.dumps(c['paths'])}\n  hash: \"{c['hash']}\"")
    return 0


def cmd_currency(repo, a):
    try:
        base = _base(repo, a)
    except branch_mod.UnknownBranch as e:
        print(f"currency: RED — {e}", file=sys.stderr)
        return 1
    findings, faults = coherence.currency(repo, base)
    print(coherence.render("currency", findings))
    for f in faults:
        print(f"currency: could not judge {f['path']}: {f['reason']}", file=sys.stderr)
    return 1 if findings else (2 if faults else 0)


def cmd_manifest_parity(repo, a):
    findings, stats = coherence.manifest_parity(repo)
    print(coherence.render("manifest-parity", findings, f"{stats['compared']} compared, {stats['no_version']} without a frontmatter version"))
    return 1 if findings else 0


def build_parser():
    ap = argparse.ArgumentParser(prog="gate.py", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default=None)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("key"); p.add_argument("dotted"); p.add_argument("--required", action="store_true"); p.set_defaults(fn=cmd_key)
    p = sub.add_parser("context"); p.set_defaults(fn=lambda r, a: print(context(r)) or 0)
    p = sub.add_parser("laws"); p.add_argument("--json", action="store_true"); p.add_argument("--parity", action="store_true"); p.set_defaults(fn=cmd_laws)
    p = sub.add_parser("law-sentences"); p.add_argument("--file", required=True); p.set_defaults(fn=cmd_law_sentences)
    p = sub.add_parser("applicable")
    for opt in ("--phase", "--scope", "--change-type", "--command", "--feature", "--agent"):
        p.add_argument(opt, default=None)
    p.add_argument("--framework", nargs="*", default=None); p.add_argument("--paths", nargs="*", default=None)
    p.add_argument("--format", choices=("json", "rollcall"), default="rollcall"); p.set_defaults(fn=cmd_applicable)
    p = sub.add_parser("digest"); p.add_argument("--paths", nargs="+", required=True); p.add_argument("--budget", type=int, default=None); p.set_defaults(fn=cmd_digest)
    p = sub.add_parser("deliver"); p.add_argument("--path", default=""); p.add_argument("--session", default=""); p.add_argument("--hook-json", action="store_true"); p.set_defaults(fn=cmd_deliver)
    p = sub.add_parser("snapshot-sections"); p.add_argument("--profile", choices=("lite", "full"), default="lite"); p.set_defaults(fn=cmd_snapshot_sections)
    p = sub.add_parser("budget"); p.set_defaults(fn=cmd_budget)
    p = sub.add_parser("retired-terms"); p.set_defaults(fn=cmd_retired)
    p = sub.add_parser("certify"); p.add_argument("--subject", choices=("diff", "tree", "worktree"), required=True); p.add_argument("--base", default=None); p.add_argument("--branch", default=None); p.add_argument("--paths", nargs="*", default=None); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_certify)
    p = sub.add_parser("currency"); p.add_argument("--base", default=None); p.add_argument("--branch", default=None); p.set_defaults(fn=cmd_currency)
    p = sub.add_parser("manifest-parity"); p.set_defaults(fn=cmd_manifest_parity)
    p = sub.add_parser("branch-class"); p.add_argument("--branch", default=None); p.add_argument("--protected", action="store_true"); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_branch_class)
    p = sub.add_parser("diff-base"); p.add_argument("--branch", default=None); p.set_defaults(fn=cmd_diff_base)
    p = sub.add_parser("surface"); p.add_argument("--base", default=None); p.add_argument("--branch", default=None); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_surface)
    p = sub.add_parser("profile"); p.add_argument("--run", action="store_true"); p.add_argument("--control-point", choices=("push", "ci", "static"), default="push"); p.add_argument("--base", default=None); p.add_argument("--branch", default=None); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_profile)
    p = sub.add_parser("one-definition"); p.set_defaults(fn=cmd_one_definition)
    p = sub.add_parser("runtime-surface"); p.add_argument("--changed", action="store_true"); p.add_argument("--base", default=None); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_runtime_surface)
    p = sub.add_parser("documentation"); p.add_argument("--path", default=None); p.add_argument("--changed", action="store_true"); p.add_argument("--base", default=None); p.add_argument("--branch", default=None); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_documentation)
    p = sub.add_parser("seal"); p.add_argument("--base", default=None); p.add_argument("--plan", action="store_true"); p.add_argument("--write", action="store_true"); p.add_argument("--check", action="store_true"); p.add_argument("--validate", action="store_true"); p.add_argument("--gates", default=""); p.add_argument("--ok", action="store_true"); p.add_argument("--red", action="store_true"); p.add_argument("--summary", default=""); p.add_argument("--full", action="store_true"); p.add_argument("--branch", default=None); p.add_argument("--ref", default="HEAD"); p.add_argument("--control-point", choices=("push", "ci", "static"), default="push"); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_seal)
    p = sub.add_parser("traceability"); p.add_argument("--declared", action="store_true"); p.add_argument("--baseline", action="store_true"); p.add_argument("--init", action="store_true"); p.add_argument("--refresh", action="store_true"); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_traceability)
    p = sub.add_parser("digests"); p.add_argument("--base", default=None); p.add_argument("--branch", default=None); p.add_argument("--control-point", choices=("push", "ci", "static"), default="push"); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_digests)
    p = sub.add_parser("plan"); p.add_argument("--path", default=None); p.add_argument("--branch", default=None); p.add_argument("--status", action="store_true"); p.add_argument("--enter", action="store_true"); p.add_argument("--record", action="store_true"); p.add_argument("--hook-json", action="store_true"); p.set_defaults(fn=cmd_plan)
    p = sub.add_parser("agents"); p.add_argument("--resolve", action="store_true"); p.add_argument("--fallback", action="store_true"); p.add_argument("--digest", action="store_true"); p.add_argument("--spawn", action="store_true"); p.add_argument("--model", default=""); p.add_argument("--hook-json", action="store_true"); p.add_argument("--check-return", action="store_true"); p.add_argument("--class", dest="cls", default=""); p.add_argument("--surface", default=""); p.add_argument("--files", type=int, default=0); p.add_argument("--lines", type=int, default=0); p.add_argument("--round", type=int, default=1); p.add_argument("--family", default=""); p.add_argument("--agent", default=""); p.add_argument("--json", action="store_true"); p.set_defaults(fn=cmd_agents)
    return ap


def main(argv=None) -> int:
    a = build_parser().parse_args(argv)
    repo = Path(a.repo).resolve() if a.repo else repo_root()
    try:
        return a.fn(repo, a)
    except GateFault as e:
        print(f"gate: {e}", file=sys.stderr)
        return 2
    except Exception as e:  # LAW-08: never a raw trace unless asked
        if os.environ.get("GATE_DEBUG") == "1":
            raise
        print(f"gate: the tool could not do its job ({type(e).__name__}: {e}). Set GATE_DEBUG=1 for the trace.", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
