#!/usr/bin/env bash
# Generated by Agent: IMPLEMENT | Feature: EVOL-005
# ============================================================================
# install-hooks.sh — Installs git hooks from scripts/hooks/ into .git/hooks/
# ============================================================================
# Usage: bash scripts/install-hooks.sh [--force]
#
# Options:
#   --force    Overwrite existing hooks without prompting
#
# Can be run manually at any time (e.g. after cloning or regenerating the repo).
# ============================================================================

set -euo pipefail

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

HOOKS_SRC="scripts/hooks"
HOOKS_DST=$(git rev-parse --git-path hooks 2>/dev/null || echo "")
FORCE=false

if [[ "${1:-}" == "--force" ]]; then
  FORCE=true
fi

# Verify we're in a git repo and resolve hooks directory
if [[ -z "$HOOKS_DST" ]]; then
  echo -e "${RED}❌ Not in a git repository (git rev-parse --git-path hooks failed).${NC}"
  exit 1
fi

# Ensure hooks directory exists
if [ ! -d "$HOOKS_DST" ]; then
  mkdir -p "$HOOKS_DST"
fi

# Verify source hooks exist
if [ ! -d "$HOOKS_SRC" ]; then
  echo -e "${YELLOW}⚠️  No hooks directory found at $HOOKS_SRC. Skipping.${NC}"
  exit 0
fi

INSTALLED=0
SKIPPED=0

for hook_file in "$HOOKS_SRC"/*; do
  [ -f "$hook_file" ] || continue

  hook_name=$(basename "$hook_file")
  target="$HOOKS_DST/$hook_name"

  # Skip .sample files
  if [[ "$hook_name" == *.sample ]]; then
    continue
  fi

  # Check for existing custom hook
  if [ -f "$target" ] && [ "$FORCE" != true ]; then
    # Check if it's our hook (contains our marker)
    if grep -q "Generated by Agent:" "$target" 2>/dev/null; then
      # Our hook — safe to overwrite
      :
    else
      echo -e "${YELLOW}⚠️  Skipping $hook_name — custom hook exists. Use --force to overwrite.${NC}"
      SKIPPED=$((SKIPPED + 1))
      continue
    fi
  fi

  cp "$hook_file" "$target"
  chmod +x "$target"
  INSTALLED=$((INSTALLED + 1))
done

if [ "$INSTALLED" -gt 0 ]; then
  echo -e "${GREEN}✅ Installed $INSTALLED git hook(s): $(ls "$HOOKS_SRC" | grep -v '.sample' | tr '\n' ' ')${NC}"
fi

if [ "$SKIPPED" -gt 0 ]; then
  echo -e "${YELLOW}⚠️  Skipped $SKIPPED hook(s) — use --force to overwrite.${NC}"
fi

if [ "$INSTALLED" -eq 0 ] && [ "$SKIPPED" -eq 0 ]; then
  echo -e "${YELLOW}ℹ️  No hooks to install.${NC}"
fi
