#!/usr/bin/env python3
"""reconcile_inventory.py — register orphan artifacts + relocate dead paths.

Implements the reconciliation protocol described in
`.claude/skills/factory-codebase-inventory/SKILL.md` § Reconciliation Protocol.

Two modes:

  - `--auto` (default for CI / scripted use): bulk-register every orphan
    surfaced by `scripts/check-inventory-freshness.py` using the path-canonical
    metadata derivation (BC alias map, status filter, class-name probe,
    docstring-aware description extractor). Idempotent — running twice is a
    no-op when the inventory is already clean.

  - `--interactive` (default for `SETUP --reconcile-inventory` slash command
    when invoked by a human): same registration logic but pauses on each
    artifact for a REGISTER / SKIP / DEFER decision. Currently a stub that
    delegates to `--auto`; the LLM-driven `Factory-setup-reconcile-inventory`
    instructions file owns the RDR loop.

Why this exists (in addition to check-inventory-freshness.py):

  - The freshness check VERIFIES drift; this script RESOLVES drift.
  - Class-name probe + docstring extraction (with leading-comment skip) lives
    here and is reusable for any future inventory write path.
  - Eliminates the ad-hoc Python heredocs that previously rebuilt this logic
    badly each time (e.g. session 2026-05-05 produced 23 entries with the
    duplicate `use_cases use case` token because a one-off script lacked
    these helpers).

Usage:

  python3 scripts/reconcile_inventory.py                 # auto-register orphans
  python3 scripts/reconcile_inventory.py --dry-run       # preview only
  python3 scripts/reconcile_inventory.py --enrich-descriptions
                                                         # re-extract docstrings
                                                         # for entries whose
                                                         # description is the
                                                         # boilerplate fallback
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INVENTORY = REPO_ROOT / "config" / "codebase_inventory.json"
FRESHNESS = REPO_ROOT / "scripts" / "check-inventory-freshness.py"

# ---------------------------------------------------------------------------
# BC alias map — loaded from config/inventory_aliases.json. Each project
# materialises this file at SETUP --generate with project-specific BC names,
# feature ownership, and cross-BC overrides. When the file is missing or empty,
# the helpers degrade gracefully (orphan registration becomes a no-op).
# ---------------------------------------------------------------------------


def _load_inventory_config() -> tuple[dict[str, str], dict[str, list[str]], dict[str, list[str]]]:
    cfg_path = Path("config/inventory_aliases.json")
    if not cfg_path.exists():
        return {}, {}, {}
    import json as _json
    data = _json.loads(cfg_path.read_text())
    return (
        data.get("bc_alias", {}),
        data.get("bc_feature", {}),
        data.get("cross_bc_features", {}),
    )


BC_ALIAS, BC_FEATURE, CROSS_BC_FEATURES = _load_inventory_config()

KIND_TO_SHORT: dict[str, str] = {
    "use_case": "uc",
    "value_object": "vo",
    "entity": "entity",
}

# Reusability default per kind. Use cases are typically feature-bound;
# value objects + entities are reusable across the BC's surface.
KIND_TO_REUSABLE: dict[str, bool] = {
    "use_case": False,
    "value_object": True,
    "entity": True,
}


# ---------------------------------------------------------------------------
# Path → metadata helpers
# ---------------------------------------------------------------------------


def derive_kind(path: str) -> str | None:
    if "/use_cases/" in path:
        return "use_case"
    if "/value_objects/" in path:
        return "value_object"
    if "/entities/" in path:
        return "entity"
    return None


def derive_bc(path: str) -> str | None:
    m = re.search(r"src/backend/(bc_[a-z]+)/", path)
    return m.group(1) if m else None


def humanize_slug(slug: str) -> str:
    return slug.replace("_", " ")


# ---------------------------------------------------------------------------
# Class-name + docstring probe
# ---------------------------------------------------------------------------

# Strip leading non-code lines (shebang, encoding, comments) before scanning
# for the module docstring. Without this, files starting with
# `# Generated by Agent: …` headers fall through to the boilerplate template.
_LEADING_NON_CODE = re.compile(r"^(?:#[^\n]*\n|\s*\n|\#![^\n]*\n)*", re.MULTILINE)
_MODULE_DOCSTRING = re.compile(r'^("""|\'\'\')(.*?)\1', re.DOTALL)
_FIRST_CLASS_DOCSTRING = re.compile(
    r'^class\s+\w+[^:]*:\s*\n\s+("""|\'\'\')(.*?)\1', re.MULTILINE | re.DOTALL
)
_CLASS_DECLARATION = re.compile(r"^class\s+([A-Za-z_][A-Za-z0-9_]*)", re.MULTILINE)


def probe_classes_and_docstring(path: Path) -> tuple[list[str], str | None]:
    """Return (class_names, first_docstring_line) for a Python source file.

    The docstring extractor strips leading comment / encoding lines before
    looking for the triple-quoted block, so files with `# Generated by …`
    headers still surface their real docstring.
    """
    if not path.exists():
        return ([], None)
    text = path.read_text(encoding="utf-8")
    classes = _CLASS_DECLARATION.findall(text)

    # Strip leading non-code, then look for module docstring at start.
    stripped_match = _LEADING_NON_CODE.match(text)
    body = text[stripped_match.end():] if stripped_match else text
    mod_ds = _MODULE_DOCSTRING.match(body)
    if mod_ds:
        first_line = mod_ds.group(2).strip().split("\n", 1)[0].strip()
    else:
        cls_ds = _FIRST_CLASS_DOCSTRING.search(body)
        first_line = (
            cls_ds.group(2).strip().split("\n", 1)[0].strip() if cls_ds else None
        )
    return (classes, first_line if first_line and len(first_line) > 10 else None)


def make_description(
    path: str, kind: str, classes: list[str], docstring_line: str | None
) -> str:
    """Compose a meaningful one-line description.

    Priority: real docstring > multi-class file-groups template > clean per-kind
    fallback. Never echoes the directory name as a type token.
    """
    slug = Path(path).stem
    human = humanize_slug(slug)
    bc = derive_bc(path)
    bc_human = bc.replace("bc_", "") if bc else "?"

    if docstring_line:
        return docstring_line.rstrip(".") + "."

    if kind == "use_case":
        if len(classes) > 1:
            return (
                f"Use cases under bc_{bc_human} — file groups: "
                f"{' + '.join(classes)}."
            )
        return f"bc_{bc_human} use case — {human}."
    if kind == "value_object":
        return f"bc_{bc_human} value object — {human}."
    if kind == "entity":
        return f"bc_{bc_human} domain entity — {human}."
    return f"{human}."


def derive_id(bc: str, kind: str, slug: str) -> str:
    return f"{BC_ALIAS[bc]}-{KIND_TO_SHORT[kind]}-{slug.replace('_', '-')}"


def derive_name(classes: list[str], slug: str) -> str:
    """File-level entries: real class(es) slash-joined; fallback to title-case
    slug if the file has no class declaration (defensive, should not happen
    in canonical paths)."""
    if classes:
        return " / ".join(classes)
    return "".join(s.capitalize() for s in slug.split("_"))


def make_entry(path_str: str, today: str | None = None) -> dict | None:
    """Build a fully-populated inventory entry from a backend file path.

    Returns None if the path doesn't match a canonical orphan-scan glob.
    """
    bc = derive_bc(path_str)
    kind = derive_kind(path_str)
    if not bc or not kind or bc not in BC_ALIAS:
        return None
    today = today or date.today().isoformat()
    slug = Path(path_str).stem
    classes, docline = probe_classes_and_docstring(REPO_ROOT / path_str)

    return {
        "id": derive_id(bc, kind, slug),
        "type": kind,
        "name": derive_name(classes, slug),
        "module": f"backend/{bc}",
        "path": path_str,
        "description": make_description(path_str, kind, classes, docline),
        "feature_ids": CROSS_BC_FEATURES.get(path_str, BC_FEATURE.get(bc, [])),
        "status": "IMPLEMENTED",
        "registered_by": "SETUP --reconcile-inventory",
        "registered_at": today,
        "implemented_at": today,
        "reusable": KIND_TO_REUSABLE[kind],
    }


# ---------------------------------------------------------------------------
# Drift query (delegates to the freshness script's --json output)
# ---------------------------------------------------------------------------


def query_drift() -> dict:
    proc = subprocess.run(
        ["python3", str(FRESHNESS), "--json"],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    # The freshness script exits 1 on drift; we don't care about the exit
    # code here — only the JSON body, which is produced regardless.
    if not proc.stdout.strip():
        raise RuntimeError(
            f"check-inventory-freshness.py produced no JSON output. stderr: {proc.stderr}"
        )
    return json.loads(proc.stdout)


# ---------------------------------------------------------------------------
# Modes
# ---------------------------------------------------------------------------


def run_auto(dry_run: bool = False) -> int:
    inv = json.loads(INVENTORY.read_text())
    drift = query_drift()
    orphans = drift.get("orphans", [])
    if not orphans:
        print("✅ No orphans to register.")
        return 0

    new_entries = []
    skipped = []
    for path in orphans:
        entry = make_entry(path)
        if entry is None:
            skipped.append(path)
            continue
        new_entries.append(entry)

    if skipped:
        print(f"⚠️  Skipped {len(skipped)} non-canonical orphan paths (require manual registration):")
        for s in skipped:
            print(f"   - {s}")

    if dry_run:
        print(f"\n[dry-run] would register {len(new_entries)} entries:")
        for e in new_entries:
            print(f"   + {e['id']:<40} {e['name']}")
        return 0

    inv["artifacts"].extend(new_entries)
    inv["last_updated"] = date.today().isoformat()
    INVENTORY.write_text(
        json.dumps(inv, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"✅ Registered {len(new_entries)} new entries (total now {len(inv['artifacts'])}).")
    return 0


def run_enrich_descriptions(dry_run: bool = False) -> int:
    """Re-extract docstrings for entries whose description matches the
    boilerplate fallback (`bc_X use case — {slug}.` etc.). Useful when the
    original registration ran before the docstring extractor was hardened.
    """
    inv = json.loads(INVENTORY.read_text())
    boilerplate_re = re.compile(
        r"^bc_\w+ (use case|value object|domain entity)\s*[—-]\s*[\w\s]+\.\s*$"
    )
    fixed = []
    for a in inv["artifacts"]:
        if a.get("registered_by") != "SETUP --reconcile-inventory":
            continue
        path = a.get("path", "")
        if not path.endswith(".py"):
            continue
        desc = a.get("description", "")
        if not boilerplate_re.match(desc):
            continue
        full_path = REPO_ROOT / path
        kind = derive_kind(path)
        if not kind:
            continue
        classes, docline = probe_classes_and_docstring(full_path)
        if not docline:
            continue  # still no docstring; leave the boilerplate
        new_desc = make_description(path, kind, classes, docline)
        if new_desc != desc:
            fixed.append((a["id"], desc, new_desc))
            if not dry_run:
                a["description"] = new_desc

    if dry_run:
        print(f"[dry-run] would enrich {len(fixed)} descriptions:")
        for id_, old, new in fixed:
            print(f"   {id_}\n     - {old}\n     + {new}")
        return 0

    if fixed:
        inv["last_updated"] = date.today().isoformat()
        INVENTORY.write_text(
            json.dumps(inv, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
    print(f"✅ Enriched {len(fixed)} descriptions.")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview changes; do not write the inventory file.",
    )
    parser.add_argument(
        "--enrich-descriptions",
        action="store_true",
        help=(
            "Re-extract docstrings for already-registered entries whose "
            "description is the boilerplate fallback. Idempotent."
        ),
    )
    parser.add_argument(
        "--interactive",
        action="store_true",
        help=(
            "(Reserved) Pause on each orphan for REGISTER/SKIP/DEFER. "
            "Currently delegates to --auto. The LLM-driven slash command "
            "owns the RDR loop."
        ),
    )
    args = parser.parse_args(argv)

    if not INVENTORY.exists():
        print(f"ERROR: {INVENTORY} not found.", file=sys.stderr)
        return 2

    if args.enrich_descriptions:
        return run_enrich_descriptions(dry_run=args.dry_run)

    return run_auto(dry_run=args.dry_run)


if __name__ == "__main__":
    sys.exit(main())
