#!/usr/bin/env bash
# Generated by Phase: IMPLEMENT | Feature: EVOL-043
# META-ONLY: tests the framework-shipped Claude Code hooks; not shipped to materialised projects.
# test-hooks.sh — hook channel + red proof per hook (EVOL-043 hook audit).
#
# The Claude Code contract this proves:
#   PreToolUse block   = exit 2, message on STDERR (exit 1 is a non-blocking error: the tool runs anyway)
#   PreToolUse context = exit 0, STDOUT is JSON {"hookSpecificOutput":{"hookEventName":"PreToolUse","additionalContext":…}}
#   plain stdout from a PreToolUse hook never reaches the model
# Every hook under .context/templates/setup/claude/hooks/ (the SETUP-delivery source, byte-identical to
# .claude/hooks/ — lock-step pair) is fed the payload that must make it RED, and the payload that must
# let the tool through. A hook never seen red is not a hook.
#
# Exit codes: 0 all assertions pass · 1 any failure · 2 infrastructure.
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOKS="$ROOT/.context/templates/setup/claude/hooks"
[ -d "$HOOKS" ] || { echo "test-hooks: hooks template tree absent" >&2; exit 2; }
command -v python3 >/dev/null || { echo "test-hooks: python3 required" >&2; exit 2; }
command -v git >/dev/null || { echo "test-hooks: git required" >&2; exit 2; }
export PYTHONDONTWRITEBYTECODE=1

SANDBOX=$(mktemp -d) || exit 2
trap 'rm -rf "$SANDBOX"; [ -n "${SLEEPER:-}" ] && kill "$SLEEPER" 2>/dev/null' EXIT
PASS=0; FAIL=0
ok()  { PASS=$((PASS+1)); echo "  ✓ $1"; }
bad() { FAIL=$((FAIL+1)); echo "  ✗ $1"; [ -n "${2:-}" ] && echo "$2" | sed 's/^/      /' | head -8; return 0; }

# run_hook <hook> <stdin> → sets RC, OUT (stdout), ERR (stderr); runs from $REPO
run_hook() {
  local hook=$1 stdin=$2
  OUT=$(cd "$REPO" && printf '%s' "$stdin" | bash "$HOOKS/$hook" 2>"$SANDBOX/err"); RC=$?
  ERR=$(cat "$SANDBOX/err")
}
assert_block() { # assert_block <label> <needle-in-stderr>
  if [ "$RC" -eq 2 ] && [ -z "$OUT" ] && printf '%s' "$ERR" | grep -qF -- "$2"; then ok "$1"; else bad "$1 (rc=$RC, stdout=${#OUT}B, stderr has needle: $(printf '%s' "$ERR" | grep -cF -- "$2"))" "$ERR$OUT"; fi
}
assert_pass() { # assert_pass <label>
  if [ "$RC" -eq 0 ]; then ok "$1"; else bad "$1 (rc=$RC)" "$ERR$OUT"; fi
}
assert_context() { # assert_context <label> <needle-in-additionalContext>
  local ctx
  ctx=$(printf '%s' "$OUT" | python3 -c 'import json,sys
try:
    d=json.load(sys.stdin); h=d["hookSpecificOutput"]; assert h["hookEventName"]=="PreToolUse"; print(h.get("additionalContext",""))
except Exception as e:
    print("INVALID-ENVELOPE:"+str(e))' 2>/dev/null)
  if [ "$RC" -eq 0 ] && printf '%s' "$ctx" | grep -qF -- "$2"; then ok "$1"; else bad "$1 (rc=$RC)" "stdout: $OUT"; fi
}

# ── a sandbox project (git repo on a working branch, with the reader and a catalog) ──
REPO="$SANDBOX/proj"; mkdir -p "$REPO"
git -C "$REPO" init -q; git -C "$REPO" -c user.name=t -c user.email=t@t commit -q --allow-empty -m init
git -C "$REPO" checkout -q -b feature/FEAT-001-x
mkdir -p "$REPO/scripts" "$REPO/config" "$REPO/.claude/rules" "$REPO/.context" "$REPO/docs" "$REPO/.claude/state"
cp -R "$ROOT/scripts/gates" "$REPO/scripts/gates"; cp "$ROOT/scripts/gate.py" "$REPO/scripts/gate.py"
cat > "$REPO/config/coherence-context.json" <<'EOF'
{"context": "downstream", "audit": {"root_sets": ["."], "exclusions": [".git/"]}}
EOF
cat > "$REPO/config/quality.json" <<'EOF'
{"budgets": {"session_start": 2000, "prompt_submit": 16000, "pre_edit": 6000, "snapshot": 16000, "law_sentence_max_chars": 240, "dc_invariant_max_chars": 160}}
EOF
mkdir -p "$REPO/.claude/skills/factory-pr-review" "$REPO/.claude/instructions"
printf -- '---\nname: factory-pr-review\napplicable_when:\n  command: [push]\n---\n' > "$REPO/.claude/skills/factory-pr-review/SKILL.md"
printf -- '---\ndescription: b\napplicable_when:\n  phase: [IMPLEMENT]\n  command: [implement]\n---\n' > "$REPO/.claude/instructions/Factory-implement-build.instructions.md"
cat > "$REPO/.claude/rules/defect-prevention.md" <<'EOF'
---
description: "test catalog"
applicable_when:
  always: true
---
# Defect Prevention Catalog

## Families
| Family | Surface (globs) | Invariant |
|---|---|---|
| `runtime` | `src/**` | Every runtime path fails loudly. |
| `data` | `**/migrations/**` | Every migration is reversible. |

## Defect Classes
| DC | Family | Invariant | Gate | Paths | Applicable To | Severity |
|---|---|---|---|---|---|---|
| DC-18 | `runtime` | Unused imports are removed before commit. | `—` | `src/**` | DEV, REVIEW | WARNING |
| DC-27 | `data` | A migration ships with its down step. | `scripts/validate-migrations.sh` | `**/migrations/**` | DEV | CRITICAL |
| DC-29 | `runtime` | Build the least that satisfies the spec. | `—` | `*` | DEV, ARCH | WARNING |
EOF

echo "── check-branch-protection ──"
git -C "$REPO" checkout -q main 2>/dev/null || git -C "$REPO" checkout -q -b main
run_hook check-branch-protection.sh '{"tool_name":"Edit","tool_input":{"file_path":"x"}}'
assert_block "on main: exit 2, BLOCKED on stderr, nothing on stdout" "BLOCKED: on protected branch"
git -C "$REPO" checkout -q feature/FEAT-001-x
run_hook check-branch-protection.sh '{"tool_name":"Edit","tool_input":{"file_path":"x"}}'
assert_pass "on a working branch: passes"
run_hook check-branch-protection.sh '{not json'
assert_pass "malformed payload: passes (the branch is what matters)"

echo "── check-concurrency-lock ──"
mkdir -p "$REPO/.context/locks"
sleep 300 & SLEEPER=$!
printf '%s\n%s\n' "$SLEEPER" "2026-01-01T00:00:00Z" > "$REPO/.context/locks/feature-FEAT-001-x.lock"
run_hook check-concurrency-lock.sh '{"tool_name":"Edit"}'
assert_block "branch locked by a live foreign PID: exit 2 on stderr" "locked by another session"
kill "$SLEEPER" 2>/dev/null; wait "$SLEEPER" 2>/dev/null; SLEEPER=""
run_hook check-concurrency-lock.sh '{"tool_name":"Edit"}'
assert_pass "stale lock (dead PID): acquired, passes"

echo "── check-completion-gate ──"
run_hook check-completion-gate.sh '{"tool_name":"Write","tool_input":{"file_path":"docs/spec/F/dev_plan.md","content":"---\nstatus: IMPLEMENTED_AND_VERIFIED\n---\n- [ ] open task\n"}}'
assert_block "terminal status with an unchecked item: exit 2" "Completion gate failed"
run_hook check-completion-gate.sh '{"tool_name":"Write","tool_input":{"file_path":"docs/spec/F/dev_plan.md","content":"---\nstatus: IMPLEMENTED_AND_VERIFIED\n---\n- [x] done\n"}}'
assert_pass "terminal status, all ticked: passes"

echo "── check-ipp-compliance ──"
BIG=$(python3 -c 'print("---\n_progress:\n  completed_sections: []\n---\n" + "".join(f"## S{i}\n" + "x\n"*60 for i in range(3)))')
run_hook check-ipp-compliance.sh "$(python3 -c 'import json,sys; print(json.dumps({"tool_name":"Write","tool_input":{"file_path":"'"$REPO"'/docs/spec/F/design.md","content":sys.argv[1]}}))' "$BIG")"
assert_block "fully-formed first write of a governance artefact: exit 2" "IPP violation on first write"
run_hook check-ipp-compliance.sh "$(python3 -c 'import json; print(json.dumps({"tool_name":"Write","tool_input":{"file_path":"'"$REPO"'/docs/spec/F/design.md","content":"---\n_progress:\n  completed_sections: []\n---\n## A\n<!-- PENDING -->\n"}}))')"
assert_pass "skeleton first write: passes"

echo "── check-push-preflight ──"
mkdir -p "$REPO/.claude/skills/factory-pr-review/scripts"
printf '#!/usr/bin/env bash\necho "blocker: secrets"\nexit 1\n' > "$REPO/.claude/skills/factory-pr-review/scripts/preflight.sh"; chmod +x "$REPO/.claude/skills/factory-pr-review/scripts/preflight.sh"
run_hook check-push-preflight.sh '{"tool_name":"Bash","tool_input":{"command":"git push origin HEAD"}}'
assert_block "preflight blockers: the push is blocked with exit 2 on stderr" "Push blocked by Factory PR Review"
printf '#!/usr/bin/env bash\nexit 2\n' > "$REPO/.claude/skills/factory-pr-review/scripts/preflight.sh"
run_hook check-push-preflight.sh '{"tool_name":"Bash","tool_input":{"command":"git push"}}'
assert_context "preflight environment failure: push proceeds, the note reaches the model through the envelope" "skipped (environment)"
run_hook check-push-preflight.sh '{"tool_name":"Bash","tool_input":{"command":"git status"}}'
assert_pass "a non-push command: passes silently"

echo "── check-governance-drift ──"
printf 'law\n' > "$REPO/docs/constitution.md"; printf 'setup\n' > "$REPO/docs/setup.md"
printf -- '---\nsetup_hash: "null"\n---\n' > "$REPO/.context/governance_snapshot.md"
run_hook check-governance-drift.sh '{"tool_name":"Edit"}'
assert_context "malformed snapshot (no constitution_hash): said through the envelope, never silent" "no constitution_hash"
run_hook check-governance-drift.sh '{not json'
if [ "$RC" -eq 0 ]; then ok "drift hook survives a malformed payload"; else bad "drift hook failed on malformed payload (rc=$RC)"; fi
printf -- '---\nconstitution_hash: "deadbeef"\nsetup_hash: "null"\ndcs_hash: "null"\n---\n' > "$REPO/.context/governance_snapshot.md"
run_hook check-governance-drift.sh '{"tool_name":"Edit"}'
assert_context "stale snapshot: the warning reaches the model through the envelope (exit 0, never blocks)" "Governance snapshot drift"
if [ "$RC" -eq 0 ]; then ok "drift warning never blocks"; else bad "drift warning blocked (rc=$RC)"; fi
H=$(md5sum "$REPO/docs/constitution.md" | cut -d' ' -f1); HD=$(md5sum "$REPO/.claude/rules/defect-prevention.md" | cut -d' ' -f1)
printf -- '---\nconstitution_hash: "%s"\nsetup_hash: "null"\ndcs_hash: "%s"\n---\n' "$H" "$HD" > "$REPO/.context/governance_snapshot.md"
run_hook check-governance-drift.sh '{"tool_name":"Edit"}'
if [ "$RC" -eq 0 ] && [ -z "$OUT" ]; then ok "fresh snapshot: silent"; else bad "fresh snapshot should be silent" "$OUT"; fi
printf '| DC-99 | `runtime` | x | — | `*` | DEV | LOW |\n' >> "$REPO/.claude/rules/defect-prevention.md"
run_hook check-governance-drift.sh '{"tool_name":"Edit"}'
assert_context "catalog edited: dcs_hash drift is reported too" "defect-prevention.md"

echo "── deliver-governance (law at the point of edit) ──"
run_hook deliver-governance.sh '{"tool_name":"Edit","tool_input":{"file_path":"src/app/models.py"},"session_id":"s1"}'
assert_context "editing src/**: the runtime family and its defect classes are DELIVERED through the envelope" "DC-18"
if printf '%s' "$OUT" | grep -qF 'DC-29' && ! printf '%s' "$OUT" | grep -qF 'DC-27'; then ok "universal DC delivered, unrelated family (data) not delivered — narrowed to the file"; else bad "narrowing by path failed" "$OUT"; fi
BYTES=${#OUT}; if [ "$BYTES" -le 6000 ]; then ok "delivery within budgets.pre_edit ($BYTES B)"; else bad "delivery over budget ($BYTES B)"; fi
run_hook deliver-governance.sh '{"tool_name":"Edit","tool_input":{"file_path":"src/app/models.py"},"session_id":"s1"}'
assert_context "same set again in the same session: one-line pointer, not the payload" "delivered=\"earlier-this-session\""
run_hook deliver-governance.sh '{"tool_name":"Edit","tool_input":{"file_path":"db/migrations/001.sql"},"session_id":"s1"}'
assert_context "editing a migration: the data family is delivered" "DC-27"
run_hook deliver-governance.sh "$(printf '{"tool_name":"Edit","tool_input":{"file_path":"%s/src/abs.py"},"session_id":"s6"}' "$REPO")"
assert_context "an absolute file_path (the real payload shape) is resolved to the repo-relative path" 'paths="src/abs.py"'
run_hook deliver-governance.sh '{"tool_name":"Write","tool_input":{"file_path":"README.md"},"session_id":"s2"}'
assert_context "a path no family governs: universal defect classes (paths *) are still delivered, never silent" "DC-29"
if printf '%s' "$OUT" | grep -qF 'paths=\"README.md\"' && ! printf '%s' "$OUT" | grep -qF 'DC-18'; then ok "no path-bound class leaks to README.md"; else bad "path-bound classes leaked to README.md" "$OUT"; fi
run_hook deliver-governance.sh '{not json'
if [ "$RC" -eq 0 ] && [ -z "$OUT" ]; then ok "malformed hook payload: silent pass, never blocks"; else bad "malformed payload should pass silently (rc=$RC)" "$OUT"; fi
cp "$REPO/config/quality.json" "$SANDBOX/quality.bak"; printf '{"budgets": {}}' > "$REPO/config/quality.json"
run_hook deliver-governance.sh '{"tool_name":"Edit","tool_input":{"file_path":"src/x.py"},"session_id":"s4"}'
assert_context "reader present but unable to run (missing budgets.pre_edit): the FAILURE is delivered, never a silent 0 B" "governance delivery failed"
if [ "$RC" -eq 0 ]; then ok "a broken reader never blocks the edit"; else bad "broken reader blocked (rc=$RC)"; fi
cp "$SANDBOX/quality.bak" "$REPO/config/quality.json"
printf 'def (broken\n' > "$REPO/scripts/gates/common.py"
run_hook deliver-governance.sh '{"tool_name":"Edit","tool_input":{"file_path":"src/x.py"},"session_id":"s5"}'
assert_context "reader package broken (SyntaxError): the reason delivered is the reader's own line, not a traceback" "package is missing or broken (SyntaxError"
cp "$ROOT/scripts/gates/common.py" "$REPO/scripts/gates/common.py"
rm -rf "$REPO/scripts/gate.py"
run_hook deliver-governance.sh '{"tool_name":"Edit","tool_input":{"file_path":"src/x.py"},"session_id":"s3"}'
if [ "$RC" -eq 0 ] && [ -z "$OUT" ]; then ok "reader missing: silent pass, never blocks"; else bad "reader missing should pass silently (rc=$RC)" "$OUT"; fi

echo "── channel audit over every shipped hook ──"
for h in "$HOOKS"/*.sh; do
  n=$(basename "$h")
  if grep -vE '^[[:space:]]*#' "$h" | grep -qE '\bexit 1\b'; then bad "$n: still exits 1 somewhere (exit 1 does not block a PreToolUse tool call)"; else ok "$n: never exits 1"; fi
done
if [ "$(python3 -c "import json;d=json.load(open('$ROOT/.context/templates/setup/claude/settings.json'));print(sum(1 for g in d['hooks']['PreToolUse'] for h in g['hooks'] if 'deliver-governance' in h['command']))")" = "1" ]; then ok "deliver-governance wired on PreToolUse Edit|Write in the template settings"; else bad "deliver-governance not wired"; fi
if diff -rq "$ROOT/.claude/hooks" "$HOOKS" >/dev/null; then ok "meta hooks byte-identical to the template hooks"; else bad "meta hooks drifted from the template"; fi

echo; echo "test-hooks: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
