#!/usr/bin/env python3
# Generated by Phase: IMPLEMENT | Feature: EVOL-052
"""Build the Product Owner package for a Claude Desktop project.

Subproduct, not product: reads the repository, assembles a staging tree OUTSIDE it and
zips it. It never writes into the repository and never calls a tracker.

Package shape:
  00-core/           distilled product model: product sheet, feature catalogue, closed
                     vocabulary (glossary), route map, roadmap
  10-design-system/  vision artefacts, tokens, component base (registry joined with the
                     codebase inventory) and one preview card per component
  20-features/       raw CODESIGN annexes, one folder per specified feature
  30-templates/      evolution-request + manifest templates and the PO-safe artefact templates

Design-system cards come from code when the project configures a rebuild tool, per
component, and from the vision otherwise. The tool is the project's; this file names none.

Usage:
    python3 build_po_package.py                       # package from the configured project
    python3 build_po_package.py --roadmap roadmap.json
    python3 build_po_package.py --mode ds-only --rebuild --check-drift --out DIR

Exit codes: 0 built · 1 drift found under --strict · 2 usage / IO / configuration error.
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import re
import shlex
import shutil
import string
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import po_lib as L  # noqa: E402

HERE = Path(__file__).resolve().parent
LANGUAGE_NAMES = {"en": "English", "es": "Spanish"}
CARD_MARKER_RE = re.compile(r'\A\s*<!--\s*@dsCard\b([^>]*)-->')
WORKFLOW_PATH = ".github/workflows/design-system-rebuild.yml"
CODESIGN_TEMPLATES = (
    "gherkin_master_template.feature", "mock-template.html",
    "mock-feature-content-template.html", "app-shell-template.html",
)
STEP_FIELDS = ("Persona", "Does", "Feels", "Pain", "Ease")


class Build:
    """Everything one run needs, resolved once."""

    def __init__(self, repo: Path, cfg: dict, out: Path, roadmap: list[dict]) -> None:
        self.repo, self.cfg, self.roadmap = repo, cfg, roadmap
        self.language = (cfg["project"].get("language") or "en").lower()
        self.warnings: list[str] = []
        self.features = L.spec_features(repo, cfg)
        self.package_id = f"{L.slugify(cfg['project']['name']) or 'project'}-po-package-" \
                          f"{datetime.date.today().strftime('%Y%m%d')}"
        self.stage = out / self.package_id

    def warn(self, message: str) -> None:
        self.warnings.append(message)
        print(f"  WARNING: {message}", file=sys.stderr)

    def write(self, rel: str, text: str) -> None:
        path = self.stage / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


# ── 00-core ──────────────────────────────────────────────────────────────────


def _journey(build: Build, feature_id: str) -> str:
    path = build.repo / build.cfg["features"]["spec_root"] / feature_id / "user_journey.md"
    return L.split_frontmatter(L.read_text(path))[1]


def _steps(body: str) -> list[dict]:
    steps: list[dict] = []
    for match in re.finditer(r"^### Paso (\d+)\s*\n(.*?)(?=^###? |\Z)", body, re.M | re.S):
        fields = dict(re.findall(r"^- \*\*([^:*]+):\*\*\s*(.*)$", match.group(2), re.M))
        steps.append({"n": match.group(1), **{k: fields.get(k, "—").strip() for k in STEP_FIELDS}})
    return steps


def _feature_title(body: str, feature_id: str) -> str:
    match = re.search(r"^# User Journey:\s*\S+\s*[—-]\s*(.+)$", body, re.M)
    return match.group(1).strip() if match else feature_id


def _feature_sheet(build: Build, feature_id: str) -> str:
    body = _journey(build, feature_id)
    vocab = L.journey_vocab(body)
    lines = [f"\n## {feature_id} — {_feature_title(body, feature_id)}\n",
             f"Annex: `20-features/{feature_id}/` · Personas: {', '.join(sorted(vocab['personas'])) or '—'}\n",
             "| Step | Who | What they do | Feels | Pain | What eases it |", "|---|---|---|---|---|---|"]
    for step in _steps(body):
        cells = [step[k].replace("|", "/") for k in STEP_FIELDS]
        lines.append(f"| Paso {step['n']} | {cells[0]} | {cells[1]} | {cells[2]} | {cells[3]} | {cells[4]} |")
    lines += ["", f"Concepts: {', '.join(sorted(vocab['concepts'])) or '—'}  ",
              f"Fields: {', '.join(f'`{f}`' for f in sorted(vocab['fields'])) or '—'}  ",
              f"Rules: {', '.join(sorted(vocab['rules'])) or '—'}"]
    return "\n".join(lines) + "\n"


def build_catalogue(build: Build) -> str:
    head = ["# Feature catalogue\n",
            "Every feature that already has a specification. Derived from the journeys in the "
            "repository — this is what exists, not a proposal.\n"]
    return "\n".join(head) + "".join(_feature_sheet(build, f) for f in build.features)


def _field_meanings(body: str) -> dict[str, str]:
    meanings: dict[str, str] = {}
    sec6 = L.section_body(re.sub(r"<!--.*?-->", "", body, flags=re.S), "## Section 6:")
    for line in sec6.splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if line.strip().startswith("|") and len(cells) >= 2 and not re.fullmatch(r":?-{2,}:?", cells[0]):
            if cells[0].lower() != "field":
                meanings.setdefault(cells[0].strip("` "), cells[1])
    return meanings


def build_glossary(build: Build) -> str:
    names: dict[tuple[str, str], list[str]] = {}
    fields: dict[str, dict] = {}
    for feature_id in build.features:
        body = _journey(build, feature_id)
        vocab = L.journey_vocab(body)
        for kind in ("personas", "concepts", "rules"):
            for name in vocab[kind]:
                names.setdefault((name, kind[:-1]), []).append(feature_id)
        for name, meaning in _field_meanings(body).items():
            entry = fields.setdefault(name, {"meaning": meaning, "features": []})
            entry["features"].append(feature_id)
    lines = ["# Domain glossary — the closed vocabulary\n",
             "Before naming anything, look it up here. If it exists, use that exact name. "
             "Anything not listed is new and must be declared in the evolution request.\n",
             "## Business names\n", "| Name | Kind | Declared in |", "|---|---|---|"]
    lines += [f"| {n} | {k} | {', '.join(sorted(v))} |" for (n, k), v in sorted(names.items())]
    lines += ["", "## Fields\n", "| Field | Meaning | Declared in |", "|---|---|---|"]
    lines += [f"| `{n}` | {e['meaning'].replace('|', '/')} | {', '.join(sorted(e['features']))} |"
              for n, e in sorted(fields.items())]
    if not names and not fields:
        build.warn("the glossary is empty — no journey could be read; the closed-vocabulary rule has nothing to hold")
    return "\n".join(lines) + "\n"


def roadmap_only(build: Build) -> list[dict]:
    specified = set(build.features)
    return [r for r in build.roadmap if isinstance(r, dict) and r.get("id") and r["id"] not in specified]


def build_roadmap(build: Build) -> str:
    lines = ["# Roadmap — features with no specification yet\n",
             "Exported from the project board. Changing these is almost free: nothing is built. "
             "When they are built is decided on the board, never here.\n"]
    items = roadmap_only(build)
    if not items:
        lines.append("_No roadmap export was provided for this package._\n")
    for item in items:
        lines += [f"\n## {item['id']} — {item.get('name', '')}\n", str(item.get("summary", "")).strip(), ""]
        if item.get("body"):
            lines += [str(item["body"]).strip(), ""]
    return "\n".join(lines) + "\n"


def build_product(build: Build) -> str:
    project = build.cfg["project"]
    personas: dict[str, str] = {}
    for feature_id in build.features:
        sec1 = L.section_body(_journey(build, feature_id), "## Section 1:")
        for line in sec1.splitlines():
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) >= 4 and cells[0] not in ("Persona", "") and not cells[0].startswith(("-", ":")):
                personas.setdefault(cells[0], cells[3])
    lines = [f"# {project['name']} — the product in one page\n", f"**Goal.** {project.get('business_goal', '')}\n",
             f"**Scope.** {project.get('scope', '')}\n",
             f"**State.** {len(build.features)} specified feature(s), {len(roadmap_only(build))} on the roadmap.\n",
             "## Who uses it\n", "| Persona | Wants |", "|---|---|"]
    lines += [f"| {name} | {wants.replace('|', '/')} |" for name, wants in sorted(personas.items())]
    notes = HERE / "product-notes.md"
    if notes.exists():
        lines += ["", "## Notes from the team\n", L.read_text(notes).strip()]
    return "\n".join(lines) + "\n"


def build_core(build: Build) -> None:
    build.write("00-core/product.md", build_product(build))
    build.write("00-core/feature-catalogue.md", build_catalogue(build))
    build.write("00-core/domain-glossary.md", build_glossary(build))
    build.write("00-core/roadmap.md", build_roadmap(build))
    nav = build.repo / build.cfg["design_system"]["vision_root"] / "navigation_map.md"
    if nav.exists():
        build.write("00-core/route-map.md", L.split_frontmatter(L.read_text(nav))[1])


# ── 10-design-system ─────────────────────────────────────────────────────────


def build_tokens(build: Build) -> str:
    found: list[tuple[str, str, str]] = []
    for rel in build.cfg["design_system"]["tokens_sources"]:
        source = build.repo / rel
        if not source.exists():
            continue
        for block in re.findall(r":root\s*\{(.*?)\}", L.read_text(source), re.S):
            found += [(n, v.strip(), rel) for n, v in re.findall(r"(--[a-zA-Z0-9-]+)\s*:\s*([^;]+);", block)]
    lines = ["# Design tokens\n", "Never write a raw colour, size or spacing: use the token.\n"]
    if not found:
        lines.append("_No CSS custom properties were found in the configured sources. If the design "
                     "system declares its tokens in a utility-framework config block, read them in "
                     "`style_guide.html`._\n")
        return "\n".join(lines)
    lines += ["| Token | Value | Source |", "|---|---|---|"]
    lines += [f"| `var({n})` | `{v}` | {src} |" for n, v, src in dict.fromkeys(found)]
    return "\n".join(lines) + "\n"


def component_rows(build: Build) -> list[dict]:
    """Registry joined with the codebase inventory. The inventory owns the code truth."""
    inventory = L.inventory_ui_components(build.repo, build.cfg)
    rows = []
    for comp in L.registry_components(build.repo, build.cfg):
        artifact = inventory.get(comp.get("cip_name") or "")
        primitive = f"{artifact['name']} — {artifact.get('path', '')}" if artifact else None
        rows.append({**comp, "primitive": primitive})
    return rows


def build_components(build: Build) -> str:
    lines = ["# Established component base\n",
             "Compose every screen with these. Asking for a new widget when one of these solves the "
             "case is the fastest way to have a proposal cut in review. A component with no code "
             "primitive yet is designed but not built: using it is fine, it is already in the plan.\n",
             "| Component | Status | Code primitive | In the library |", "|---|---|---|---|"]
    rows = component_rows(build)
    for row in rows:
        lines.append(f"| {row.get('name', row.get('id'))} | {row.get('status', '—')} | "
                     f"{row['primitive'] or '— not built yet'} | `{row.get('ds_anchor', '—')}` |")
    if not rows:
        lines.append("| — | — | — | — |")
        build.warn("the component registry is empty — cards will carry no code primitive")
    return "\n".join(lines) + "\n"


def _head_assets(html: str) -> str:
    parts = re.findall(r"<style\b.*?</style>", html, re.S | re.I)
    parts += re.findall(r"<link\b[^>]*>", html, re.I)
    parts += re.findall(r"<script\b[^>]*>.*?</script>", html.split("</head>")[0], re.S | re.I)
    return "\n    ".join(parts)


def _card(build: Build, group: str, title: str, assets: str, inner: str, footer: str) -> str:
    return (f'<!-- @dsCard group="{group}" -->\n<!doctype html>\n<html lang="{build.language}">\n  <head>\n'
            f'    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n'
            f"    <title>{build.cfg['project']['name']} — {title}</title>\n    {assets}\n  </head>\n"
            f"  <body>\n    <main>\n{inner}\n    </main>\n    <!-- {footer} -->\n  </body>\n</html>\n")


def vision_cards(build: Build) -> dict[str, dict]:
    """{id: card} from the vision anchors; whole-file cards when a file carries none."""
    root = build.repo / build.cfg["design_system"]["vision_root"]
    primitives = {r["id"]: r for r in component_rows(build) if r.get("id")}
    cards: dict[str, dict] = {}
    for filename, attr, group, prefix in (("component_library.html", "data-component", "Components", ""),
                                          ("style_guide.html", "data-token-group", "Foundations", "fnd-")):
        source = root / filename
        if not source.exists():
            continue
        html = L.read_text(source)
        blocks = L.scan_sections(html, attr)
        if not blocks:
            build.warn(f"{filename} carries no `{attr}` anchors — one whole-file card is shipped instead")
            blocks = [{"id": L.slugify(Path(filename).stem), "name": Path(filename).stem, "group": group,
                       "html": re.sub(r"(?is).*<body[^>]*>|</body>.*", "", html)}]
        for block in blocks:
            row = primitives.get(block["id"], {})
            if prefix:
                footer = f"Design tokens · {block['id']}"
            elif row.get("primitive"):
                footer = f"Code primitive: {row['primitive']}"
            else:
                footer = f"No code primitive yet (status: {row.get('status', 'not in the registry')})"
            cid = prefix + block["id"]
            cards[cid] = {"id": cid, "name": block["name"] or block["id"], "group": block["group"] or group,
                          "subtitle": footer, "source": "vision",
                          "html": _card(build, block["group"] or group, block["name"], _head_assets(html),
                                        block["html"], footer)}
    return cards


def code_cards(build: Build) -> dict[str, dict]:
    """Cards a project tool rebuilt from code. Assumed contract: HTML files whose first
    line is the design-system card marker, plus an optional compiled manifest."""
    rel = build.cfg["design_system"]["code_cards"].get("dir")
    folder = build.repo / rel if rel else None
    if not folder or not folder.is_dir():
        return {}
    manifest = L.load_json(folder / "_ds_manifest.json", {})
    meta = {Path(c.get("path", "")).name: c for c in (manifest.get("cards") or []) if isinstance(c, dict)}
    cards: dict[str, dict] = {}
    for path in sorted(folder.rglob("*.html")):
        html = L.read_text(path)
        marker = CARD_MARKER_RE.match(html)
        if not marker:
            continue
        group = re.search(r'group="([^"]*)"', marker.group(1))
        info = meta.get(path.name, {})
        cid = L.slugify(path.stem)
        cards[cid] = {"id": cid, "name": info.get("name") or path.stem, "source": "code", "html": html,
                      "group": info.get("group") or (group.group(1) if group else "Components"),
                      "subtitle": info.get("subtitle") or "Rendered from code"}
    return cards


def run_rebuild(build: Build) -> bool:
    """Run the project's rebuild tool. No shell, a timeout, the repo as cwd. Never blocks."""
    conf = build.cfg["design_system"]["code_cards"]
    command = conf.get("rebuild_command")
    if not command:
        build.warn("--rebuild was asked but no rebuild command is configured — vision cards are used")
        return False
    try:
        args = shlex.split(command)
        proc = subprocess.run(args, cwd=build.repo, shell=False, capture_output=True, text=True,
                              timeout=int(conf.get("timeout_s") or 600), check=False)
    except (OSError, ValueError, subprocess.SubprocessError) as exc:
        build.warn(f"the design-system rebuild command could not run ({exc}) — vision cards are used")
        return False
    if proc.returncode != 0:
        build.warn(f"the design-system rebuild command failed (exit {proc.returncode}) — vision cards are used: "
                   f"{(proc.stderr or proc.stdout).strip()[:200]}")
        return False
    return True


def drift(build: Build, from_code: dict[str, dict]) -> list[str]:
    """Card-to-registry drift: the mechanical signal of design-system / build alignment."""
    if not build.cfg["design_system"]["code_cards"].get("dir"):
        return []
    registry = {c["id"]: c for c in L.registry_components(build.repo, build.cfg) if c.get("id")}
    found = [f"code-card-unregistered: «{cid}» is rendered from code but is not in the component registry"
             for cid in sorted(set(from_code) - set(registry))]
    for cid, comp in sorted(registry.items()):
        status = comp.get("status")
        if status == "IMPLEMENTED" and cid not in from_code:
            found.append(f"implemented-without-code-card: «{cid}» is IMPLEMENTED but no card was rendered from code")
        if status in ("DESIGNED", "PLANNED") and cid in from_code:
            found.append(f"candidate-implemented: «{cid}» is {status} yet a card is rendered from code")
    return found


def build_design_system(build: Build, use_code: bool) -> tuple[int, list[str]]:
    ds = build.cfg["design_system"]
    root = build.repo / ds["vision_root"]
    if not root.is_dir():
        build.warn(f"no vision at {ds['vision_root']} — the design-system folder is not shipped")
        return 0, []
    for name in L.VISION_FILES:
        if name.endswith(".html") and (root / name).exists():
            shutil.copy2(root / name, _ensure(build.stage / "10-design-system") / name)
    for rel in ds.get("extra_files") or []:
        if (build.repo / rel).is_file():
            shutil.copy2(build.repo / rel, _ensure(build.stage / "10-design-system") / Path(rel).name)
    build.write("10-design-system/tokens.md", build_tokens(build))
    build.write("10-design-system/components.md", build_components(build))
    from_code = code_cards(build) if use_code else {}
    if not use_code and ds["code_cards"].get("dir"):
        build.warn("code cards are not trusted in this run — drift is not computed")
    cards = {**vision_cards(build), **from_code}  # code wins per component
    for card in cards.values():
        build.write(f"10-design-system/cards/{card['id']}.html", card["html"])
    index = [{"name": c["name"], "path": f"cards/{c['id']}.html", "group": c["group"],
              "subtitle": c["subtitle"], "source": c["source"], "viewport": {"width": 960, "height": 600}}
             for c in cards.values()]
    build.write("10-design-system/_ds_manifest.json", json.dumps({"cards": index}, indent=2, ensure_ascii=False) + "\n")
    return len(cards), (drift(build, from_code) if use_code else [])


def _ensure(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


# ── 20-features, 30-templates, static prose ──────────────────────────────────


def build_features(build: Build) -> None:
    root = build.repo / build.cfg["features"]["spec_root"]
    for feature_id in build.features:
        target = _ensure(build.stage / "20-features" / feature_id)
        for name in ("user_journey.md", "spec.feature", "mock.html", "slice_map.md"):
            if (root / feature_id / name).exists():
                shutil.copy2(root / feature_id / name, target / name)


def build_templates(build: Build, with_vision: bool) -> None:
    source = build.repo / ".context" / "templates" / "codesign"
    target = _ensure(build.stage / "30-templates")
    for name, out in (("user_journey_template.md", "user_journey-TEMPLATE.md"),
                      ("slice_map_template.md", "slice_map-TEMPLATE.md")):
        if (source / name).exists():  # PO-safe cut: the header block is factory-owned
            (target / out).write_text(L.split_frontmatter(L.read_text(source / name))[1].lstrip(), encoding="utf-8")
        elif name.startswith("user_journey"):
            build.warn("the journey template is missing from the repository — the PO has no mould to start from")
    if with_vision or build.features:
        for name in CODESIGN_TEMPLATES:
            if (source / name).exists():
                shutil.copy2(source / name, target / name)


def copy_static(build: Build, with_vision: bool, variables: dict[str, str]) -> None:
    """English is the complete set; the project language overrides file by file."""
    base = HERE / "static" / "en"
    override = HERE / "static" / build.language
    for path in sorted(p for p in base.rglob("*") if p.is_file()):
        rel = path.relative_to(base)
        if not with_vision and rel.name == "PROJECT-INSTRUCTIONS-VISION.md":
            continue
        chosen = override / rel if (override / rel).is_file() else path
        text = L.read_text(chosen)
        try:
            rendered = string.Template(text).substitute(variables)
        except (KeyError, ValueError) as exc:
            raise L.PoPackageError(f"static/{chosen.relative_to(HERE / 'static')} uses an unknown or "
                                   f"malformed build variable: {exc}") from exc
        build.write(rel.as_posix(), rendered)


# ── Runbook freshness, staging, zip ──────────────────────────────────────────


def expected_runbook_section(build: Build) -> str:
    if not build.cfg["design_system"]["code_cards"].get("rebuild_command"):
        return "6A"
    return "6C" if (build.repo / WORKFLOW_PATH).exists() else "6B"


def check_runbook(build: Build) -> None:
    runbook = HERE / "RUNBOOK.md"
    if not runbook.exists():
        return
    stated = re.search(r"^Active design-system section:\s*\*\*(6[ABC])\*\*", L.read_text(runbook), re.M)
    expected = expected_runbook_section(build)
    if stated and stated.group(1) != expected:
        build.warn(f"RUNBOOK.md says section {stated.group(1)} applies, but the configuration and the CI "
                   f"workflow say {expected} — update its 'This project' block")


def staging_root(repo: Path, cli_out: Path | None) -> Path:
    out = (cli_out or Path(os.environ.get("PO_PACKAGE_OUT") or tempfile.gettempdir())).expanduser().resolve()
    if out == repo.resolve() or repo.resolve() in out.parents:
        raise L.PoPackageError(f"The staging folder must be outside the repository (got {out}).")
    return out


def zip_folder(cfg: dict, cli_zip_dir: Path | None, fallback: Path, repo: Path) -> Path:
    configured = cli_zip_dir or (Path(cfg["output"]["zip_dir"]) if cfg["output"].get("zip_dir") else None)
    downloads = Path.home() / "Downloads"
    folder = (configured or (downloads if downloads.is_dir() else fallback)).expanduser().resolve()
    if folder == repo.resolve() or repo.resolve() in folder.parents:
        raise L.PoPackageError(f"The zip folder must be outside the repository (got {folder}).")
    folder.mkdir(parents=True, exist_ok=True)
    return folder


def load_roadmap(path: Path | None) -> list[dict]:
    if not path:
        return []
    data = L.load_json(path, None)
    if not isinstance(data, list):
        raise L.PoPackageError(f"{path} must hold a JSON list of {{id, name, summary}} items.")
    return data


def resolve_mode(cli_mode: str, cfg: dict, repo: Path) -> tuple[bool, bool]:
    """(with_features, with_vision). Non-UI scopes and features-only projects carry no vision."""
    ui = cfg["project"].get("scope") in L.UI_SCOPES
    vision_allowed = ui and cfg.get("mode", "full") == "full"
    if cli_mode == "ds-only":
        return False, True
    if cli_mode == "features":
        return True, False
    if cli_mode == "vision":
        return False, vision_allowed
    return True, vision_allowed


# ── CLI ──────────────────────────────────────────────────────────────────────


def _parse(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build the Product Owner package (reads the repo, writes outside it).")
    parser.add_argument("--repo", help="repository root (default: PO_PACKAGE_REPO, then git toplevel)")
    parser.add_argument("--config", type=Path, help="config file (default: next to this script)")
    parser.add_argument("--out", type=Path, help="staging folder, outside the repo (default: PO_PACKAGE_OUT, then the system temp folder)")
    parser.add_argument("--zip-dir", type=Path, help="where the zip lands (default: config, then ~/Downloads, then --out)")
    parser.add_argument("--roadmap", type=Path, help="roadmap export: a JSON list of {id, name, summary}")
    parser.add_argument("--mode", choices=("auto", "vision", "features", "ds-only"), default="auto")
    parser.add_argument("--rebuild", action="store_true", help="run the configured design-system rebuild command first")
    parser.add_argument("--check-drift", action="store_true", help="report card-to-registry drift")
    parser.add_argument("--strict", action="store_true", help="with --check-drift: exit 1 when drift is found")
    parser.add_argument("--no-zip", action="store_true", help="leave the staging tree only")
    return parser.parse_args(argv)


def run(args: argparse.Namespace) -> int:
    repo = L.resolve_repo(args.repo)
    cfg = L.load_config(args.config)
    if cfg.get("mode") == "off":
        raise L.PoPackageError("The PO package is switched off for this project (mode: off).")
    out = staging_root(repo, args.out)
    build = Build(repo, cfg, out, load_roadmap(args.roadmap))
    shutil.rmtree(build.stage, ignore_errors=True)
    build.stage.mkdir(parents=True)
    check_runbook(build)
    with_features, with_vision = resolve_mode(args.mode, cfg, repo)
    use_code = run_rebuild(build) if args.rebuild else bool(cfg["design_system"]["code_cards"].get("dir"))
    cards, drifted = build_design_system(build, use_code) if with_vision else (0, [])
    if args.mode != "ds-only":
        variables = {"project_name": cfg["project"]["name"], "business_goal": cfg["project"].get("business_goal", ""),
                     "project_scope": cfg["project"].get("scope", ""),
                     "po_language_name": LANGUAGE_NAMES.get(build.language, build.language),
                     "n_specified": str(len(build.features)), "n_roadmap": str(len(roadmap_only(build))),
                     "package_id": build.package_id}
        build_core(build)
        if with_features:
            build_features(build)
        build_templates(build, with_vision)
        copy_static(build, with_vision, variables)
        build.write("PACKAGE.json", json.dumps({"package_id": build.package_id, "mode": args.mode,
                                               "with_vision": with_vision, "features": build.features}, indent=2) + "\n")
    print(f"staging: {build.stage}")
    print(f"features: {len(build.features)} · roadmap: {len(roadmap_only(build))} · cards: {cards}")
    if not args.no_zip:
        folder = zip_folder(cfg, args.zip_dir, out, repo)
        print(f"zip: {shutil.make_archive(str(folder / build.package_id), 'zip', build.stage.parent, build.stage.name)}")
    if args.check_drift:
        print(f"drift: {len(drifted)} finding(s)")
        for line in drifted:
            print(f"  · {line}")
        if drifted and args.strict:
            return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    try:
        return run(_parse(argv))
    except L.PoPackageError as exc:
        print(f"Cannot build the package: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
