#!/usr/bin/env python3
# Generated by Phase: IMPLEMENT | Feature: EVOL-052
"""Golden fixtures for the validator self-test and for `--emit-fixture` (which the framework's
synthetic-materialisation test, scripts/test-po-package.sh, builds its sandbox project from).

An invented, neutral domain (table booking). No project data lives here.

Two trees are emitted:
  repo/    a tiny materialised project: one specified feature (FEAT-998), an approved
           vision, a component registry, a codebase inventory, a roadmap export, one
           CODESIGN template loading an allowed host, and a copy of the journey gate
  return/  a golden PO return: MANIFEST.yaml + VISION/ + FEAT-999/ (a roadmap feature)
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

FIXTURE_CONFIG: dict = {
    "project": {
        "name": "Fixture Project",
        "business_goal": "Guests book a table without calling the venue.",
        "scope": "full-stack",
        "language": "en",
    },
    "mode": "full",
    "features": {"spec_root": "docs/spec", "id_pattern": r"^FEAT-\d{3,}$", "include": [], "exclude": []},
    "mock": {"allowed_external_hosts": []},
}

JOURNEY_FRONTMATTER = """---
status: APPROVED
feature_id: "{fid}"
scope: {scope}
schemas_version: 1
iteration: 1
iterations: []
---

"""

JOURNEY_BODY = """# User Journey: {fid} — Table booking

## Section 0: Decision History

| # | Date | Concern | Question | Options | Decision | Rationale |
|---|------|-----|----------|---------|----------|-----------|
| 1 | 2026-01-01 | PO | — | — | — | — |

## Section 1: Personas

| Persona | Type | Knows | Wants | Context |
|---------|------|-------|-------|---------|
| Guest | Human | The venue and the day they want | A confirmed table | Arrives from the venue page |

## Section 2: Journey Steps

```mermaid
journey
    title Guest — Table booking
    section Book
      Pick a day: 4: Guest
      Confirm the booking: 5: Guest
```

### Paso 1

- **Persona:** Guest
- **Goal:** Find a day with a free table
- **Does:** Picks a day from the open days
- **Sees:** The chosen day marked as selected
- **Feels:** 4/5 — confident, the open days are obvious
- **Pain:** —
- **Ease:** Closed days are not selectable
- **BDD Scenario:** Guest picks an available day
- **Mock Action:** {mock1}

### Paso 2

- **Persona:** Guest
- **Goal:** Leave with a confirmed table
- **Does:** Confirms the booking
- **Sees:** A confirmation with the day and the party size
- **Feels:** 5/5 — relieved, nothing else to do
- **Pain:** —
- **Ease:** One confirmation step, no account needed
- **BDD Scenario:** Guest confirms the booking
- **Mock Action:** {mock2}

## Section 3: Paths

- **Path Happy** (Guest): Paso 1 → Paso 2

## Section 4: Pain & Emotion Map

| Where (Paso) | Pain | Target emotion | Why here |
|--------------|------|----------------|----------|
| Paso 1 | Guessing which days are open | Confidence | A guest who doubts leaves |

## Section 5: Actions & Outcomes

| # | When the persona… (ref Paso) | The business guarantees… | Ref |
|---|------------------------------|--------------------------|-----|
| A1 | confirms the booking (Paso 2) | The table is held for the guest | Paso 2 |

## Section 6: Business Fields

### Booking

| Field | Meaning | Required | Allowed values (plain language) | Example |
|-------|---------|----------|--------------------------------|---------|
| booking_day | The day the guest will come | Yes | Any open day | next Friday |
| party_size | How many people will come | Yes | One to twelve people | 4 |

## Section 7: Business Rules

| # | Rule ID | When… | Then the business… | Scenario Ref |
|---|---------|-------|--------------------|--------------|
| P1 | RULE-BOOK-01 | The day is fully booked | Offers the next open day | Guest picks a fully booked day |

## Section 8: Third Parties & Guarantees

| Party | What is exchanged | Business guarantee | Notes |
|-------|-------------------|--------------------|-------|
| None | — | — | — |

## Traceability Matrix

| Paso | Persona | BDD Scenario | Mock Action | Concepts | Rules |
|------|---------|--------------|-------------|----------|-------|
| 1 | Guest | Guest picks an available day | {mock1} | Booking | P1 |
| 2 | Guest | Guest confirms the booking | {mock2} | Booking | — |
"""

SPEC = """Feature: Table booking

  Scenario: Guest picks an available day
    Given the venue has open days
    When the guest picks a day
    Then the day is shown as selected

  Scenario: Guest confirms the booking
    Given the guest picked a day
    When the guest confirms the booking
    Then the table is held for the guest

  Scenario: Guest picks a fully booked day
    Given the day the guest wants is fully booked
    When the guest picks that day
    Then the next open day is offered

  Scenario: Guest opens the booking with no open days
    Given the venue has no open days
    When the guest opens the booking
    Then the guest is told there is nothing to book yet
"""

MOCK = """<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>Table booking</title>
<style>:root{--color-primary:#1f2937}.imp-step{padding:1rem}</style></head>
<body><main>
<section class="imp-step" id="step-1"><h1>Pick a day</h1>
  <div data-state="default" class="active"><label for="size">Party size</label><input id="size" type="number" min="1" max="12"><button type="button">Friday</button></div>
  <div data-state="empty"><p>There is nothing to book yet.</p></div>
  <div data-state="loading"><p>Looking for open days…</p></div>
  <div data-state="error"><p>That day is fully booked. The next open day is Saturday.</p></div>
</section>
<section class="imp-step" id="step-2"><h2>Confirm</h2>
  <div data-state="default" class="active"><p>Friday, 4 people.</p><button type="button">Confirm booking</button></div>
  <div data-state="empty"><p>Pick a day first.</p></div>
  <div data-state="loading"><p>Holding your table…</p></div>
  <div data-state="error"><p>We could not hold the table. Nothing was booked.</p></div>
</section>
</main></body></html>
"""

FEATURE_ERQ = """---
erq_id: "ERQ-{fid}-01"
target: "feature"
feature_id: "{fid}"
feature_name: "Table booking"
feature_state: "roadmap"
scope: "{scope}"
author: "Selftest"
date: "2026-01-01"
based_on_package: "fixture-po-package-20260101"
classification: "delta"
changes:
  - id: "C1"
    kind: "new_step"
    target: "Paso 2"
    summary: "A single confirmation step closes the booking."
    business_reason: "Guests abandon when confirmation takes more than one step."
    reuse_checked: "Booking, booking_day and party_size already exist in the glossary; reused as is."
    impact: "delta"
new_names: []
open_questions: []
---

# Evolution request

## What problem are we solving

Guests call the venue because they cannot tell whether the booking went through.
"""

VISION_ERQ = """---
erq_id: "ERQ-VISION-01"
target: "vision"
author: "Selftest"
date: "2026-01-01"
based_on_package: "fixture-po-package-20260101"
classification: "delta"
changes:
  - id: "C1"
    kind: "usability"
    target: "component_library.html"
    summary: "The card gains a compact variant."
    business_reason: "Lists of bookings do not fit on a phone with the current card."
    reuse_checked: "Card already exists in the registry; this is a variant, not a new component."
    impact: "delta"
new_components: []
open_questions: []
---

# Evolution request — design system
"""

VISION_MD = """# Global UX Vision — Fixture Project

Calm, legible, one primary action per screen.
"""

APP_SHELL = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>App shell</title>
<style>:root{--color-primary:#1f2937;--space-2:0.5rem}</style></head>
<body><header><a href="#main">Skip to content</a></header>
<nav aria-label="Primary"><a href="#bookings">Bookings</a></nav>
<main id="main"><h1>Content</h1></main></body></html>
"""

STYLE_GUIDE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Style guide</title>
<style>:root{--color-primary:#1f2937;--color-surface:#ffffff;--radius-md:8px}</style></head>
<body><main><h1>Style guide</h1>
<section id="colors" data-token-group="Colors"><h2>Colors</h2><p>Primary and surface.</p></section>
<section id="radius" data-token-group="Borders"><h2>Radius</h2><p>One radius.</p></section>
</main></body></html>
"""

PAGE_TEMPLATES = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Page templates</title></head>
<body><main><h1>Page templates</h1><section id="list"><h2>List</h2></section></main></body></html>
"""

COMPONENT_LIBRARY = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Component library</title>
<style>:root{--color-primary:#1f2937}</style></head>
<body><main><h1>Component library</h1>
<section id="button" data-component="Button" data-group="Components"><h2>Button</h2>
  <section><h3>States</h3><button type="button">Default</button></section>
</section>
<section id="card" data-component="Card" data-group="Components"><h2>Card</h2><div>Body</div></section>
<section id="input" data-component="Input" data-group="Components"><h2>Input</h2>
  <label for="demo">Name</label><input id="demo" type="text"></section>
</main></body></html>
"""

NAVIGATION_MAP = """# Navigation map

- Bookings → Booking detail
- Bookings → New booking
- Settings
"""

VISION_BODIES = {
    "vision.md": VISION_MD,
    "app_shell.html": APP_SHELL,
    "style_guide.html": STYLE_GUIDE,
    "page_templates.html": PAGE_TEMPLATES,
    "component_library.html": COMPONENT_LIBRARY,
    "navigation_map.md": NAVIGATION_MAP,
}

MANIFEST = """package:
  author: "Selftest"
  date: "2026-01-01"
  based_on_package: "fixture-po-package-20260101"
  summary: "Booking confirmation and a compact card."

vision:
  erq: "VISION/ERQ.md"
  classification: "delta"
  self_checked: true

features:
  - feature_id: "FEAT-999"
    feature_name: "Table booking"
    feature_state: "roadmap"
    erq: "FEAT-999/ERQ.md"
    classification: "delta"
    self_checked: true

reviewed_no_change: []
"""

REGISTRY = {
    "$schema": "component_registry_v1",
    "version": "1.0.0",
    "last_updated": "2026-01-01T00:00:00Z",
    "catalog_feature": None,
    "components": [
        {"id": "button", "name": "Button", "group": "Components",
         "ds_anchor": "component_library.html#button", "origin": "vision", "cip_name": "Button",
         "status": "IMPLEMENTED", "backlog_ref": None, "introduced_by": "UX-VISION"},
        {"id": "card", "name": "Card", "group": "Components",
         "ds_anchor": "component_library.html#card", "origin": "vision", "cip_name": None,
         "status": "DESIGNED", "backlog_ref": None, "introduced_by": "UX-VISION"},
        {"id": "input", "name": "Input", "group": "Components",
         "ds_anchor": "component_library.html#input", "origin": "vision", "cip_name": None,
         "status": "DESIGNED", "backlog_ref": None, "introduced_by": "UX-VISION"},
    ],
}

INVENTORY = {
    "version": "1.0.0",
    "bootstrap_mode": "greenfield",
    "artifacts": [
        {"name": "Button", "type": "ui_component", "module": "ui", "path": "src/ui/button",
         "feature_ids": ["FEAT-998"], "responsibility": "Primary and secondary actions",
         "status": "IMPLEMENTED"},
        {"name": "BookingService", "type": "service", "module": "booking",
         "path": "src/booking/service", "feature_ids": ["FEAT-998"],
         "responsibility": "Holds tables", "status": "IMPLEMENTED"},
    ],
}

ROADMAP = [
    {"id": "FEAT-999", "name": "Table booking", "summary": "Guests book and confirm a table on their own."},
]

TEMPLATE_WITH_ALLOWED_HOST = """<!doctype html>
<html lang="en"><head><script src="https://allowed.example/lib.js"></script></head><body></body></html>
"""


def journey(fid: str, scope: str = "full-stack", with_frontmatter: bool = False) -> str:
    ui = scope in ("full-stack", "frontend-only")
    body = JOURNEY_BODY.format(fid=fid, mock1="#step-1" if ui else "—", mock2="#step-2" if ui else "—")
    return (JOURNEY_FRONTMATTER.format(fid=fid, scope=scope) if with_frontmatter else "") + body


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def emit_repo(root: Path, grammar_script: Path | None) -> Path:
    """A tiny materialised project. Returns its root."""
    repo = root / "repo"
    feature = repo / "docs" / "spec" / "FEAT-998"
    _write(feature / "user_journey.md", journey("FEAT-998", with_frontmatter=True))
    _write(feature / "spec.feature", SPEC)
    _write(feature / "mock.html", MOCK)
    for name, body in VISION_BODIES.items():
        prefix = "---\nstatus: APPROVED\nversion: 1\n---\n\n" if name == "vision.md" else ""
        _write(repo / "docs" / "ux" / "vision" / name, prefix + body)
    _write(repo / "docs" / "ux" / "component-registry.json", json.dumps(REGISTRY, indent=2))
    _write(repo / "config" / "codebase_inventory.json", json.dumps(INVENTORY, indent=2))
    _write(repo / "roadmap.json", json.dumps(ROADMAP, indent=2))
    _write(repo / ".context" / "templates" / "codesign" / "mock-template.html", TEMPLATE_WITH_ALLOWED_HOST)
    if grammar_script and grammar_script.exists():
        target = repo / "scripts" / "check-journey-grammar.sh"
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(grammar_script, target)
    return repo


def emit_return(root: Path, with_vision: bool = True, scope: str = "full-stack") -> Path:
    """A golden PO return. Returns its root."""
    ret = root / "return"
    feature = ret / "FEAT-999"
    _write(feature / "ERQ.md", FEATURE_ERQ.format(fid="FEAT-999", scope=scope))
    _write(feature / "user_journey.md", journey("FEAT-999", scope=scope))
    _write(feature / "spec.feature", SPEC)
    if scope in ("full-stack", "frontend-only"):
        _write(feature / "mock.html", MOCK)
    manifest = MANIFEST
    if with_vision:
        _write(ret / "VISION" / "ERQ.md", VISION_ERQ)
        for name, body in VISION_BODIES.items():
            _write(ret / "VISION" / name, body)
    else:
        manifest = manifest.replace(
            'vision:\n  erq: "VISION/ERQ.md"\n  classification: "delta"\n  self_checked: true\n\n', "")
    _write(ret / "MANIFEST.yaml", manifest)
    return ret


def emit_fixture(root: Path, grammar_script: Path | None) -> tuple[Path, Path]:
    root.mkdir(parents=True, exist_ok=True)
    return emit_repo(root, grammar_script), emit_return(root)
