#!/usr/bin/env python3
# Generated by Phase: IMPLEMENT | Feature: EVOL-052
"""Shared helpers for the PO package subproduct (generator + return validator).

Subproduct, not product: deliverable-generation tooling imported by no framework or
product module. It reads the repository and never writes into it.

Nothing here is tied to a product or a tracker, and the only stack knowledge is the
utility framework the framework's own CODESIGN templates load:
  · the closed vocabulary comes from the journey-first grammar (Sections 1, 6, 7)
  · components come from `<section data-component>` anchors in the vision library
  · allowed external hosts come from the framework's own CODESIGN templates + config
"""

from __future__ import annotations

import errno
import json
import os
import re
import subprocess
import sys
import traceback
import zipfile
from html.parser import HTMLParser
from pathlib import Path, PurePosixPath
from typing import Callable
from urllib.parse import urlparse

HERE = Path(__file__).resolve().parent
CONFIG_NAME = "po-package.config.json"

MAX_ZIP_ENTRIES = 2000
MAX_MEMBER_BYTES = 20 * 1024 * 1024
MAX_TOTAL_BYTES = 200 * 1024 * 1024
# The only system-call failures a PO archive can cause by itself, through the names and offsets it declares:
# a name too long, a file where a folder must be (or the reverse), a seek to an offset it made up. A corrupt
# compressed stream raises an OSError with no errno at all. Every other errno is the operator's machine.
ARCHIVE_ERRNOS = frozenset(getattr(errno, name) for name in ("ENAMETOOLONG", "ENOTDIR", "EISDIR", "EEXIST", "EINVAL")
                           if hasattr(errno, name))

PACKAGE_MODES = ("full", "features-only", "off")
VOCAB_KINDS = ("personas", "concepts", "fields", "rules")
UI_SCOPES = ("full-stack", "frontend-only")
ALL_SCOPES = UI_SCOPES + ("backend-only", "integration")

VISION_FILES = (
    "vision.md",
    "app_shell.html",
    "style_guide.html",
    "page_templates.html",
    "component_library.html",
    "navigation_map.md",
)

DEFAULT_CONFIG: dict = {
    "project": {"name": "Project", "business_goal": "", "scope": "full-stack", "language": "en"},
    "mode": "full",
    "features": {
        "spec_root": "docs/spec",
        "id_pattern": r"^[A-Z][A-Z0-9]*-\d{3,}$",
        "include": [],
        "exclude": [],
    },
    "design_system": {
        "vision_root": "docs/ux/vision",
        "component_registry": "docs/ux/component-registry.json",
        "codebase_inventory": "config/codebase_inventory.json",
        "tokens_sources": ["docs/ux/vision/style_guide.html"],
        "extra_files": [],
        "code_cards": {"dir": None, "rebuild_command": None, "timeout_s": 600},
    },
    "mock": {"allowed_external_hosts": []},
    "output": {"zip_dir": None},
}


class PoPackageError(Exception):
    """A condition the operator must fix. The message is plain language, never a trace."""


# ── Repository and configuration ─────────────────────────────────────────────


def resolve_repo(cli_repo: str | None = None) -> Path:
    """--repo, then PO_PACKAGE_REPO, then the git toplevel of this file."""
    candidate = cli_repo or os.environ.get("PO_PACKAGE_REPO")
    if candidate:
        path = Path(candidate).expanduser().resolve()
        if not path.is_dir():
            raise PoPackageError(f"The repository path does not exist: {path}")
        return path
    try:
        out = subprocess.run(
            ["git", "-C", str(HERE), "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, timeout=15, check=False,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise PoPackageError(f"Cannot locate the repository (git unavailable: {exc}). Pass --repo.") from exc
    if out.returncode != 0 or not out.stdout.strip():
        raise PoPackageError("Cannot locate the repository. Pass --repo or set PO_PACKAGE_REPO.")
    return Path(out.stdout.strip())


def merge_config(base: dict, over: dict) -> dict:
    out = dict(base)
    for key, value in over.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = merge_config(out[key], value)
        else:
            out[key] = value
    return out


def _check_shapes(defaults: dict, data: dict, name: str, prefix: str = "") -> None:
    """A mapping, a list or a text in the defaults must stay one: a wrong shape fails silently later."""
    for key, default in defaults.items():
        if key not in data or default is None:
            continue
        value, label = data[key], f"{prefix}{key}"
        for kind, word in ((dict, "an object"), (list, "a list"), (str, "a string")):
            if isinstance(default, kind) and not isinstance(value, kind):
                raise PoPackageError(f"{name}: `{label}` must be {word}.")
        if isinstance(default, dict):
            _check_shapes(default, value, name, f"{label}.")


def load_config(path: Path | None = None) -> dict:
    """Defaults overlaid with the project config. Unresolved placeholders are an error."""
    cfg_path = path or (HERE / CONFIG_NAME)
    if not cfg_path.exists():
        raise PoPackageError(f"Missing configuration file: {cfg_path}")
    raw = cfg_path.read_text(encoding="utf-8")
    leftover = sorted(set(re.findall(r"\{\{[A-Z0-9_]+\}\}", raw)))
    if leftover:
        raise PoPackageError(
            f"{cfg_path.name} still carries unresolved placeholders ({', '.join(leftover)}). "
            "SETUP --generate resolves them; outside a materialised project pass --config."
        )
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise PoPackageError(f"{cfg_path.name} is not valid JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise PoPackageError(f"{cfg_path.name} must hold a JSON object.")
    _check_shapes(DEFAULT_CONFIG, data, cfg_path.name)
    cfg = merge_config(DEFAULT_CONFIG, data)
    if cfg.get("mode") not in PACKAGE_MODES:
        raise PoPackageError(f"{cfg_path.name}: `mode` must be one of {', '.join(PACKAGE_MODES)} (got {cfg.get('mode')!r}).")
    cards = cfg["design_system"]["code_cards"]
    for key in ("dir", "rebuild_command"):  # tolerate the string "null" where JSON null was meant
        if isinstance(cards.get(key), str) and cards[key].strip().lower() in ("", "null", "none"):
            cards[key] = None
    return cfg


def feature_id_re(cfg: dict) -> re.Pattern[str]:
    try:
        return re.compile(cfg["features"]["id_pattern"])
    except (re.error, TypeError) as exc:
        raise PoPackageError(f"features.id_pattern is not a valid pattern: {exc}") from exc


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


# ── Journey-first grammar: frontmatter and closed vocabulary ─────────────────

_FM_RE = re.compile(r"\A---\n(.*?)\n---\n?", re.S)
_COMMENT_RE = re.compile(r"<!--.*?-->", re.S)


def split_frontmatter(text: str) -> tuple[str, str]:
    """(frontmatter body, rest). Frontmatter is factory-owned; a PO return may omit it."""
    match = _FM_RE.match(text.lstrip("﻿"))
    if not match:
        return "", text
    return match.group(1), text[match.end():]


def frontmatter_value(frontmatter: str, key: str) -> str | None:
    match = re.search(rf"^{re.escape(key)}:\s*\"?([^\"#\n]*?)\"?\s*(?:#.*)?$", frontmatter, re.M)
    return match.group(1).strip() if match and match.group(1).strip() else None


def section_body(text: str, heading_prefix: str) -> str:
    """Body of the H2 whose line starts with `heading_prefix`, up to the next H2."""
    out: list[str] = []
    inside = False
    for line in text.splitlines():
        if line.startswith("## "):
            inside = line.startswith(heading_prefix)
            continue
        if inside:
            out.append(line)
    return "\n".join(out)


def strip_comments(text: str) -> str:
    return _COMMENT_RE.sub("", text)


def table_rows(body: str) -> list[list[str]]:
    """Data rows of every markdown table in `body`; header and separator rows dropped."""
    rows: list[list[str]] = []
    seen_separator = False
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped.startswith("|"):
            seen_separator = False
            continue
        cells = [c.strip() for c in stripped.strip("|").split("|")]
        if all(re.fullmatch(r":?-{2,}:?", c) for c in cells if c):
            seen_separator = True
        elif seen_separator:
            rows.append(cells)
    return rows


def _table_column(body: str, index: int) -> list[str]:
    cells = (row[index].strip("` ") for row in table_rows(body) if index < len(row))
    return [cell for cell in cells if cell and cell != "—"]


def journey_vocab(text: str) -> dict[str, set[str]]:
    """Closed vocabulary a journey declares: personas (§1), concepts + fields (§6), rules (§7)."""
    _fm, body = split_frontmatter(text)
    body = strip_comments(body)
    sec6 = section_body(body, "## Section 6:")
    return {
        "personas": set(_table_column(section_body(body, "## Section 1:"), 0)),
        "concepts": {m.group(1).strip() for m in re.finditer(r"^###\s+(.+?)\s*$", sec6, re.M)},
        "fields": set(_table_column(sec6, 0)),
        "rules": set(_table_column(section_body(body, "## Section 7:"), 1)),
    }


def empty_vocab() -> dict[str, set[str]]:
    return {kind: set() for kind in VOCAB_KINDS}


def spec_features(repo: Path, cfg: dict) -> list[str]:
    """Feature ids that have a journey in the repo, honouring include/exclude."""
    root = repo / cfg["features"]["spec_root"]
    pattern = feature_id_re(cfg)
    include = set(cfg["features"].get("include") or [])
    exclude = set(cfg["features"].get("exclude") or [])
    if not root.is_dir():
        return []
    found: list[str] = []
    for entry in sorted(root.iterdir()):
        if not entry.is_dir() or not pattern.match(entry.name):
            continue
        if include and entry.name not in include:
            continue
        if entry.name in exclude:
            continue
        if (entry / "user_journey.md").exists():
            found.append(entry.name)
    return found


def load_glossary(repo: Path, cfg: dict) -> dict[str, set[str]]:
    """Union of the vocabulary of every journey the config selects (id_pattern, include,
    exclude) — read live from the repo. An excluded feature contributes no names."""
    glossary = empty_vocab()
    root = repo / cfg["features"]["spec_root"]
    for feature_id in spec_features(repo, cfg):
        vocab = journey_vocab(read_text(root / feature_id / "user_journey.md"))
        for key in glossary:
            glossary[key] |= vocab[key]
    return glossary


# ── HTML: external references and nesting-safe section scanner ───────────────


_CSS_REF_RE = re.compile(r"""(?:url\(\s*|@import\s+)["']?((?:https?:)?//[^"')\s;]+)""", re.I)
LANDMARKS = ("header", "nav", "main")
# attribute → the tags on which it LOADS something (None = any tag). An <a href> navigates; it loads nothing.
_LOADING_ATTRS = {"src": None, "data-src": None, "poster": None, "data": ("object",),
                  "href": ("link", "base", "image", "use"), "xlink:href": ("image", "use")}
_SRCSET_ATTRS = ("srcset", "imagesrcset")


def _absolute(value: str) -> str | None:
    value = value.strip()
    if value.startswith("//"):
        return "https:" + value
    return value if value.lower().startswith(("http://", "https://")) else None


class _HtmlFacts(HTMLParser):
    """One pass over a page: what it loads and the cheap accessibility signals.

    A parser, not a regex: browsers load unquoted attribute values, `srcset` / `imagesrcset`
    candidates, `<object data>`, a `<base href>`, SVG `<image>` / `<use>` references and
    stylesheet `url()` / `@import` too. Style rules are read where they live (`<style>` blocks
    and `style=` attributes), never in prose. NOT seen, by design of a static read: what a
    script loads at run time and a `<meta http-equiv="refresh">` — WCAG and the sync gate
    look at the rendered page; this is the cheap early net, not the last one."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.refs: list[str] = []
        self.has_lang = False
        self.images_without_alt = 0
        self.landmarks: set[str] = set()
        self._in_style = False

    @staticmethod
    def _candidates(tag: str, attributes: dict) -> list[str]:
        """Every attribute value that would make the browser fetch something for this tag."""
        values = [attributes.get(name) or "" for name, tags in _LOADING_ATTRS.items() if tags is None or tag in tags]
        listed = ",".join(attributes.get(name) or "" for name in _SRCSET_ATTRS)
        candidates = [c.split()[0] for c in listed.split(",") if c.split()]
        return values + candidates + _CSS_REF_RE.findall(attributes.get("style") or "")

    def _loaded(self, tag: str, attributes: dict) -> list[str]:
        return [ref for ref in map(_absolute, self._candidates(tag, attributes)) if ref]

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attributes = dict(attrs)
        self.refs += self._loaded(tag, attributes)
        self._in_style = tag == "style"
        if tag == "html" and (attributes.get("lang") or "").strip():
            self.has_lang = True
        if tag == "img" and "alt" not in attributes:
            self.images_without_alt += 1
        if tag in LANDMARKS:
            self.landmarks.add(tag)

    def handle_endtag(self, tag: str) -> None:
        if tag == "style":
            self._in_style = False

    def handle_data(self, data: str) -> None:
        if self._in_style:
            self.refs += [_absolute(m) or m for m in _CSS_REF_RE.findall(data)]


def html_facts(html: str) -> _HtmlFacts:
    facts = _HtmlFacts()
    facts.feed(html)
    facts.close()
    return facts


def external_refs(html: str) -> list[str]:
    return html_facts(html).refs


def allowed_hosts(repo: Path, cfg: dict) -> set[str]:
    """Hosts the framework's own CODESIGN templates load, plus the project's allowlist.

    Derived at run time so a factory-generated mock can never be red by construction.
    """
    hosts = {h.lower() for h in (cfg["mock"].get("allowed_external_hosts") or [])}
    templates = repo / ".context" / "templates" / "codesign"
    if templates.is_dir():
        for html_file in sorted(templates.glob("*.html")):
            for url in external_refs(read_text(html_file)):
                host = urlparse(url).hostname
                if host:
                    hosts.add(host.lower())
    return hosts


def disallowed_refs(html: str, hosts: set[str]) -> list[str]:
    bad: list[str] = []
    for url in external_refs(html):
        host = (urlparse(url).hostname or "").lower()
        if host not in hosts:
            bad.append(url)
    return bad


class _SectionScanner(HTMLParser):
    """Top-level `<section ATTR=…>` blocks. Nested sections never split a block."""

    def __init__(self, source: str, attr: str) -> None:
        super().__init__(convert_charrefs=True)
        self._source = source
        self._attr = attr
        # HTMLParser counts "\n" only. str.splitlines() also splits on form feed, NEL and
        # U+2028/9 — one of those in the page would shift every later offset.
        self._starts = [0]
        for line in source.split("\n"):
            self._starts.append(self._starts[-1] + len(line) + 1)
        self._depth = 0
        self._open: dict | None = None
        self.blocks: list[dict] = []

    def _offset(self) -> int:
        line, col = self.getpos()
        return self._starts[line - 1] + col

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag != "section":
            return
        if self._open is not None:
            self._depth += 1
            return
        attributes = dict(attrs)
        if self._attr not in attributes:
            return
        name = (attributes.get(self._attr) or "").strip()
        self._open = {
            "id": (attributes.get("id") or "").strip() or slugify(name),
            "name": name or (attributes.get("id") or "").strip(),
            "group": (attributes.get("data-group") or "").strip(),
            "start": self._offset(),
        }
        self._depth = 0

    def handle_endtag(self, tag: str) -> None:
        if tag != "section" or self._open is None:
            return
        if self._depth > 0:
            self._depth -= 1
            return
        close = self._source.find(">", self._offset())
        end = close + 1 if close != -1 else len(self._source)
        block = self._open
        block["html"] = self._source[block.pop("start"):end]
        self.blocks.append(block)
        self._open = None


def scan_sections_full(html: str, attr: str) -> tuple[list[dict], str | None]:
    """(blocks, unclosed). `unclosed` names a top-level section that never closes: the
    browser auto-closes it, the scanner cannot — everything after it is unreadable."""
    scanner = _SectionScanner(html, attr)
    scanner.feed(html)
    scanner.close()
    unclosed = (scanner._open["name"] or scanner._open["id"] or "(unnamed)") if scanner._open else None
    return scanner.blocks, unclosed


def scan_sections(html: str, attr: str) -> list[dict]:
    """[{id, name, group, html}] for each top-level `<section {attr}="…">`."""
    return scan_sections_full(html, attr)[0]


def is_slug(value: str) -> bool:
    """Ids become file names and join keys: lowercase slug, nothing else."""
    return bool(value) and value == slugify(value)


def tokens_declared(html: str) -> bool:
    """Tokens are declared in a root CSS block, or in the `tailwind.config` block of the
    utility framework the CODESIGN templates load."""
    if re.search(r":root\s*\{[^}]*--[a-zA-Z]", html, re.S):
        return True
    return bool(re.search(r"tailwind\.config\s*=", html))


# ── Registry and codebase inventory ──────────────────────────────────────────


def load_json(path: Path, default):
    if not path.exists():
        return default
    try:
        return json.loads(read_text(path))
    except json.JSONDecodeError as exc:
        raise PoPackageError(f"{path} is not valid JSON: {exc}") from exc


def registry_components(repo: Path, cfg: dict) -> list[dict]:
    path = cfg["design_system"]["component_registry"]
    data = load_json(repo / path, {})
    components = data.get("components", []) if isinstance(data, dict) else None
    if not isinstance(components, list) or not all(isinstance(c, dict) for c in components):
        # The operator's own file: a silent filter would read as "empty registry" and as false drift.
        raise PoPackageError(f"{path}: `components` must be a list of entries (see the Component Registry schema).")
    return components


def inventory_ui_components(repo: Path, cfg: dict) -> dict[str, dict]:
    """{name: artifact} for the codebase inventory entries that are UI components."""
    data = load_json(repo / cfg["design_system"]["codebase_inventory"], {})
    artifacts = data.get("artifacts") or [] if isinstance(data, dict) else []
    return {
        a["name"]: a for a in artifacts
        if isinstance(a, dict) and a.get("name") and a.get("type") == "ui_component"
    }


# ── Zip safety ───────────────────────────────────────────────────────────────


def _member_problem(info: zipfile.ZipInfo) -> str | None:
    name = info.filename
    parts = PurePosixPath(name.replace("\\", "/")).parts
    if name.startswith(("/", "\\")) or re.match(r"^[A-Za-z]:", name):
        return f"absolute path: {name}"
    if ".." in parts:
        return f"path escapes the archive: {name}"
    if (info.external_attr >> 16) & 0o170000 == 0o120000:
        return f"symbolic link: {name}"
    if info.file_size > MAX_MEMBER_BYTES:
        return f"oversized member ({info.file_size} bytes): {name}"
    return None


def local_io_fault(exc: BaseException) -> bool:
    """The operator's disk, share, limits or permissions failed: never a finding about the PO's archive."""
    return isinstance(exc, OSError) and exc.errno is not None and exc.errno not in ARCHIVE_ERRNOS


def _content_problems(archive: zipfile.ZipFile, infos: list[zipfile.ZipInfo]) -> list[str]:
    """Read every member without writing it: a password or a damaged member shows here."""
    protected = [i.filename for i in infos if i.flag_bits & 0x1]
    if protected:
        return [f"password-protected member: {protected[0]}"]
    try:
        damaged = archive.testzip()
    except Exception as exc:  # noqa: BLE001 - each decompressor raises its own type (zlib.error, LZMAError, …):
        # this boundary exists to turn an unreadable archive into a finding, so it names none of them
        if local_io_fault(exc):   # a disk or a share failing mid-read is the operator's, never a RED for the PO
            raise PoPackageError(f"Cannot read {archive.filename} ({exc.strerror}). "
                                 "Check the file is still there and readable, then run again.") from exc
        return ["a member cannot be read — the archive is damaged or uses an unsupported compression"]
    return [f"damaged member: {damaged}"] if damaged else []


def zip_problems(zip_path: Path) -> list[str]:
    """Reasons this archive must not be extracted. Empty list = safe to extract."""
    try:
        archive = zipfile.ZipFile(zip_path)
    except OSError as exc:   # permissions, a vanished file, a folder: the operator's machine, not the PO's archive
        raise PoPackageError(f"Cannot read {zip_path}: {exc}") from exc
    except Exception as exc:  # noqa: BLE001 - only the archive's own directory is parsed here (BadZipFile,
        # an unknown zip version, an undecodable name…): whatever it raises is the archive's fault
        return [f"not a readable zip: {exc}"]
    with archive:
        infos = archive.infolist()
        problems = [problem for info in infos if (problem := _member_problem(info))]
        if len(infos) > MAX_ZIP_ENTRIES:
            problems.append(f"too many entries ({len(infos)} > {MAX_ZIP_ENTRIES})")
        if sum(i.file_size for i in infos) > MAX_TOTAL_BYTES:
            problems.append(f"archive expands beyond {MAX_TOTAL_BYTES} bytes")
        return problems or _content_problems(archive, infos)   # contents are read only once size is bounded


def inside_repo(repo: Path, rel: str, label: str) -> Path:
    """A configured path the tool READS must stay inside the repository."""
    path = (repo / rel).resolve()
    if path != repo.resolve() and repo.resolve() not in path.parents:
        raise PoPackageError(f"`{label}` must be a path inside the repository (got {rel}).")
    return path


def cli_main(action: Callable[[], int], prefix: str) -> int:
    """Boundary shared by both tools: a fault of the tool must never read as a verdict.

    Exit 2, plain language (LAW-08). PO_PACKAGE_DEBUG=1 adds the trace; the exit code stays 2."""
    try:
        return action()
    except PoPackageError as exc:
        print(f"{prefix}: {exc}", file=sys.stderr)
    except Exception as exc:  # noqa: BLE001 - the boundary
        if os.environ.get("PO_PACKAGE_DEBUG"):
            traceback.print_exc()
        print(f"{prefix}: the tool itself failed ({type(exc).__name__}: {exc}). This is a tooling fault, "
              "not a finding about the input. Set PO_PACKAGE_DEBUG=1 to see the trace.", file=sys.stderr)
    return 2


PO_LIB_COMPLETE = True   # MUST stay the last line: the tools refuse a copy cut short above it
