#!/usr/bin/env python3
# Generated by Phase: IMPLEMENT | Feature: EVOL-052
"""Self-test of the return validator: a gate that cannot fail is not a gate.

Every check id is exercised on input that must trip it — with the SEVERITY it must carry,
because RED versus GREEN is the validator's whole product — and the golden returns must
produce no finding at all. Hermetic: each case builds its own fixture project in a temp
directory. The only thing taken from the real repository is the journey gate script,
because the point is to prove the validator against the gate projects actually run.
"""

from __future__ import annotations

import ast
import shutil
import stat
import tempfile
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable
from unittest import mock

import po_fixtures as F
import po_lib as L
import validate_po_return as V

Mutation = Callable[[Path, Path], None]
Archive = Callable[[Path], Path]


@dataclass(frozen=True)
class Case:
    name: str
    expect: str | None = None      # check id that must fire; None = the return must be spotless
    severity: str | None = None    # severity that finding must carry (required with `expect`)
    mutate: Mutation | None = None
    message: str | None = None     # substring the finding's message must carry (tells branches apart)
    with_vision: bool = True
    scope: str = "full-stack"
    archive: Archive | None = None  # hostile archive instead of a folder return
    forbid: str | None = None      # check id that must NOT fire


def _sub(path: Path, old: str, new: str) -> None:
    text = path.read_text(encoding="utf-8")
    if old not in text:
        raise AssertionError(f"self-test fixture drifted: «{old[:40]}» not found in {path.name}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _feat(ret: Path, name: str) -> Path:
    return ret / "FEAT-999" / name


def _vis(ret: Path, name: str) -> Path:
    return ret / "VISION" / name


def _only_vision(_repo: Path, ret: Path) -> None:
    shutil.rmtree(ret / "FEAT-999")
    head = (ret / "MANIFEST.yaml").read_text(encoding="utf-8").split("features:", 1)[0]
    _write(ret / "MANIFEST.yaml", head + "features: []\n")


def _strip_tokens(_repo: Path, ret: Path) -> None:
    import re
    for name in ("style_guide.html", "app_shell.html"):
        page = _vis(ret, name)
        _write(page, re.sub(r"<style>.*?</style>", "", page.read_text(encoding="utf-8"), flags=re.S))


def _scope_from_repo(repo: Path, ret: Path) -> None:
    """No scope in the ERQ, no mock: the scope must come from the journey already in the repo."""
    _sub(_feat(ret, "ERQ.md"), 'scope: "backend-only"\n', "")
    _write(repo / "docs" / "spec" / "FEAT-999" / "user_journey.md", F.journey("FEAT-999", "backend-only", True))


def _gate(body: str) -> Mutation:
    return lambda repo, _ret: _write(repo / "scripts" / "check-journey-grammar.sh", body)


_STEPPER = '<section id="stepper" data-component="Stepper"><h2>Stepper</h2></section></main>'
_WAITLIST = ("### Waitlist\n\n| Field | Meaning | Required | Allowed values (plain language) | Example |\n"
             "|---|---|---|---|---|\n| booking_day | Day | Yes | Any | Friday |\n\n## Section 7:")
_DEPOSIT_ROW = "| deposit_amount | Money held | No | Any | 10 |\n| party_size |"
_ERROR_STATE = '  <div data-state="error"><p>That day is fully booked. The next open day is Saturday.</p></div>\n'


def _member(name: str, size: int = 1, mode: int | None = None) -> Archive:
    def build(root: Path) -> Path:
        target = root / "hostile.zip"
        with zipfile.ZipFile(target, "w") as archive:
            info = zipfile.ZipInfo(name)
            if mode is not None:
                info.external_attr = mode << 16
            archive.writestr(info, "x" * size)
        return target
    return build


def _many_members(root: Path) -> Path:
    target = root / "hostile.zip"
    with zipfile.ZipFile(target, "w") as archive:
        for index in range(6):
            archive.writestr(f"f{index}.txt", "x")
    return target


def _garbage(root: Path) -> Path:
    target = root / "hostile.zip"
    target.write_bytes(b"this is not a zip archive at all")
    return target


CASES: list[Case] = [
    # ── golden: not one finding ──
    Case("G1 clean feature return", with_vision=False),
    Case("G2 clean design-system return", mutate=_only_vision),
    Case("G3 backend-only feature, no mock", with_vision=False, scope="backend-only"),
    Case("G4 clean combined return"),
    Case("G5 host loaded by the framework templates is allowed",
         mutate=lambda r, t: _sub(_feat(t, "mock.html"), "<style>", '<script src="https://allowed.example/lib.js"></script><style>')),
    Case("G6 scope falls back to the journey already in the repo", with_vision=False, scope="backend-only",
         mutate=_scope_from_repo),
    Case("G7 a new field declared in the evolution request is not flagged", with_vision=False,
         mutate=lambda r, t: (_sub(_feat(t, "user_journey.md"), "| party_size |", _DEPOSIT_ROW),
                              _sub(_feat(t, "ERQ.md"), "new_names: []", 'new_names:\n  - name: "deposit_amount"\n'
                                   '    kind: "field"\n    why_not_reused: "Nothing in the glossary holds money."'))),
    Case("G8 a new component declared in the evolution request is not flagged",
         mutate=lambda r, t: (_sub(_vis(t, "component_library.html"), "</main>", _STEPPER),
                              _sub(_vis(t, "ERQ.md"), "new_components: []", 'new_components:\n  - id: "stepper"\n'
                                   '    name: "Stepper"\n    why_not_reused: "Tabs do not show an ordered sequence."'))),
    Case("G9 a navigation link to another site is not a dependency", with_vision=False,
         mutate=lambda r, t: _sub(_feat(t, "mock.html"), "<h1>Pick a day</h1>",
                                  '<h1>Pick a day</h1><a href="https://venue.example/help">Help</a>')),
    # ── journey gate, delegated ──
    Case("R1 translated section header", "journey-grammar", "ERROR",
         lambda r, t: _sub(_feat(t, "user_journey.md"), "## Section 2: Journey Steps", "## Sección 2: Pasos")),
    Case("R2 technical type in the business contract", "journey-grammar", "ERROR",
         lambda r, t: _sub(_feat(t, "user_journey.md"), "One to twelve people", "decimal(10,2)")),
    Case("R3 step cites a scenario that does not exist", "journey-grammar", "ERROR",
         lambda r, t: _sub(_feat(t, "user_journey.md"), "- **BDD Scenario:** Guest confirms the booking",
                           "- **BDD Scenario:** Guest pays a deposit")),
    Case("R4 step points at a mock anchor that does not exist", "journey-grammar", "ERROR",
         lambda r, t: _sub(_feat(t, "user_journey.md"), "- **Mock Action:** #step-2", "- **Mock Action:** #step-9")),
    Case("R5 journey gate missing", "journey-grammar-infra", "BLOCKER",
         lambda r, t: (r / "scripts" / "check-journey-grammar.sh").unlink(), message="is missing"),
    Case("R5b journey gate crashes", "journey-grammar-infra", "BLOCKER", _gate("exit 3\n"), message="exit 3"),
    Case("R5c journey gate fails without naming a violation", "journey-grammar-infra", "BLOCKER",
         _gate("echo broken; exit 1\n"), message="exit 1"),
    # ── vocabulary ──
    Case("R6 undeclared new field", "field-new-undeclared", "WARN",
         lambda r, t: _sub(_feat(t, "user_journey.md"), "| party_size |", _DEPOSIT_ROW)),
    Case("R6b undeclared new rule", "name-new-undeclared", "WARN",
         lambda r, t: _sub(_feat(t, "user_journey.md"), "| P1 | RULE-BOOK-01 |", "| P1 | RULE-BOOK-02 |"), message="RULE-BOOK-02"),
    Case("R7 undeclared new concept", "name-new-undeclared", "WARN",
         lambda r, t: _sub(_feat(t, "user_journey.md"), "## Section 7:", _WAITLIST), message="Waitlist"),
    # ── external dependencies ──
    Case("R8 external dependency outside the allowlist", "external-deps", "ERROR",
         lambda r, t: _sub(_feat(t, "mock.html"), "<style>", '<script src="https://cdn.not-allowed.example/x.js"></script><style>')),
    Case("R8b unquoted attribute value does not slip through", "external-deps", "ERROR",
         lambda r, t: _sub(_feat(t, "mock.html"), "<style>", "<script src=https://cdn.unquoted.example/x.js></script><style>"),
         message="cdn.unquoted.example"),
    Case("R8c stylesheet import does not slip through", "external-deps", "ERROR",
         lambda r, t: _sub(_feat(t, "mock.html"), "<style>", '<style>@import "https://css.not-allowed.example/a.css";'),
         message="css.not-allowed.example"),
    # ── evolution request ──
    Case("R9 change without a business reason", "erq-change-incomplete", "ERROR",
         lambda r, t: _sub(_feat(t, "ERQ.md"), '    business_reason: "Guests abandon when confirmation takes more than one step."\n', "")),
    Case("R10 new name without justification", "new-name-unjustified", "ERROR",
         lambda r, t: _sub(_feat(t, "ERQ.md"), "new_names: []", 'new_names:\n  - name: "deposit_amount"\n    kind: "field"')),
    Case("R10b new names written as bare texts is a finding, not a crash", "erq-fields", "ERROR",
         lambda r, t: _sub(_feat(t, "ERQ.md"), "new_names: []", 'new_names: ["deposit_amount"]'), message="new_names"),
    Case("R10c changes written as a number is a finding, not a crash", "erq-fields", "ERROR",
         lambda r, t: _sub(_feat(t, "ERQ.md"), "new_names: []", "new_components: 3"), message="new_components"),
    Case("R20 evolution request without header", "erq-header", "BLOCKER",
         lambda r, t: _write(_feat(t, "ERQ.md"), "# no header\n")),
    Case("R20b evolution request header is a list", "erq-header", "BLOCKER",
         lambda r, t: _write(_feat(t, "ERQ.md"), "---\n- a\n- b\n---\n"), message="mapping"),
    Case("R21 unknown classification", "erq-fields", "ERROR",
         lambda r, t: _sub(_feat(t, "ERQ.md"), 'classification: "delta"', 'classification: "minor"'), message="classification"),
    Case("R21b feature id does not match its folder", "erq-fields", "ERROR",
         lambda r, t: _sub(_feat(t, "ERQ.md"), 'feature_id: "FEAT-999"', 'feature_id: "FEAT-100"'), message="FEAT-100"),
    Case("R21c request without changes", "erq-fields", "ERROR",
         lambda r, t: _sub(_feat(t, "ERQ.md"), "changes:\n", "changes: []\nignored:\n"), message="`changes`"),
    Case("R21d vision request inside a feature folder", "erq-fields", "ERROR",
         lambda r, t: _sub(_feat(t, "ERQ.md"), 'target: "feature"', 'target: "vision"'), message="`target`"),
    # ── manifest ──
    Case("R11a folder not listed in the manifest", "manifest", "ERROR", with_vision=False, message="not listed",
         mutate=lambda r, t: _write(t / "MANIFEST.yaml", "package: {}\nfeatures: []\n")),
    Case("R11b manifest lists a folder that did not come", "manifest", "ERROR", message="has no folder",
         mutate=lambda r, t: _sub(t / "MANIFEST.yaml", "    self_checked: true\n\nreviewed",
                                  '    self_checked: true\n  - feature_id: "FEAT-123"\n    self_checked: true\n\nreviewed')),
    Case("R11c manifest is a list", "manifest", "BLOCKER", message="mapping",
         mutate=lambda r, t: _write(t / "MANIFEST.yaml", "- a\n")),
    Case("R11d vision block without its folder", "manifest", "ERROR", message="come together",
         mutate=lambda r, t: shutil.rmtree(t / "VISION")),
    Case("R11e manifest missing", "manifest", "BLOCKER", message="is missing",
         mutate=lambda r, t: (t / "MANIFEST.yaml").unlink()),
    Case("R22 checklist not walked", "self-check", "WARN",
         lambda r, t: _sub(t / "MANIFEST.yaml", "    self_checked: true", "    self_checked: false")),
    # ── gherkin ──
    Case("R12 spec without scenarios", "gherkin", "BLOCKER",
         lambda r, t: _write(_feat(t, "spec.feature"), "Feature: Empty\n"), message="no `Scenario:`"),
    Case("R12b spec without a feature line", "gherkin", "BLOCKER",
         lambda r, t: _sub(_feat(t, "spec.feature"), "Feature: Table booking", "Table booking"), message="`Feature:`"),
    Case("R13 duplicated scenario title", "gherkin", "ERROR",
         lambda r, t: _sub(_feat(t, "spec.feature"), "Scenario: Guest opens the booking with no open days",
                           "Scenario: Guest picks a fully booked day"), message="duplicated"),
    # ── structure ──
    Case("R19 UI feature without a mock", "structure", "BLOCKER",
         lambda r, t: _feat(t, "mock.html").unlink(), message="missing"),
    Case("R27 empty journey is never a silent pass", "structure", "BLOCKER",
         lambda r, t: _write(_feat(t, "user_journey.md"), ""), message="empty"),
    Case("R26 folder that is neither VISION nor a feature id", "structure", "ERROR",
         lambda r, t: shutil.copytree(t / "FEAT-999", t / "booking-waitlist"), message="NOT reviewed"),
    Case("R29 file that is not UTF-8", "structure", "ERROR",
         lambda r, t: _feat(t, "spec.feature").write_bytes(_feat(t, "spec.feature").read_bytes() + "# caf\xe9\n".encode("cp1252")),
         message="UTF-8"),
    Case("R32 return with nothing in it", "structure", "BLOCKER", message="neither",
         mutate=lambda r, t: (shutil.rmtree(t / "FEAT-999"), shutil.rmtree(t / "VISION"))),
    # ── mock ──
    Case("R24 page without a language", "a11y-basics", "WARN",
         lambda r, t: _sub(_feat(t, "mock.html"), '<html lang="en">', "<html>"), message="lang"),
    Case("R24b image without alternative text", "a11y-basics", "WARN",
         lambda r, t: _sub(_feat(t, "mock.html"), "<h1>Pick a day</h1>", '<h1>Pick a day</h1><img src="a.png">'), message="alt"),
    Case("R24c shell without a navigation landmark", "a11y-basics", "WARN",
         lambda r, t: _sub(_vis(t, "app_shell.html"), '<nav aria-label="Primary"><a href="#bookings">Bookings</a></nav>', ""),
         message="<nav>"),
    Case("R25 step without its error state", "mock-states", "WARN",
         lambda r, t: _sub(_feat(t, "mock.html"), _ERROR_STATE, ""), message="error"),
    # ── design system ──
    Case("R14 design-system file missing", "vision-files", "BLOCKER",
         lambda r, t: _vis(t, "page_templates.html").unlink(), message="missing"),
    Case("R14b design-system return without its evolution request", "structure", "BLOCKER",
         lambda r, t: _vis(t, "ERQ.md").unlink(), message="missing"),
    Case("R14c design-system file empty", "vision-files", "BLOCKER",
         lambda r, t: _write(_vis(t, "navigation_map.md"), "\n"), message="empty"),
    Case("R15 no design tokens declared", "vision-tokens-declared", "ERROR", _strip_tokens),
    Case("R16 component library without component anchors", "vision-components-parseable", "ERROR",
         lambda r, t: _write(_vis(t, "component_library.html"),
                             '<html lang="en"><body><main><section id="x"><h2>X</h2></section></main></body></html>'),
         message="no top-level"),
    Case("R16b duplicated component id", "vision-components-parseable", "ERROR",
         lambda r, t: _sub(_vis(t, "component_library.html"), "</main>",
                           '<section id="button" data-component="Button"><h2>Again</h2></section></main>'), message="more than once"),
    Case("R16c core component absent", "vision-components-parseable", "WARN",
         lambda r, t: _sub(_vis(t, "component_library.html"), 'id="card" data-component="Card"', 'id="panel" data-component="Panel"'),
         message="«card»"),
    Case("R30 component id that would become a path", "vision-components-parseable", "ERROR",
         lambda r, t: _sub(_vis(t, "component_library.html"), "</main>",
                           '<section id="../../../escape" data-component="Evil"><h2>Evil</h2></section></main>'), message="slug"),
    Case("R30b token group id that is not a slug", "vision-components-parseable", "ERROR",
         lambda r, t: _sub(_vis(t, "style_guide.html"), 'id="colors"', 'id="Brand Colors"'), message="slug"),
    Case("R31 component section never closed", "vision-components-parseable", "ERROR",
         lambda r, t: _sub(_vis(t, "component_library.html"), "<div>Body</div></section>", "<div>Body</div>"), message="never closed"),
    Case("R17 undeclared new component", "vision-component-undeclared", "WARN",
         lambda r, t: _sub(_vis(t, "component_library.html"), "</main>", _STEPPER)),
    Case("R23 factory-owned header returned in the vision", "vision-frontmatter-leak", "WARN",
         lambda r, t: _write(_vis(t, "vision.md"), "---\nstatus: APPROVED\n---\n\n# Vision\n")),
    # ── hostile archives: never extracted ──
    Case("R18 archive escapes its folder", "zip-safety", "BLOCKER", archive=_member("../escaped.txt"), message="escapes"),
    Case("R18b absolute path", "zip-safety", "BLOCKER", archive=_member("/etc/owned.txt"), message="absolute"),
    Case("R18c drive-letter path", "zip-safety", "BLOCKER", archive=_member("C:\\owned.txt"), message="absolute"),
    Case("R18d symbolic link", "zip-safety", "BLOCKER", archive=_member("link", mode=stat.S_IFLNK | 0o777), message="symbolic"),
    Case("R18e oversized member", "zip-safety", "BLOCKER", archive=_member("big.txt", size=64), message="oversized"),
    Case("R18f too many entries", "zip-safety", "BLOCKER", archive=_many_members, message="too many"),
    Case("R18g not an archive", "zip-safety", "BLOCKER", archive=_garbage, message="not a readable zip"),
]

_LIMITS = {"MAX_MEMBER_BYTES": 32, "MAX_ZIP_ENTRIES": 5}   # small caps so the hostile archives stay tiny


def _validate(case: Case, root: Path, grammar: Path, cfg: dict) -> tuple[V.Report, str | None]:
    repo = F.emit_repo(root, grammar)
    if case.archive:
        with mock.patch.multiple(L, **_LIMITS), mock.patch.object(zipfile.ZipFile, "extractall") as extract:
            rep = V.validate_zip(case.archive(root), repo, cfg)
        return rep, ("a hostile archive was extracted" if extract.called else None)
    ret = F.emit_return(root, with_vision=case.with_vision, scope=case.scope)
    if case.mutate:
        case.mutate(repo, ret)
    return V.validate_dir(ret, repo, cfg), None


def _is_hit(case: Case, finding: V.Finding) -> bool:
    return (finding.check == case.expect and finding.severity == case.severity
            and (case.message or "") in finding.message)


def _verdict_follows_severity(case: Case, rep: V.Report) -> str | None:
    """RED versus GREEN is the product: a severity that stops moving the verdict is a disabled gate."""
    alone = all(f.check == case.expect for f in rep.findings)
    if case.severity == "WARN" and alone and rep.blocking:
        return "a WARN-only return must stay GREEN"
    if case.severity != "WARN" and not rep.blocking:
        return f"a {case.severity} finding must make the return RED"
    return None


def _verdict(case: Case, rep: V.Report) -> str | None:
    if case.forbid in {f.check for f in rep.findings}:
        return f"«{case.forbid}» fired and must not"
    if case.expect is None:
        found = [f"{f.check}: {f.message}" for f in rep.findings]
        return f"expected no finding at all, got {found}" if found else None
    if not any(_is_hit(case, f) for f in rep.findings):
        saw = sorted((f.check, f.severity) for f in rep.findings)
        return f"«{case.expect}» [{case.severity}] «{case.message or ''}» did not fire (saw {saw})"
    return _verdict_follows_severity(case, rep)


def _run_case(case: Case, grammar: Path, cfg: dict) -> str | None:
    """None when the case behaves; otherwise the reason it does not."""
    with tempfile.TemporaryDirectory(prefix="po-selftest-") as tmp:
        rep, fault = _validate(case, Path(tmp), grammar, cfg)
    return fault or _verdict(case, rep)


def _check_ids_in_source() -> tuple[set[str], set[str]]:
    """(ids passed literally as the 3rd argument of `.add`, every string constant of the module).

    Helpers receive the check id as a parameter, so a literal scan of `.add` alone would
    miss them; any declared id must at least appear somewhere as a constant."""
    tree = ast.parse(Path(V.__file__).read_text(encoding="utf-8"))
    direct: set[str] = set()
    constants: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            constants.add(node.value)
        is_add = isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr == "add"
        if is_add and len(node.args) >= 3 and isinstance(node.args[2], ast.Constant):
            direct.add(node.args[2].value)
    return direct, constants


def _coverage_gaps() -> list[str]:
    declared = set(V.ALL_CHECKS)
    direct, constants = _check_ids_in_source()
    covered = {c.expect for c in CASES if c.expect}
    named = {c.expect for c in CASES} | {c.forbid for c in CASES}
    gaps = [f"check «{c}» is raised but not declared in ALL_CHECKS" for c in sorted(direct - declared)]
    gaps += [f"check «{c}» is declared but nothing in the validator names it" for c in sorted(declared - constants)]
    gaps += [f"check «{c}» has no red case — a check that only sees green is decoration" for c in sorted(declared - covered)]
    gaps += [f"a case names «{c}», which is not a check id — it would pass vacuously" for c in sorted(named - declared - {None})]
    gaps += [f"case «{c.name}» expects a finding but states no severity" for c in CASES if c.expect and c.severity not in V.SEVERITIES]
    return gaps


def run(grammar: Path) -> int:
    if not grammar.exists():
        print(f"SELFTEST CANNOT RUN: the journey gate is missing at {grammar}")
        return 2
    cfg = L.merge_config(L.DEFAULT_CONFIG, F.FIXTURE_CONFIG)
    failures = 0
    for case in CASES:
        reason = _run_case(case, grammar, cfg)
        failures += 1 if reason else 0
        print(f"  {'FAIL' if reason else 'ok  '}  {case.name}" + (f" — {reason}" if reason else ""))
    for gap in _coverage_gaps():
        failures += 1
        print(f"  FAIL  coverage — {gap}")
    print(f"\nselftest: {len(CASES)} cases, {failures} failure(s)")
    return 1 if failures else 0
