#!/usr/bin/env bash
# Generated by Phase: IMPLEMENT | Feature: EVOL-049
# ============================================================================
# check-agent-spawn.sh — PreToolUse hook (Agent): a roster agent spawns on its family's alias, never on the other's.
# Writers and critics live on different model families by construction (rules/agents.md · config/quality.json →
# agents.families); the definition carries no model, so the spawn must pass one — this hook is the mechanical hold.
# ONE definition: python3 scripts/gate.py agents --spawn --hook-json (exit 1 = refused). Exit 2 + stderr = the blocking
# contract. A subagent_type outside the framework's names (`factory-*`) is not ours: pass without asking the reader.
# The reader missing or the policy unreadable on a framework name → fail closed (the roster needs SETUP --upgrade, Q34).
# ============================================================================
cd "${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}" || exit 0
INPUT=$(cat)
TYPE=$(printf '%s' "$INPUT" | python3 -c 'import json,sys
try: print((json.load(sys.stdin).get("tool_input") or {}).get("subagent_type") or "")
except Exception: print("")' 2>/dev/null)
case "$TYPE" in factory-*) ;; *) exit 0 ;; esac
if [ ! -f scripts/gate.py ] || ! command -v python3 >/dev/null 2>&1; then
  echo "BLOCKED: $TYPE is a framework agent but the gate reader (scripts/gate.py) is not delivered — run factory-sync.sh, then SETUP --upgrade (Q34)." >&2; exit 2
fi
OUT=$(printf '%s' "$INPUT" | python3 scripts/gate.py agents --spawn --hook-json 2>&1); RC=$?
case "$RC" in
  0) exit 0 ;;
  1) { echo "BLOCKED: a roster agent spawns on its family's alias."; echo "$OUT"; } >&2; exit 2 ;;
  *) { echo "BLOCKED: the class policy could not be read for $TYPE (rules/agents.md + config/quality.json → agents.families — SETUP --upgrade, Q34)."; echo "$OUT"; } >&2; exit 2 ;;
esac
