#!/usr/bin/env bash
# Generated by Agent: IMPLEMENT | Feature: EVOL-011
# ============================================================================
# check-branch-protection.sh — PreToolUse hook: block Edit/Write on protected branches
# ============================================================================
# Reads stdin JSON from Claude Code hook protocol.
# Exit 2 + message on stderr = the Claude Code blocking contract for PreToolUse hooks
# (exit 1 is a NON-blocking error: the tool would run anyway — EVOL-043 hook audit).
# ============================================================================

branch=$(git branch --show-current 2>/dev/null || echo '')
if [ -z "$branch" ]; then
  exit 0
fi

if echo "$branch" | grep -qE '^(main|master|develop|release(/.+)?|hotfix)$'; then
  {
    echo "BLOCKED: on protected branch '$branch'. Create a working branch first. Allowed patterns:"
    echo "  feature/ID-slug   fix/slug   bugfix/slug   hotfix/slug   docs/slug   chore/slug"
    echo "Example: git checkout -b hotfix/my-fix origin/main"
  } >&2
  exit 2
fi

# A train (per-increment branch whose increment plan declares sub-increments) is protected like a base
# branch (EVOL-045): the reader classifies the name; exit 1 = protected. Reader absent or faulting → pass.
if [ -f scripts/gate.py ] && command -v python3 >/dev/null 2>&1; then
  python3 scripts/gate.py branch-class --protected >/dev/null 2>&1
  if [ $? -eq 1 ]; then
    {
      echo "BLOCKED: '$branch' is a train — its increment plan declares sub-increments, so it takes merges only."
      echo "Commit on a sub-increment branch: git checkout -b ${branch}-sub-<M> origin/${branch}  (one PR each into the train)"
    } >&2
    exit 2
  fi
fi

exit 0
