#!/usr/bin/env bash
# Generated by Phase: IMPLEMENT | Feature: EVOL-048
# ============================================================================
# check-plan-mode.sh — PreToolUse hook (EnterPlanMode): one planning stage, never two.
# A branch class whose plan a framework phase owns (feature, increment, train, sub-increment, epic in a project)
# never enters the harness's plan mode: a second approval would appear to cover decisions the user never made.
# ONE definition: python3 scripts/gate.py plan --enter (exit 1 = blocked). Exit 2 + stderr = the blocking contract.
# Reader absent → pass (plan mode itself writes nothing; the pre-write gate stays fail-closed).
# ============================================================================
cd "${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}" || exit 0
[ -f scripts/gate.py ] && command -v python3 >/dev/null 2>&1 || exit 0
OUT=$(python3 scripts/gate.py plan --enter 2>&1); RC=$?
if [ "$RC" -eq 1 ]; then
  { echo "BLOCKED: one planning stage, never two."; echo "$OUT"; } >&2; exit 2
fi
exit 0
