#!/usr/bin/env bash
# Generated by Phase: IMPLEMENT | Feature: EVOL-048
# ============================================================================
# check-plan-approval.sh — PreToolUse hook (Edit|Write): one planning stage, never zero.
# A write to a governed path on a branch class with no framework planning phase needs an approved plan.
# ONE definition: python3 scripts/gate.py plan --path <file> (config/quality.json → planning). exit 1 = blocked.
# Exit 2 + message on stderr = the Claude Code blocking contract. Fail-closed: a missing python3 or reader, or a
# payload that cannot be read, blocks with the resolution named. A well-formed payload without a file path passes.
# ============================================================================
cd "${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}" || exit 2
if ! command -v python3 >/dev/null 2>&1; then
  echo "BLOCKED: python3 is not on PATH — the planning gate cannot run. Install python3, then retry." >&2; exit 2
fi
if [ ! -f scripts/gate.py ]; then
  echo "BLOCKED: the governance reader (scripts/gate.py) is not delivered — the write cannot be judged against the planning gate. Resolution: bash scripts/factory-sync.sh, then retry." >&2; exit 2
fi
FILE=$(python3 -c '
import json, sys
try:
    d = json.load(sys.stdin); print((d.get("tool_input") or {}).get("file_path") or "")
except Exception:
    print("<<unreadable>>")
' 2>/dev/null)
case "$FILE" in
  "") exit 0 ;;
  "<<unreadable>>") echo "BLOCKED: the hook payload could not be read — the write cannot be judged against the planning gate. Retry the edit." >&2; exit 2 ;;
esac
OUT=$(python3 scripts/gate.py plan --path "$FILE" 2>&1); RC=$?
case "$RC" in
  0) exit 0 ;;
  1) { echo "BLOCKED: no approved plan covers this write to '$FILE'."; echo "$OUT"; } >&2; exit 2 ;;
  *) { echo "BLOCKED: the planning gate could not judge the write to '$FILE' (gate.py plan exit $RC):"; echo "$OUT"; echo "Resolution: see the reason above; fix it from the shell (the shell is not gated) or re-run scripts/factory-sync.sh, then retry."; } >&2; exit 2 ;;
esac
