#!/usr/bin/env bash
# Generated by Phase: IMPLEMENT | Feature: EVOL-048
# ============================================================================
# record-plan-approval.sh — PostToolUse hook (ExitPlanMode): the ONLY writer of the plan-approval marker.
# ExitPlanMode completes only when the user approved the plan; the reader refuses any other payload.
# Never blocks (PostToolUse); a failure is said through the envelope. Marker: .claude/state/plan-approved-<branch>.json
# ============================================================================
[ -f scripts/gate.py ] && command -v python3 >/dev/null 2>&1 || exit 0
OUT=$(python3 scripts/gate.py plan --record --hook-json 2>&1); RC=$?
if [ "$RC" -ne 0 ]; then
  printf '{"hookSpecificOutput":{"hookEventName":"PostToolUse","additionalContext":"plan approval NOT recorded (gate.py plan --record exit %s): %s"}}\n' "$RC" "$(printf '%s' "$OUT" | tr -d '"\\' | head -c 300)"
fi
exit 0
